// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"hash/maphash"
	"io"
	"log/slog"
	"net/http"
	"runtime/debug"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/httpserve"
	dpsse "github.com/romshark/datapages/runtime/sse"
	"github.com/romshark/datapages/runtime/subject"

	"github.com/romshark/datapages/internal/acceptance/stategeneric/app"
	"github.com/romshark/datapages/internal/acceptance/stategeneric/app/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

// assetsFileSystem rejects datapages.WithAssets: the app package declares no
// embed.FS with a URL path in its doc comment, hence there is nothing to serve.
func assetsFileSystem(cfg datapages.ServerConfig) (http.FileSystem, error) {
	if cfg.AssetsFS != nil {
		return cfg.AssetsFS, nil
	}
	if cfg.AssetsEmbed != nil {
		return nil, errors.New(
			"datapages.WithAssets: the app package declares no assets",
		)
	}
	return nil, nil
}

// brokerMetrics implements messaging.Metrics as a no-op.
type brokerMetrics struct{}

func (m brokerMetrics) OnPublish(subject string) {}
func (m brokerMetrics) OnDeliveryDropped()       {}

// --- Message Broker ---

const DefaultBodySizeLimit = 1024 * 1024 // 1 MiB

func (s *Server) httpErrBad(w http.ResponseWriter, msg string, err error) {
	s.Logger().Debug("bad request", slog.String("cause", msg), slog.Any("err", err))
	http.Error(w, msg, http.StatusBadRequest)
}

func (s *Server) checkIsDSReq(w http.ResponseWriter, r *http.Request) (ok bool) {
	if !httpserve.IsDatastarRequest(r) {
		s.Logger().Debug("not a datastar request",
			slog.Any("method", r.Method),
			slog.String("path", r.URL.Path))
		http.Error(w, http.StatusText(http.StatusNotAcceptable), http.StatusNotAcceptable)
		return false
	}
	return true
}

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	_, err := io.WriteString(w, s.HTMLHead())
	if err != nil {
		return err
	}
	// The instance id is a bearer credential: presenting it claims a tab's state.
	// The script below closes over the id and then drops its own node.
	// The closure is what the fetch wrapper reads, and no copy is
	// left in the DOM for a later reader to lift, a session replay
	// recorder or an error reporter included. The response body still
	// carries the id, which is what the page's Cache-Control: no-store is for.
	if id := w.Header().Get(stateInstanceIDHeader); s.verifyStateInstanceID(id) {
		if _, err := io.WriteString(w, `<script>(() => {
		let __dpInstance="`); err != nil {
			return err
		}
		if _, err := io.WriteString(w, id); err != nil {
			return err
		}
		if _, err := io.WriteString(w, `"
		document.currentScript?.remove()
		const k="datapages-reloaded:"+location.pathname
		const mark=v => { try { v ? sessionStorage.setItem(k,"1"):sessionStorage.removeItem(k) } catch {} }
		const marked=() => { try { return !!sessionStorage.getItem(k) } catch { return false } }
		const o2 = globalThis.fetch.bind(globalThis)
		globalThis.fetch=(i,init={}) => {
			const isReq=i instanceof Request
			const r=isReq ? i:new Request(i,init)
			if (r.headers.get("Datastar-Request")!=="true" ||
				new URL(r.url,location.href).origin!==location.origin
			) return isReq ? o2(r,init):o2(r)
			const h=new Headers(r.headers)
			if (__dpInstance) h.set("Datapages-Instance",__dpInstance)
			return o2(new Request(r,{...init,headers:h})).then(resp => {
				if (resp.status===409 && resp.headers.get("Datapages-Retry")==="reconnect") {
					__dpInstance=""
					if (!marked()) {
						mark(true)
						location.reload()
					}
				} else if (resp.ok) {
					mark(false)
				}
				return resp
			})
		}
		globalThis.addEventListener("pageshow", e => {
			if (e.persisted) location.reload()
		})
	})()</script>`); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, s.HTMLDatastarScript()); err != nil {
		return err
	}
	if head != nil {
		if err := head.Render(r.Context(), w); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "</head><body "); err != nil {
		return err
	}
	if writeBodyAttrs != nil {
		writeBodyAttrs(w)
	}
	if _, err := io.WriteString(w, ">"); err != nil {
		return err
	}
	if body != nil {
		if err := body.Render(r.Context(), w); err != nil {
			return err
		}
	}
	if writeBodySuffix != nil {
		if _, err := io.WriteString(w, "<template "); err != nil {
			return err
		}
		writeBodySuffix(w)
		if _, err := io.WriteString(w, "></template>"); err != nil {
			return err
		}
	}
	_, err = io.WriteString(w, "</body></html>")
	return err
}

func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request,
	subjects []string,
	onOpen func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
	) error,
	onClose func(streamID datapages.StreamID),
	fn func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
		ch <-chan messaging.Message,
	),
) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	streamID := datapages.StreamID(s.streamSeq.Add(1))

	// The subscription is established before the response head goes out.
	// A client learns the stream is open by reading that head and may dispatch
	// immediately after, which must not reach the broker before this.
	ctx := r.Context()
	sub, err := s.messageBroker.Subscribe(ctx, s.messageBrokerMetrics, subjects...)
	if err != nil {
		// Nothing has been written yet, so the error can still carry a status.
		s.httpErrIntern(w, r, nil, "subscribing to message broker", err)
		return
	}

	sse := datastar.NewSSE(w, r, datastar.WithCompression())

	subC := sub.C()
	if onOpen != nil {
		if err := onOpen(streamID, sse); err != nil {
			sub.Close()
			s.httpErrIntern(w, r, sse, "handling stream open hook", err)
			return
		}
	}
	go func() {
		select {
		case <-r.Context().Done():
		case <-s.ShutdownCh():
		}
		sub.Close()
		if onClose != nil {
			// Not the goroutine net/http recovers.
			defer func() {
				if rec := recover(); rec != nil {
					s.LogErr("recovering panic in stream close hook",
						fmt.Errorf("%v\n%s", rec, debug.Stack()))
				}
			}()
			onClose(streamID)
		}
	}()

	fn(streamID, sse, subC)
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics brokerMetrics
	streamSeq            atomic.Uint64
	app                  *app.App

	stateConf *datapages.StateConfig
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[app.App, datapages.DisableSessions, datapages.DisablePrometheus, Server](app, broker, opts...)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *app.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[datapages.DisableSessions],
) error {
	if sessionManager != nil {
		return errors.New("unexpected option WithSessionManager: package app declares no session type")
	}
	if cfg.MetricsServer != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}
	if cfg.State == nil {
		return errors.New("missing option WithStateConfig: " +
			"this app has stateful pages")
	}

	assetsFS, err := assetsFileSystem(cfg)
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core = httpserve.NewCore(cfg, "")
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = brokerMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}
	s.stateConf = cfg.State

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.Logger())

	return nil
}

const (

	// Public events:

	EvSubjPing = "ping.*"
)

const (
	EvSubjPrefPing = "ping."
)

func MessageBrokerStreamSubjects() []string {
	return []string{
		EvSubjPing,
	}
}

func evSubjPageCount(stateID string) []string {
	return []string{
		EvSubjPrefPing + stateID,
	}
}

func evSubjPageEmbedOnly(stateID string) []string {
	return []string{
		EvSubjPrefPing + stateID,
	}
}

func evSubjPageLabel(stateID string) []string {
	return []string{
		EvSubjPrefPing + stateID,
	}
}

func evSubjPageNested(stateID string) []string {
	return []string{
		EvSubjPrefPing + stateID,
	}
}

func evSubjPagePointer(stateID string) []string {
	return []string{
		EvSubjPrefPing + stateID,
	}
}

// stateInstanceIDHeader is the request/response header used to carry the
// server-issued per-page-instance identifier.
const stateInstanceIDHeader = "Datapages-Instance"

// stateRetryHeader signals the client to reconnect before retrying an
// action that was rejected because no live instance was found.
const stateRetryHeader = "Datapages-Retry"

// stateRetryReconnect is the only value currently emitted on stateRetryHeader.
const stateRetryReconnect = "reconnect"

// stateInstanceIDSep separates payload and signature in a Datapages-Instance value.
// It must not be "." and must not appear in the base64url alphabet:
// the identifier is used verbatim as a single message-broker subject token
// (see the SubjectStateID event routing), and "." would split it in two,
// breaking single-token wildcard matching.
const stateInstanceIDSep = '~'

// stateInstanceIDTag and the tag stateRouteKey writes name what each MAC is for.
// One key, two derivations: without a tag of its own on each,
// a value computed for one of them is a value the other would accept.
var stateInstanceIDTag = []byte("datapages-instance\x00")

// signStateInstanceID produces an HMAC-signed Datapages-Instance value.
// The payload is 16 random bytes; the output is:
// base64url(payload) + "~" + base64url(hmacSHA256(tag, payload)).
func (s *Server) signStateInstanceID() (string, error) {
	if s.stateConf == nil {
		return "", errors.New("state runtime not configured")
	}
	var payload [16]byte
	if _, err := rand.Read(payload[:]); err != nil {
		return "", err
	}
	mac := hmac.New(sha256.New, s.stateConf.HMACKey)
	mac.Write(stateInstanceIDTag)
	mac.Write(payload[:])
	return base64.RawURLEncoding.EncodeToString(payload[:]) +
		string(stateInstanceIDSep) +
		base64.RawURLEncoding.EncodeToString(mac.Sum(nil)), nil
}

// verifyStateInstanceID returns true when the supplied Datapages-Instance
// value is well-formed and signed by the server's HMAC key.
func (s *Server) verifyStateInstanceID(id string) bool {
	if s.stateConf == nil || id == "" {
		return false
	}
	sep := strings.IndexByte(id, stateInstanceIDSep)
	if sep <= 0 || sep == len(id)-1 {
		return false
	}
	payload, err := base64.RawURLEncoding.DecodeString(id[:sep])
	if err != nil {
		return false
	}
	sig, err := base64.RawURLEncoding.DecodeString(id[sep+1:])
	if err != nil {
		return false
	}
	mac := hmac.New(sha256.New, s.stateConf.HMACKey)
	mac.Write(stateInstanceIDTag)
	mac.Write(payload)
	return hmac.Equal(mac.Sum(nil), sig)
}

// stateRouteKey derives the value that names a tab in message broker subjects.
// Subjects travel further than a request does: into broker logs,
// stream storage, traces and metrics. The Datapages-Instance id itself
// stays out of them, since presenting it is what claims a tab's state.
// Knowing the routing key only lets a dispatcher address that tab.
//
// Callers must verify the id first.
func (s *Server) stateRouteKey(id string) string {
	mac := hmac.New(sha256.New, s.stateConf.HMACKey)
	mac.Write([]byte("datapages-route\x00"))
	mac.Write([]byte(id))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil)[:16])
}

// stateLiveInstances counts the instances of every state type.
// Memory is shared between them,
// and so is the budget in datapages.StateConfig.MaxConcurrentInstances.
var stateLiveInstances atomic.Int64

// stateNoInstanceLimit is what a negative MaxConcurrentInstances means:
// no budget at all. The counter is still kept, since releases decrement it
// unconditionally and a configuration is free to change between processes.
func (s *Server) stateNoInstanceLimit() bool {
	return s.stateConf.MaxConcurrentInstances < 0
}

// stateReserveInstance takes one slot out of the budget. It reports false
// when the server is full, which fails the stream open that asked for it.
// An unlimited server serves every caller.
func (s *Server) stateReserveInstance() bool {
	n := stateLiveInstances.Add(1)
	if s.stateNoInstanceLimit() {
		return true
	}
	if n > int64(s.stateConf.MaxConcurrentInstances) {
		stateLiveInstances.Add(-1)
		return false
	}
	return true
}

// stateHasCapacity reports whether the budget has room right now.
// It is a look, not a claim, and callers use it before a stream commits its status line.
// stateReserveInstance is what actually holds the bound.
func (s *Server) stateHasCapacity() bool {
	if s.stateNoInstanceLimit() {
		return true
	}
	return stateLiveInstances.Load() < int64(s.stateConf.MaxConcurrentInstances)
}

// errStateAtCapacity fails a stream open that finds no free instance.
var errStateAtCapacity = errors.New("state instance limit reached")

// stateStoreShards is how many independent maps a stateStore spreads its keys over.
// Instance ids are random, so they distribute evenly,
// and each shard carries its own lock.
const stateStoreShards = 32

// stateStoreSeed randomizes shard selection per process.
var stateStoreSeed = maphash.MakeSeed()

// stateStoreShard is one lock and the keys that belong to it.
type stateStoreShard[S any] struct {
	mu sync.RWMutex
	m  map[string]*S
}

// stateStore maps a verified Datapages-Instance id to the live slot it names.
//
// Every key is written once and deleted once, and none is read after its deletion.
// That is the opposite of what sync.Map is tuned for,
// which is a read-mostly set of stable keys. Sharded plain maps read without a write
// barrier and delete without leaving a tombstone behind.
//
// The zero value is ready to use.
type stateStore[S any] struct {
	shards [stateStoreShards]stateStoreShard[S]
}

func (s *stateStore[S]) shard(id string) *stateStoreShard[S] {
	return &s.shards[maphash.String(stateStoreSeed, id)%stateStoreShards]
}

// Load returns the slot registered under id, or (nil, false).
func (s *stateStore[S]) Load(id string) (*S, bool) {
	sh := s.shard(id)
	sh.mu.RLock()
	slot, ok := sh.m[id]
	sh.mu.RUnlock()
	return slot, ok
}

// Store registers slot under id, replacing whatever was there.
func (s *stateStore[S]) Store(id string, slot *S) {
	sh := s.shard(id)
	sh.mu.Lock()
	if sh.m == nil {
		sh.m = make(map[string]*S)
	}
	sh.m[id] = slot
	sh.mu.Unlock()
}

// CompareAndDelete removes id only while it still names slot.
// A stream can allocate a fresh slot under an id whose predecessor is on its way out,
// and the one leaving must not take the new one with it.
func (s *stateStore[S]) CompareAndDelete(id string, slot *S) bool {
	sh := s.shard(id)
	sh.mu.Lock()
	defer sh.mu.Unlock()
	if sh.m[id] != slot {
		return false
	}
	delete(sh.m, id)
	return true
}

// stateSlotStateCounter holds one instance of StateCounter.
// It is checked out of statePoolStateCounter on StreamOpen and returned on StreamClose.
// An instance lives exactly as long as the stream that created it:
// a client that reconnects gets a zeroed one.
type stateSlotStateCounter struct {
	state *app.StateCounter
	mu    sync.Mutex // serializes all stateful handler calls on this instance
	dead  bool       // true once the state went back to the pool
}

// statePoolStateCounter pools StateCounter values across instance checkouts.
// Every value is zeroed before it is handed out, so nothing of the
// previous tab reaches the next one.
var statePoolStateCounter = sync.Pool{
	New: func() any { return new(app.StateCounter) },
}

// stateInstancesStateCounter maps a verified Datapages-Instance id to the live slot.
var stateInstancesStateCounter stateStore[stateSlotStateCounter]

// allocateStateCounter checks a state value out of statePoolStateCounter,
// zeroes it, registers it under id, and hands it to the SSE stream that asked for it.
// Returns the slot so callers (StreamOpen) can pass the state to the user,
// or nil when the server holds as many instances as it may.
func (s *Server) allocateStateCounter(id string) *stateSlotStateCounter {
	if !s.stateReserveInstance() {
		return nil
	}
	st := statePoolStateCounter.Get().(*app.StateCounter)
	*st = app.StateCounter{} // nothing of the previous tab survives
	slot := &stateSlotStateCounter{state: st}
	stateInstancesStateCounter.Store(id, slot)
	return slot
}

// lookupStateCounter returns the registered slot for id, or (nil, false)
// when no live instance matches. The id is not HMAC-verified here;
// call verifyStateInstanceID first.
func (s *Server) lookupStateCounter(id string) (*stateSlotStateCounter, bool) {
	return stateInstancesStateCounter.Load(id)
}

// releaseStateCounter returns the slot's state to the pool the moment its stream closes.
// Nothing of the instance outlives the stream: a client that
// reconnects opens a new stream and gets a zeroed state.
//
// The caller passes the slot it allocated rather than the id alone.
// A tab can hold two streams at once while the server still tears the
// older one down, and the second registers its own slot under the same id.
// Releasing by id would give back whichever slot the map holds now.
//
// Calling this twice on one slot releases it once.
func (s *Server) releaseStateCounter(id string, slot *stateSlotStateCounter) {
	slot.mu.Lock()
	if slot.dead {
		slot.mu.Unlock()
		return
	}
	slot.dead = true
	st := slot.state
	slot.state = nil
	slot.mu.Unlock()
	// A stream can allocate a fresh slot under this id while this
	// one is on its way out. Drop only the slot this call owns.
	stateInstancesStateCounter.CompareAndDelete(id, slot)
	stateLiveInstances.Add(-1)
	if st != nil {
		statePoolStateCounter.Put(st)
	}
}

// stateSlotStateLabel holds one instance of StateLabel.
// It is checked out of statePoolStateLabel on StreamOpen and returned on StreamClose.
// An instance lives exactly as long as the stream that created it:
// a client that reconnects gets a zeroed one.
type stateSlotStateLabel struct {
	state *app.StateLabel
	mu    sync.Mutex // serializes all stateful handler calls on this instance
	dead  bool       // true once the state went back to the pool
}

// statePoolStateLabel pools StateLabel values across instance checkouts.
// Every value is zeroed before it is handed out, so nothing of the
// previous tab reaches the next one.
var statePoolStateLabel = sync.Pool{
	New: func() any { return new(app.StateLabel) },
}

// stateInstancesStateLabel maps a verified Datapages-Instance id to the live slot.
var stateInstancesStateLabel stateStore[stateSlotStateLabel]

// allocateStateLabel checks a state value out of statePoolStateLabel,
// zeroes it, registers it under id, and hands it to the SSE stream that asked for it.
// Returns the slot so callers (StreamOpen) can pass the state to the user,
// or nil when the server holds as many instances as it may.
func (s *Server) allocateStateLabel(id string) *stateSlotStateLabel {
	if !s.stateReserveInstance() {
		return nil
	}
	st := statePoolStateLabel.Get().(*app.StateLabel)
	*st = app.StateLabel{} // nothing of the previous tab survives
	slot := &stateSlotStateLabel{state: st}
	stateInstancesStateLabel.Store(id, slot)
	return slot
}

// lookupStateLabel returns the registered slot for id, or (nil, false)
// when no live instance matches. The id is not HMAC-verified here;
// call verifyStateInstanceID first.
func (s *Server) lookupStateLabel(id string) (*stateSlotStateLabel, bool) {
	return stateInstancesStateLabel.Load(id)
}

// releaseStateLabel returns the slot's state to the pool the moment its stream closes.
// Nothing of the instance outlives the stream: a client that
// reconnects opens a new stream and gets a zeroed state.
//
// The caller passes the slot it allocated rather than the id alone.
// A tab can hold two streams at once while the server still tears the
// older one down, and the second registers its own slot under the same id.
// Releasing by id would give back whichever slot the map holds now.
//
// Calling this twice on one slot releases it once.
func (s *Server) releaseStateLabel(id string, slot *stateSlotStateLabel) {
	slot.mu.Lock()
	if slot.dead {
		slot.mu.Unlock()
		return
	}
	slot.dead = true
	st := slot.state
	slot.state = nil
	slot.mu.Unlock()
	// A stream can allocate a fresh slot under this id while this
	// one is on its way out. Drop only the slot this call owns.
	stateInstancesStateLabel.CompareAndDelete(id, slot)
	stateLiveInstances.Add(-1)
	if st != nil {
		statePoolStateLabel.Put(st)
	}
}

// stateSlotStateNested holds one instance of StateNested.
// It is checked out of statePoolStateNested on StreamOpen and returned on StreamClose.
// An instance lives exactly as long as the stream that created it:
// a client that reconnects gets a zeroed one.
type stateSlotStateNested struct {
	state *app.StateNested
	mu    sync.Mutex // serializes all stateful handler calls on this instance
	dead  bool       // true once the state went back to the pool
}

// statePoolStateNested pools StateNested values across instance checkouts.
// Every value is zeroed before it is handed out, so nothing of the
// previous tab reaches the next one.
var statePoolStateNested = sync.Pool{
	New: func() any { return new(app.StateNested) },
}

// stateInstancesStateNested maps a verified Datapages-Instance id to the live slot.
var stateInstancesStateNested stateStore[stateSlotStateNested]

// allocateStateNested checks a state value out of statePoolStateNested,
// zeroes it, registers it under id, and hands it to the SSE stream that asked for it.
// Returns the slot so callers (StreamOpen) can pass the state to the user,
// or nil when the server holds as many instances as it may.
func (s *Server) allocateStateNested(id string) *stateSlotStateNested {
	if !s.stateReserveInstance() {
		return nil
	}
	st := statePoolStateNested.Get().(*app.StateNested)
	*st = app.StateNested{} // nothing of the previous tab survives
	slot := &stateSlotStateNested{state: st}
	stateInstancesStateNested.Store(id, slot)
	return slot
}

// lookupStateNested returns the registered slot for id, or (nil, false)
// when no live instance matches. The id is not HMAC-verified here;
// call verifyStateInstanceID first.
func (s *Server) lookupStateNested(id string) (*stateSlotStateNested, bool) {
	return stateInstancesStateNested.Load(id)
}

// releaseStateNested returns the slot's state to the pool the moment its stream closes.
// Nothing of the instance outlives the stream: a client that
// reconnects opens a new stream and gets a zeroed state.
//
// The caller passes the slot it allocated rather than the id alone.
// A tab can hold two streams at once while the server still tears the
// older one down, and the second registers its own slot under the same id.
// Releasing by id would give back whichever slot the map holds now.
//
// Calling this twice on one slot releases it once.
func (s *Server) releaseStateNested(id string, slot *stateSlotStateNested) {
	slot.mu.Lock()
	if slot.dead {
		slot.mu.Unlock()
		return
	}
	slot.dead = true
	st := slot.state
	slot.state = nil
	slot.mu.Unlock()
	// A stream can allocate a fresh slot under this id while this
	// one is on its way out. Drop only the slot this call owns.
	stateInstancesStateNested.CompareAndDelete(id, slot)
	stateLiveInstances.Add(-1)
	if st != nil {
		statePoolStateNested.Put(st)
	}
}

// stateSlotStatePointer holds one instance of StatePointer.
// It is checked out of statePoolStatePointer on StreamOpen and returned on StreamClose.
// An instance lives exactly as long as the stream that created it:
// a client that reconnects gets a zeroed one.
type stateSlotStatePointer struct {
	state *app.StatePointer
	mu    sync.Mutex // serializes all stateful handler calls on this instance
	dead  bool       // true once the state went back to the pool
}

// statePoolStatePointer pools StatePointer values across instance checkouts.
// Every value is zeroed before it is handed out, so nothing of the
// previous tab reaches the next one.
var statePoolStatePointer = sync.Pool{
	New: func() any { return new(app.StatePointer) },
}

// stateInstancesStatePointer maps a verified Datapages-Instance id to the live slot.
var stateInstancesStatePointer stateStore[stateSlotStatePointer]

// allocateStatePointer checks a state value out of statePoolStatePointer,
// zeroes it, registers it under id, and hands it to the SSE stream that asked for it.
// Returns the slot so callers (StreamOpen) can pass the state to the user,
// or nil when the server holds as many instances as it may.
func (s *Server) allocateStatePointer(id string) *stateSlotStatePointer {
	if !s.stateReserveInstance() {
		return nil
	}
	st := statePoolStatePointer.Get().(*app.StatePointer)
	*st = app.StatePointer{} // nothing of the previous tab survives
	slot := &stateSlotStatePointer{state: st}
	stateInstancesStatePointer.Store(id, slot)
	return slot
}

// lookupStatePointer returns the registered slot for id, or (nil, false)
// when no live instance matches. The id is not HMAC-verified here;
// call verifyStateInstanceID first.
func (s *Server) lookupStatePointer(id string) (*stateSlotStatePointer, bool) {
	return stateInstancesStatePointer.Load(id)
}

// releaseStatePointer returns the slot's state to the pool the moment its stream closes.
// Nothing of the instance outlives the stream: a client that
// reconnects opens a new stream and gets a zeroed state.
//
// The caller passes the slot it allocated rather than the id alone.
// A tab can hold two streams at once while the server still tears the
// older one down, and the second registers its own slot under the same id.
// Releasing by id would give back whichever slot the map holds now.
//
// Calling this twice on one slot releases it once.
func (s *Server) releaseStatePointer(id string, slot *stateSlotStatePointer) {
	slot.mu.Lock()
	if slot.dead {
		slot.mu.Unlock()
		return
	}
	slot.dead = true
	st := slot.state
	slot.state = nil
	slot.mu.Unlock()
	// A stream can allocate a fresh slot under this id while this
	// one is on its way out. Drop only the slot this call owns.
	stateInstancesStatePointer.CompareAndDelete(id, slot)
	stateLiveInstances.Add(-1)
	if st != nil {
		statePoolStatePointer.Put(st)
	}
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /count/{$}",
		s.handlePageCountGET)
	s.Mux().HandleFunc(
		"GET /count/_$/{$}",
		s.handlePageCountGETStream)
	s.Mux().HandleFunc(
		"GET /embed-only/{$}",
		s.handlePageEmbedOnlyGET)
	s.Mux().HandleFunc(
		"GET /embed-only/_$/{$}",
		s.handlePageEmbedOnlyGETStream)
	s.Mux().HandleFunc(
		"GET /",
		s.handlePageIndexGET)
	s.Mux().HandleFunc(
		"GET /label/{$}",
		s.handlePageLabelGET)
	s.Mux().HandleFunc(
		"GET /label/_$/{$}",
		s.handlePageLabelGETStream)
	s.Mux().HandleFunc(
		"GET /nested/{$}",
		s.handlePageNestedGET)
	s.Mux().HandleFunc(
		"GET /nested/_$/{$}",
		s.handlePageNestedGETStream)
	s.Mux().HandleFunc(
		"GET /pointer/{$}",
		s.handlePagePointerGET)
	s.Mux().HandleFunc(
		"GET /pointer/_$/{$}",
		s.handlePagePointerGETStream)
	s.Mux().HandleFunc(
		"POST /count/bump/{$}",
		s.handlePageCountPOSTBump)
	s.Mux().HandleFunc(
		"POST /label/set/{$}",
		s.handlePageLabelPOSTSet)
	s.Mux().HandleFunc(
		"POST /nested/bump/{$}",
		s.handlePageNestedPOSTBump)
	s.Mux().HandleFunc(
		"POST /pointer/bump/{$}",
		s.handlePagePointerPOSTBump)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	_ *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	switch {
	case errors.Is(err, datapages.ErrBadRequest):
		http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
	case errors.Is(err, datapages.ErrForbidden):
		http.Error(w, http.StatusText(http.StatusForbidden), http.StatusForbidden)
	case errors.Is(err, datapages.ErrNotFound):
		http.Error(w, http.StatusText(http.StatusNotFound), http.StatusNotFound)
	case errors.Is(err, datapages.ErrConflict):
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
	default:
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
	}
}

func (s *Server) handlePageCountGET(w http.ResponseWriter, r *http.Request) {

	// Mint the per-instance identifier for this page load.
	// The client echoes this value on action requests and on the SSE
	// stream connect via the Datapages-Instance header.
	instanceID, err := s.signStateInstanceID()
	if err != nil {
		s.httpErrIntern(w, r, nil, "minting state instance", err)
		return
	}
	w.Header().Set(stateInstanceIDHeader, instanceID)
	// The page carries an identifier that stands for one tab's state.
	// A cache that hands it to a second visitor hands over the state.
	w.Header().Set("Cache-Control", "no-store")

	p := app.PageCount{
		App: s.app,
		Base: app.Base[app.StateCounter]{
			App: s.app,
		},
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageCount.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/count/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageCount", err)
		return
	}
}

func (s *Server) handlePageCountGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	if _, live := s.lookupStateCounter(instanceID); !live && !s.stateHasCapacity() {
		w.Header().Set("Retry-After", "5")
		http.Error(w,
			http.StatusText(http.StatusServiceUnavailable),
			http.StatusServiceUnavailable)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	var slot *stateSlotStateCounter

	p := app.PageCount{
		App: s.app,
		Base: app.Base[app.StateCounter]{
			App: s.app,
		},
	}
	s.handleStreamRequest(w, r, evSubjPageCount(stateID),
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			slot = s.allocateStateCounter(instanceID)
			// A stream that gets no slot never opens: the event loop and the
			// close hook run only once this hook has returned nil,
			// which is why neither of them checks again.
			if slot == nil {
				return errStateAtCapacity
			}
			// The close hook is wired up only once this one has returned nil.
			// An open that ends any other way gives the instance back here,
			// since nothing else is left to do it.
			opened := false
			defer func() {
				if !opened {
					s.releaseStateCounter(instanceID, slot)
				}
			}()
			slot.mu.Lock()
			defer slot.mu.Unlock()
			if err := p.StreamOpen(r, streamID, slot.state); err != nil {
				return err
			}
			opened = true
			return nil
		},
		func(streamID datapages.StreamID) {
			s.releaseStateCounter(instanceID, slot)
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventPing app.EventPing
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvSubjPrefPing):
					eventPing = app.EventPing{}
					if err := json.Unmarshal(msg.Data, &eventPing); err != nil {
						s.LogErr("unmarshaling EventPing JSON", err)
						continue
					}
					slot.mu.Lock()
					if slot.dead {
						slot.mu.Unlock()
						continue
					}
					if err := p.OnPing(eventPing, dpsse.New(sse), slot.state); err != nil {
						s.LogErr("handling PageCount.OnPing", err)
					}
					slot.mu.Unlock()
				}
			}
		})
}

func (s *Server) handlePageCountPOSTBump(
	w http.ResponseWriter, r *http.Request,
) {
	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	slot, ok := s.lookupStateCounter(instanceID)
	if !ok {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	slot.mu.Lock()
	defer slot.mu.Unlock()
	if slot.dead {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}

	dispatchPing := dispatcherEventPing{s: s, ctx: r.Context()}
	p := app.PageCount{
		App: s.app,
		Base: app.Base[app.StateCounter]{
			App: s.app,
		},
	}
	err := p.POSTBump(r, slot.state, stateID, dispatchPing)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageCount.Bump", err)
		return
	}
}

func (s *Server) handlePageEmbedOnlyGET(w http.ResponseWriter, r *http.Request) {

	// Mint the per-instance identifier for this page load.
	// The client echoes this value on action requests and on the SSE
	// stream connect via the Datapages-Instance header.
	instanceID, err := s.signStateInstanceID()
	if err != nil {
		s.httpErrIntern(w, r, nil, "minting state instance", err)
		return
	}
	w.Header().Set(stateInstanceIDHeader, instanceID)
	// The page carries an identifier that stands for one tab's state.
	// A cache that hands it to a second visitor hands over the state.
	w.Header().Set("Cache-Control", "no-store")

	p := app.PageEmbedOnly{
		App: s.app,
		Base: app.Base[app.StateLabel]{
			App: s.app,
		},
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageEmbedOnly.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/embed-only/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageEmbedOnly", err)
		return
	}
}

func (s *Server) handlePageEmbedOnlyGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	if _, live := s.lookupStateLabel(instanceID); !live && !s.stateHasCapacity() {
		w.Header().Set("Retry-After", "5")
		http.Error(w,
			http.StatusText(http.StatusServiceUnavailable),
			http.StatusServiceUnavailable)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	var slot *stateSlotStateLabel

	p := app.PageEmbedOnly{
		App: s.app,
		Base: app.Base[app.StateLabel]{
			App: s.app,
		},
	}
	s.handleStreamRequest(w, r, evSubjPageEmbedOnly(stateID),
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			slot = s.allocateStateLabel(instanceID)
			// A stream that gets no slot never opens: the event loop and the
			// close hook run only once this hook has returned nil,
			// which is why neither of them checks again.
			if slot == nil {
				return errStateAtCapacity
			}
			// The close hook is wired up only once this one has returned nil.
			// An open that ends any other way gives the instance back here,
			// since nothing else is left to do it.
			opened := false
			defer func() {
				if !opened {
					s.releaseStateLabel(instanceID, slot)
				}
			}()
			slot.mu.Lock()
			defer slot.mu.Unlock()
			if err := p.StreamOpen(r, streamID, slot.state); err != nil {
				return err
			}
			opened = true
			return nil
		},
		func(streamID datapages.StreamID) {
			s.releaseStateLabel(instanceID, slot)
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventPing app.EventPing
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvSubjPrefPing):
					eventPing = app.EventPing{}
					if err := json.Unmarshal(msg.Data, &eventPing); err != nil {
						s.LogErr("unmarshaling EventPing JSON", err)
						continue
					}
					slot.mu.Lock()
					if slot.dead {
						slot.mu.Unlock()
						continue
					}
					if err := p.OnPing(eventPing, dpsse.New(sse), slot.state); err != nil {
						s.LogErr("handling PageEmbedOnly.OnPing", err)
					}
					slot.mu.Unlock()
				}
			}
		})
}

func (s *Server) handlePageIndexGET(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	p := app.PageIndex{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

func (s *Server) handlePageLabelGET(w http.ResponseWriter, r *http.Request) {

	// Mint the per-instance identifier for this page load.
	// The client echoes this value on action requests and on the SSE
	// stream connect via the Datapages-Instance header.
	instanceID, err := s.signStateInstanceID()
	if err != nil {
		s.httpErrIntern(w, r, nil, "minting state instance", err)
		return
	}
	w.Header().Set(stateInstanceIDHeader, instanceID)
	// The page carries an identifier that stands for one tab's state.
	// A cache that hands it to a second visitor hands over the state.
	w.Header().Set("Cache-Control", "no-store")

	p := app.PageLabel{
		App: s.app,
		Base: app.Base[app.StateLabel]{
			App: s.app,
		},
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageLabel.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/label/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageLabel", err)
		return
	}
}

func (s *Server) handlePageLabelGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	if _, live := s.lookupStateLabel(instanceID); !live && !s.stateHasCapacity() {
		w.Header().Set("Retry-After", "5")
		http.Error(w,
			http.StatusText(http.StatusServiceUnavailable),
			http.StatusServiceUnavailable)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	var slot *stateSlotStateLabel

	p := app.PageLabel{
		App: s.app,
		Base: app.Base[app.StateLabel]{
			App: s.app,
		},
	}
	s.handleStreamRequest(w, r, evSubjPageLabel(stateID),
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			slot = s.allocateStateLabel(instanceID)
			// A stream that gets no slot never opens: the event loop and the
			// close hook run only once this hook has returned nil,
			// which is why neither of them checks again.
			if slot == nil {
				return errStateAtCapacity
			}
			// The close hook is wired up only once this one has returned nil.
			// An open that ends any other way gives the instance back here,
			// since nothing else is left to do it.
			opened := false
			defer func() {
				if !opened {
					s.releaseStateLabel(instanceID, slot)
				}
			}()
			slot.mu.Lock()
			defer slot.mu.Unlock()
			if err := p.StreamOpen(r, streamID, slot.state); err != nil {
				return err
			}
			opened = true
			return nil
		},
		func(streamID datapages.StreamID) {
			s.releaseStateLabel(instanceID, slot)
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventPing app.EventPing
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvSubjPrefPing):
					eventPing = app.EventPing{}
					if err := json.Unmarshal(msg.Data, &eventPing); err != nil {
						s.LogErr("unmarshaling EventPing JSON", err)
						continue
					}
					slot.mu.Lock()
					if slot.dead {
						slot.mu.Unlock()
						continue
					}
					if err := p.OnPing(eventPing, dpsse.New(sse), slot.state); err != nil {
						s.LogErr("handling PageLabel.OnPing", err)
					}
					slot.mu.Unlock()
				}
			}
		})
}

func (s *Server) handlePageLabelPOSTSet(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.checkIsDSReq(w, r) {
		return
	}
	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	slot, ok := s.lookupStateLabel(instanceID)
	if !ok {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		Text string `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.httpErrBad(w, "reading signals", err)
		return
	}
	slot.mu.Lock()
	defer slot.mu.Unlock()
	if slot.dead {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}

	dispatchPing := dispatcherEventPing{s: s, ctx: r.Context()}
	p := app.PageLabel{
		App: s.app,
		Base: app.Base[app.StateLabel]{
			App: s.app,
		},
	}
	err := p.POSTSet(r, slot.state, stateID, signals, dispatchPing)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageLabel.Set", err)
		return
	}
}

func (s *Server) handlePageNestedGET(w http.ResponseWriter, r *http.Request) {

	// Mint the per-instance identifier for this page load.
	// The client echoes this value on action requests and on the SSE
	// stream connect via the Datapages-Instance header.
	instanceID, err := s.signStateInstanceID()
	if err != nil {
		s.httpErrIntern(w, r, nil, "minting state instance", err)
		return
	}
	w.Header().Set(stateInstanceIDHeader, instanceID)
	// The page carries an identifier that stands for one tab's state.
	// A cache that hands it to a second visitor hands over the state.
	w.Header().Set("Cache-Control", "no-store")

	p := app.PageNested{
		App: s.app,
		Mid: app.Mid[app.StateNested]{
			App: s.app,
			Base: app.Base[app.StateNested]{
				App: s.app,
			},
		},
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageNested.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/nested/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageNested", err)
		return
	}
}

func (s *Server) handlePageNestedGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	if _, live := s.lookupStateNested(instanceID); !live && !s.stateHasCapacity() {
		w.Header().Set("Retry-After", "5")
		http.Error(w,
			http.StatusText(http.StatusServiceUnavailable),
			http.StatusServiceUnavailable)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	var slot *stateSlotStateNested

	p := app.PageNested{
		App: s.app,
		Mid: app.Mid[app.StateNested]{
			App: s.app,
			Base: app.Base[app.StateNested]{
				App: s.app,
			},
		},
	}
	s.handleStreamRequest(w, r, evSubjPageNested(stateID),
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			slot = s.allocateStateNested(instanceID)
			// A stream that gets no slot never opens: the event loop and the
			// close hook run only once this hook has returned nil,
			// which is why neither of them checks again.
			if slot == nil {
				return errStateAtCapacity
			}
			// The close hook is wired up only once this one has returned nil.
			// An open that ends any other way gives the instance back here,
			// since nothing else is left to do it.
			opened := false
			defer func() {
				if !opened {
					s.releaseStateNested(instanceID, slot)
				}
			}()
			slot.mu.Lock()
			defer slot.mu.Unlock()
			if err := p.StreamOpen(r, streamID, slot.state); err != nil {
				return err
			}
			opened = true
			return nil
		},
		func(streamID datapages.StreamID) {
			s.releaseStateNested(instanceID, slot)
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventPing app.EventPing
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvSubjPrefPing):
					eventPing = app.EventPing{}
					if err := json.Unmarshal(msg.Data, &eventPing); err != nil {
						s.LogErr("unmarshaling EventPing JSON", err)
						continue
					}
					slot.mu.Lock()
					if slot.dead {
						slot.mu.Unlock()
						continue
					}
					if err := p.OnPing(eventPing, dpsse.New(sse), slot.state); err != nil {
						s.LogErr("handling PageNested.OnPing", err)
					}
					slot.mu.Unlock()
				}
			}
		})
}

func (s *Server) handlePageNestedPOSTBump(
	w http.ResponseWriter, r *http.Request,
) {
	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	slot, ok := s.lookupStateNested(instanceID)
	if !ok {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	slot.mu.Lock()
	defer slot.mu.Unlock()
	if slot.dead {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}

	dispatchPing := dispatcherEventPing{s: s, ctx: r.Context()}
	p := app.PageNested{
		App: s.app,
		Mid: app.Mid[app.StateNested]{
			App: s.app,
			Base: app.Base[app.StateNested]{
				App: s.app,
			},
		},
	}
	err := p.POSTBump(r, slot.state, stateID, dispatchPing)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageNested.Bump", err)
		return
	}
}

func (s *Server) handlePagePointerGET(w http.ResponseWriter, r *http.Request) {

	// Mint the per-instance identifier for this page load.
	// The client echoes this value on action requests and on the SSE
	// stream connect via the Datapages-Instance header.
	instanceID, err := s.signStateInstanceID()
	if err != nil {
		s.httpErrIntern(w, r, nil, "minting state instance", err)
		return
	}
	w.Header().Set(stateInstanceIDHeader, instanceID)
	// The page carries an identifier that stands for one tab's state.
	// A cache that hands it to a second visitor hands over the state.
	w.Header().Set("Cache-Control", "no-store")

	p := app.PagePointer{
		App: s.app,
		Base: &app.Base[app.StatePointer]{
			App: s.app,
		},
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PagePointer.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/pointer/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PagePointer", err)
		return
	}
}

func (s *Server) handlePagePointerGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	if _, live := s.lookupStatePointer(instanceID); !live && !s.stateHasCapacity() {
		w.Header().Set("Retry-After", "5")
		http.Error(w,
			http.StatusText(http.StatusServiceUnavailable),
			http.StatusServiceUnavailable)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	var slot *stateSlotStatePointer

	p := app.PagePointer{
		App: s.app,
		Base: &app.Base[app.StatePointer]{
			App: s.app,
		},
	}
	s.handleStreamRequest(w, r, evSubjPagePointer(stateID),
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			slot = s.allocateStatePointer(instanceID)
			// A stream that gets no slot never opens: the event loop and the
			// close hook run only once this hook has returned nil,
			// which is why neither of them checks again.
			if slot == nil {
				return errStateAtCapacity
			}
			// The close hook is wired up only once this one has returned nil.
			// An open that ends any other way gives the instance back here,
			// since nothing else is left to do it.
			opened := false
			defer func() {
				if !opened {
					s.releaseStatePointer(instanceID, slot)
				}
			}()
			slot.mu.Lock()
			defer slot.mu.Unlock()
			if err := p.StreamOpen(r, streamID, slot.state); err != nil {
				return err
			}
			opened = true
			return nil
		},
		func(streamID datapages.StreamID) {
			s.releaseStatePointer(instanceID, slot)
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventPing app.EventPing
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvSubjPrefPing):
					eventPing = app.EventPing{}
					if err := json.Unmarshal(msg.Data, &eventPing); err != nil {
						s.LogErr("unmarshaling EventPing JSON", err)
						continue
					}
					slot.mu.Lock()
					if slot.dead {
						slot.mu.Unlock()
						continue
					}
					if err := p.OnPing(eventPing, dpsse.New(sse), slot.state); err != nil {
						s.LogErr("handling PagePointer.OnPing", err)
					}
					slot.mu.Unlock()
				}
			}
		})
}

func (s *Server) handlePagePointerPOSTBump(
	w http.ResponseWriter, r *http.Request,
) {
	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	slot, ok := s.lookupStatePointer(instanceID)
	if !ok {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	slot.mu.Lock()
	defer slot.mu.Unlock()
	if slot.dead {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}

	dispatchPing := dispatcherEventPing{s: s, ctx: r.Context()}
	p := app.PagePointer{
		App: s.app,
		Base: &app.Base[app.StatePointer]{
			App: s.app,
		},
	}
	err := p.POSTBump(r, slot.state, stateID, dispatchPing)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PagePointer.Bump", err)
		return
	}
}

type dispatcherEventPing struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventPing) Dispatch(e app.EventPing) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventPing) DispatchCtx(
	ctx context.Context, e app.EventPing,
) error {
	if !subject.IsToken(string(e.SubjectStateID)) {
		return fmt.Errorf(
			"EventPing.SubjectStateID must be a non-empty subject token, received %q",
			e.SubjectStateID)
	}
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventPing JSON: %w", err)
	}
	subj := "ping." + string(e.SubjectStateID)
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, subj, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", subj, err)
	}
	return nil
}
