// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"errors"
	"fmt"
	"log/slog"
	"net/http"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/httpserve"
	dpsse "github.com/romshark/datapages/runtime/sse"

	"github.com/romshark/datapages/internal/acceptance/recovererror/app"
	"github.com/romshark/datapages/internal/acceptance/recovererror/app/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

const DefaultBodySizeLimit = httpserve.DefaultBodySizeLimit

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	return s.Core.WriteHTML(w, r, httpserve.HTMLDocument{
		Head:            head,
		Body:            body,
		WriteBodyAttrs:  writeBodyAttrs,
		WriteBodySuffix: writeBodySuffix,
	})
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics messaging.NoopMetrics
	app                  *app.App
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[app.App, datapages.DisableSessions, datapages.DisablePrometheus, Server](app, broker, opts...)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *app.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[datapages.DisableSessions],
) error {
	if sessionManager != nil {
		return errors.New("unexpected option WithSessionManager: package app declares no session type")
	}
	if cfg.Prometheus != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}

	assetsFS, err := httpserve.AssetsFileSystem(cfg, "", "")
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core, err = httpserve.NewCore(cfg, "")
	if err != nil {
		return err
	}
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = messaging.NoopMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.Logger())

	return nil
}

const (

// Public events:

)

func MessageBrokerStreamSubjects() []string {
	return []string{}
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /boom/{$}",
		s.handlePageBoomGET)
	s.Mux().HandleFunc(
		"GET /server-error/{$}",
		s.handlePageError500GET)
	s.Mux().HandleFunc(
		"GET /",
		s.handlePageIndexGET)
	s.Mux().HandleFunc(
		"POST /bad/{$}",
		s.handlePageIndexPOSTBad)
	s.Mux().HandleFunc(
		"POST /missing/{$}",
		s.handlePageIndexPOSTMissing)
	s.Mux().HandleFunc(
		"POST /plain/{$}",
		s.handlePageIndexPOSTPlain)
	s.Mux().HandleFunc(
		"POST /unrecoverable/{$}",
		s.handlePageIndexPOSTUnrecoverable)
}

// httpErrFinal writes the error response without rendering PageError500.
// The PageError500 handler uses it so it can't render itself.
func (s *Server) httpErrFinal(w http.ResponseWriter, msg string, err error) {
	s.LogErr(msg, err)
	httpserve.WriteErrStatus(w, err)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	if !httpserve.IsDatastarRequest(r) {
		// A page load gets the app's own 500 page, with the status that
		// says what happened. The page's own route serves 200;
		// this is the other way in.
		w.WriteHeader(http.StatusInternalServerError)
		s.handlePageError500GET(w, r)
		return
	}
	// The response of a Datastar request is an event stream. Once one is
	// open the status line is gone, which is what committed reports.
	committed := sse != nil
	if sse == nil {
		sse = datastar.NewSSE(w, r, datastar.WithCompression())
		committed = true
	}
	errRecover := s.app.RecoverError(err, dpsse.New(sse))
	if errRecover == nil {
		return // Feedback delivered gracefully.
	}
	// RecoverError failed — fall back to HTTP error response.
	s.Logger().Error("recovering error",
		slog.Any("orig.msg", msg),
		slog.Any("orig.err", err),
		slog.Any("err", errRecover))
	if committed {
		// http.Error would write a status the client already received,
		// and append its text to the event stream the client is reading.
		return
	}
	httpserve.WriteErrStatus(w, err)
}

func (s *Server) handlePageBoomGET(w http.ResponseWriter, r *http.Request) {
	p := app.PageBoom{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageBoom.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageBoom", err)
		return
	}
}

func (s *Server) handlePageError500GET(w http.ResponseWriter, r *http.Request) {
	p := app.PageError500{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrFinal(w, "handling PageError500.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageError500", err)
		return
	}
}

func (s *Server) handlePageIndexGET(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	p := app.PageIndex{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTBad(
	w http.ResponseWriter, r *http.Request,
) {
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTBad(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Bad", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTMissing(
	w http.ResponseWriter, r *http.Request,
) {
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTMissing(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Missing", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTPlain(
	w http.ResponseWriter, r *http.Request,
) {
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTPlain(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Plain", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTUnrecoverable(
	w http.ResponseWriter, r *http.Request,
) {
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTUnrecoverable(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Unrecoverable", err)
		return
	}
}
