// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"runtime/debug"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/httpserve"
	dpsse "github.com/romshark/datapages/runtime/sse"
	"github.com/romshark/datapages/runtime/stream"

	"github.com/romshark/datapages/internal/acceptance/recovererror/app"
	"github.com/romshark/datapages/internal/acceptance/recovererror/app/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

const DefaultBodySizeLimit = httpserve.DefaultBodySizeLimit

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	return s.Core.WriteHTML(w, r, httpserve.HTMLDocument{
		Head:            head,
		Body:            body,
		WriteBodyAttrs:  writeBodyAttrs,
		WriteBodySuffix: writeBodySuffix,
	})
}

func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request,
	subjects []string,
	onOpen func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
	) error,
	onClose func(streamID datapages.StreamID),
	fn func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
		ch <-chan messaging.Message,
	),
) {
	s.streams.Handle(w, r, "", "", subjects, onOpen, onClose, fn)
}

// recoverPanic turns a panicking handler into an error and hands it to the error path.
func (s *Server) recoverPanic(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, handler string,
) {
	v := recover()
	if v == nil {
		return
	}
	stack := debug.Stack()
	s.Logger().Error("recovered panic",
		slog.String("handler", handler),
		slog.Any("panic", v),
		slog.String("stack", string(stack)))
	s.httpErrIntern(w, r, sse, "panic in "+handler,
		datapages.PanicError{Value: v, Stack: stack})
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics messaging.NoopMetrics
	streams              *stream.Handler
	app                  *app.App
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[app.App, datapages.DisableSessions, datapages.DisablePrometheus, Server](
//		app, broker, opts...,
//	)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *app.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[datapages.DisableSessions],
) error {
	if sessionManager != nil {
		return errors.New("unexpected option WithSessionManager: package app declares no session type")
	}
	if cfg.Prometheus != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}

	assetsFS, err := httpserve.AssetsFileSystem(cfg, "", "")
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core, err = httpserve.NewCore(cfg, "")
	if err != nil {
		return err
	}
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = messaging.NoopMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}
	s.streams = stream.NewHandler(
		s.Core, messageBroker, s.messageBrokerMetrics,
		nil,
		nil,
		s.httpErrIntern,
	)

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.Logger())

	return nil
}

const (

	// Public events:

	EvSubjPinged = "pinged"
)

func MessageBrokerStreamSubjects() []string {
	return []string{
		EvSubjPinged,
	}
}

var evSubjPageStreamPanic = []string{
	EvSubjPinged,
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /boom/{$}",
		s.handlePageBoomGET)
	s.Mux().HandleFunc(
		"GET /server-error/{$}",
		s.handlePageError500GET)
	s.Mux().HandleFunc(
		"GET /",
		s.handlePageIndexGET)
	s.Mux().HandleFunc(
		"GET /panic-page/{$}",
		s.handlePagePanicGET)
	s.Mux().HandleFunc(
		"GET /render-panic/{$}",
		s.handlePageRenderPanicGET)
	s.Mux().HandleFunc(
		"GET /stream-panic/{$}",
		s.handlePageStreamPanicGET)
	s.Mux().HandleFunc(
		"GET /stream-panic/_$/{$}",
		s.handlePageStreamPanicGETStream)
	s.Mux().HandleFunc(
		"POST /bad/{$}",
		s.handlePageIndexPOSTBad)
	s.Mux().HandleFunc(
		"POST /missing/{$}",
		s.handlePageIndexPOSTMissing)
	s.Mux().HandleFunc(
		"POST /plain/{$}",
		s.handlePageIndexPOSTPlain)
	s.Mux().HandleFunc(
		"POST /unrecoverable/{$}",
		s.handlePageIndexPOSTUnrecoverable)
	s.Mux().HandleFunc(
		"POST /panic/{$}",
		s.handlePageIndexPOSTPanic)
}

// httpErrFinal writes the error response without rendering PageError500.
// The PageError500 handler uses it so it can't render itself.
func (s *Server) httpErrFinal(w http.ResponseWriter, msg string, err error) {
	s.LogErr(msg, err)
	if httpserve.ResponseBodyWritten(w) {
		// A status written now only appends its text to the body.
		return
	}
	httpserve.WriteErrStatus(w, err)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	if !httpserve.IsDatastarRequest(r) {
		if httpserve.ResponseBodyWritten(w) {
			// An error page after a half-written one sends two documents.
			return
		}
		// The page serves 200 on its own route. Reached from here it carries 500.
		w.WriteHeader(http.StatusInternalServerError)
		s.handlePageError500GET(w, r)
		return
	}
	// committed reports that the stream is open, hence no status is left to send.
	committed := sse != nil
	if sse == nil {
		sse = datastar.NewSSE(w, r, datastar.WithCompression())
		committed = true
	}
	errRecover := s.app.RecoverError(err, dpsse.New(sse))
	if errRecover == nil {
		return // Feedback delivered gracefully.
	}
	// RecoverError failed — fall back to HTTP error response.
	s.Logger().Error("recovering error",
		slog.Any("orig.msg", msg),
		slog.Any("orig.err", err),
		slog.Any("err", errRecover))
	if committed {
		// A status written now only appends its text to the stream.
		return
	}
	if httpserve.ResponseBodyWritten(w) {
		// A status written now only appends its text to the body.
		return
	}
	httpserve.WriteErrStatus(w, err)
}

func (s *Server) handlePageBoomGET(w http.ResponseWriter, r *http.Request) {
	p := app.PageBoom{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageBoom.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageBoom.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageBoom", err)
		return
	}
}

func (s *Server) handlePageError500GET(w http.ResponseWriter, r *http.Request) {
	p := app.PageError500{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageError500.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrFinal(w, "handling PageError500.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageError500", err)
		return
	}
}

func (s *Server) handlePageIndexGET(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	p := app.PageIndex{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageIndex.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTBad(
	w http.ResponseWriter, r *http.Request,
) {
	defer s.recoverPanic(w, r, nil, "PageIndex.Bad")
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTBad(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Bad", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTMissing(
	w http.ResponseWriter, r *http.Request,
) {
	defer s.recoverPanic(w, r, nil, "PageIndex.Missing")
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTMissing(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Missing", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTPlain(
	w http.ResponseWriter, r *http.Request,
) {
	defer s.recoverPanic(w, r, nil, "PageIndex.Plain")
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTPlain(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Plain", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTUnrecoverable(
	w http.ResponseWriter, r *http.Request,
) {
	defer s.recoverPanic(w, r, nil, "PageIndex.Unrecoverable")
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTUnrecoverable(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Unrecoverable", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTPanic(
	w http.ResponseWriter, r *http.Request,
) {
	defer s.recoverPanic(w, r, nil, "PageIndex.Panic")
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTPanic(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Panic", err)
		return
	}
}

func (s *Server) handlePagePanicGET(w http.ResponseWriter, r *http.Request) {
	p := app.PagePanic{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PagePanic.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PagePanic.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PagePanic", err)
		return
	}
}

func (s *Server) handlePageRenderPanicGET(w http.ResponseWriter, r *http.Request) {
	p := app.PageRenderPanic{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageRenderPanic.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageRenderPanic.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageRenderPanic", err)
		return
	}
}

func (s *Server) handlePageStreamPanicGET(w http.ResponseWriter, r *http.Request) {
	p := app.PageStreamPanic{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageStreamPanic.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageStreamPanic.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/stream-panic/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageStreamPanic", err)
		return
	}
}

func (s *Server) handlePageStreamPanicGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}

	p := app.PageStreamPanic{
		App: s.app,
	}
	s.handleStreamRequest(w, r, evSubjPageStreamPanic,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			return p.StreamOpen(r, streamID)
		},
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			defer s.recoverPanic(w, r, sse, "PageStreamPanic stream")
			var eventPinged app.EventPinged
			for msg := range ch {
				switch msg.Subject {
				case EvSubjPinged:
					eventPinged = app.EventPinged{}
					if err := json.Unmarshal(msg.Data, &eventPinged); err != nil {
						s.LogErr("unmarshaling EventPinged JSON", err)
						continue
					}
					if err := p.OnPinged(eventPinged, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageStreamPanic.OnPinged", err)
					}
				}
			}
		})
}
