// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"runtime/debug"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/actionexpr"
	"github.com/romshark/datapages/runtime/httpserve"
	dpsse "github.com/romshark/datapages/runtime/sse"
	"github.com/romshark/datapages/runtime/stream"

	dpapp "github.com/romshark/datapages/internal/acceptance/multiapp/app/admin"
	"github.com/romshark/datapages/internal/acceptance/multiapp/app/admin/datapagesgen/href"

	"github.com/romshark/datapages/internal/acceptance/multiapp/events"

	"github.com/romshark/datapages/runtime/prom"
	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

// brokerMetrics implements messaging.Metrics using the built-in Prometheus counters.
type brokerMetrics struct{}

func (m brokerMetrics) OnPublish(subject string) {
	prom.BrokerPublish(brokerSubjectKind(subject))
}

func (m brokerMetrics) OnDeliveryDropped() {
	prom.BrokerDeliveryDropped()
}

const DefaultBodySizeLimit = httpserve.DefaultBodySizeLimit

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	return s.Core.WriteHTML(w, r, httpserve.HTMLDocument{
		Head:            head,
		Body:            body,
		WriteBodyAttrs:  writeBodyAttrs,
		WriteBodySuffix: writeBodySuffix,
	})
}

func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request,
	subjects []string,
	onOpen func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
	) error,
	onClose func(streamID datapages.StreamID),
	fn func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
		ch <-chan messaging.Message,
	),
) {
	s.streams.Handle(w, r, "", "", subjects, onOpen, onClose, fn)
}

// recoverPanic turns a panicking handler into an error and hands it to the error path.
func (s *Server) recoverPanic(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, handler string,
) {
	v := recover()
	if v == nil {
		return
	}
	stack := debug.Stack()
	s.Logger().Error("recovered panic",
		slog.String("handler", handler),
		slog.Any("panic", v),
		slog.String("stack", string(stack)))
	s.httpErrIntern(w, r, sse, "panic in "+handler,
		datapages.PanicError{Value: v, Stack: stack})
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics brokerMetrics
	streams              *stream.Handler
	app                  *dpapp.App
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[dpapp.App, datapages.DisableSessions, datapages.EnablePrometheus, Server](
//		app, broker, opts...,
//	)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithLogSampling
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
//   - datapages.WithPrometheus (required)
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *dpapp.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[datapages.DisableSessions],
) error {
	if sessionManager != nil {
		return errors.New("unexpected option WithSessionManager: package dpapp declares no session type")
	}
	if cfg.Prometheus == nil {
		// This server is generated with datapages.EnablePrometheus,
		// hence the metrics it counts must be served.
		return errors.New("missing option WithPrometheus")
	}

	assetsFS, err := httpserve.AssetsFileSystem(cfg, "", "")
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core, err = httpserve.NewCore(cfg, "")
	if err != nil {
		return err
	}
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = brokerMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}
	s.streams = stream.NewHandler(
		s.Core, messageBroker, s.messageBrokerMetrics,
		nil,
		prom.StreamMetrics{},
		s.httpErrIntern,
	)

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.SampledLogger())
	actionexpr.SetLogger(s.SampledLogger())
	actionexpr.SetMetrics(prom.ActionMetrics{})

	return nil
}

const (

	// Public events:

	EvSubjReport       = "report"
	EvSubjAnnouncement = "announcement"
)

func MessageBrokerStreamSubjects() []string {
	return []string{
		EvSubjReport,
		EvSubjAnnouncement,
	}
}

var evSubjPageIndex = []string{
	EvSubjReport,
	EvSubjAnnouncement,
}

// brokerSubjectKind folds subjects that carry a value back into the event name.
// A metric labelled with the raw subject would carry one value per subject value.
func brokerSubjectKind(subject string) string {
	switch {
	case subject == EvSubjReport:
		return "report"
	case subject == EvSubjAnnouncement:
		return "announcement"
	default:
		return "unknown"
	}
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /",
		pageIndexHandlers{s}.GET)
	s.Mux().HandleFunc(
		"GET /_$/{$}",
		pageIndexHandlers{s}.GETStream)
	s.Mux().HandleFunc(
		"POST /announce/{$}",
		pageIndexHandlers{s}.POSTAnnounce)
	s.Mux().HandleFunc(
		"POST /report/{$}",
		pageIndexHandlers{s}.POSTReport)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	sse *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	if sse != nil {
		// The stream is open, hence no status is left to send.
		return
	}
	if httpserve.ResponseBodyWritten(w) {
		// A status written now only appends its text to the body.
		return
	}
	httpserve.WriteErrStatus(w, err)
}

type pageIndexHandlers struct{ *Server }

func (s pageIndexHandlers) GET(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	p := dpapp.PageIndex{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageIndex.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

func (s pageIndexHandlers) GETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}

	p := dpapp.PageIndex{
		App: s.app,
	}
	s.handleStreamRequest(w, r, evSubjPageIndex,
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			defer s.recoverPanic(w, r, sse, "PageIndex stream")
			var eventReport dpapp.EventReport
			var eventAnnouncement events.EventAnnouncement
			for msg := range ch {
				switch msg.Subject {
				case EvSubjReport:
					eventReport = dpapp.EventReport{}
					if err := json.Unmarshal(msg.Data, &eventReport); err != nil {
						s.LogErr("unmarshaling EventReport JSON", err)
						continue
					}
					if err := p.OnReport(eventReport, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageIndex.OnReport", err)
					}
				case EvSubjAnnouncement:
					eventAnnouncement = events.EventAnnouncement{}
					if err := json.Unmarshal(msg.Data, &eventAnnouncement); err != nil {
						s.LogErr("unmarshaling EventAnnouncement JSON", err)
						continue
					}
					if err := p.OnAnnouncement(eventAnnouncement, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageIndex.OnAnnouncement", err)
					}
				}
			}
		})
}

func (s pageIndexHandlers) POSTAnnounce(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	httpserve.LimitRequestBody(w, r, s.BodySizeLimit())
	var signals datapages.Signals[struct {
		Text string `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}

	dispatchAnnouncement := dispatcherEventAnnouncement{s: s.Server, ctx: r.Context()}
	defer s.recoverPanic(w, r, nil, "PageIndex.Announce")
	p := dpapp.PageIndex{
		App: s.app,
	}
	err := p.POSTAnnounce(r, signals, dispatchAnnouncement)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Announce", err)
		return
	}
}

func (s pageIndexHandlers) POSTReport(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	httpserve.LimitRequestBody(w, r, s.BodySizeLimit())
	var signals datapages.Signals[struct {
		N int `json:"n"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}

	dispatchReport := dispatcherEventReport{s: s.Server, ctx: r.Context()}
	defer s.recoverPanic(w, r, nil, "PageIndex.Report")
	p := dpapp.PageIndex{
		App: s.app,
	}
	err := p.POSTReport(r, signals, dispatchReport)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Report", err)
		return
	}
}

type dispatcherEventAnnouncement struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventAnnouncement) Dispatch(e events.EventAnnouncement) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventAnnouncement) DispatchCtx(
	ctx context.Context, e events.EventAnnouncement,
) error {
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventAnnouncement JSON: %w", err)
	}
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, EvSubjAnnouncement, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", EvSubjAnnouncement, err)
	}
	return nil
}

type dispatcherEventReport struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventReport) Dispatch(e dpapp.EventReport) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventReport) DispatchCtx(
	ctx context.Context, e dpapp.EventReport,
) error {
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventReport JSON: %w", err)
	}
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, EvSubjReport, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", EvSubjReport, err)
	}
	return nil
}
