package generator_test

import (
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/romshark/datapages/generator"
	"github.com/romshark/datapages/parser"
	"github.com/stretchr/testify/require"
)

func TestGenerateClassifieds(t *testing.T) {
	app, errs := parser.Parse(
		filepath.Join("..", "example", "classifieds", "app"),
	)
	require.Zero(t, errs.Len(), "unexpected parser errors: %s", errs.Error())
	require.NotNil(t, app, "parser returned nil model")

	tmpDir := t.TempDir()
	err := generator.Generate(tmpDir, "datapagesgen", app, 0o644, generator.Options{Prometheus: true})
	require.NoError(t, err)

	compareFile(t, "app_gen.go",
		filepath.Join(tmpDir, "app_gen.go"),
		filepath.Join("..", "example", "classifieds",
			"datapagesgen", "app_gen.go"))
	compareFile(t, "action/action_gen.go",
		filepath.Join(tmpDir, "action", "action_gen.go"),
		filepath.Join("..", "example", "classifieds",
			"datapagesgen", "action", "action_gen.go"))
	compareFile(t, "href/href_gen.go",
		filepath.Join(tmpDir, "href", "href_gen.go"),
		filepath.Join("..", "example", "classifieds",
			"datapagesgen", "href", "href_gen.go"))
}

func TestGenerateCmd(t *testing.T) {
	tests := map[string]struct {
		appImport  string
		genImport  string
		genPkgName string
	}{
		"default paths": {
			appImport:  "example.com/myapp/app",
			genImport:  "example.com/myapp/datapagesgen",
			genPkgName: "datapagesgen",
		},
		"custom gen package": {
			appImport:  "example.com/myapp/app",
			genImport:  "example.com/myapp/mygen",
			genPkgName: "mygen",
		},
	}
	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			tmpDir := t.TempDir()
			err := generator.GenerateCmd(
				tmpDir, tt.appImport, tt.genImport, tt.genPkgName, true, 0o644,
			)
			require.NoError(t, err)

			data, err := os.ReadFile(filepath.Join(tmpDir, "main.go"))
			require.NoError(t, err)

			src := string(data)
			require.True(t, strings.HasPrefix(src, "// Generated by"))
			require.Contains(t, src, "package main")
			require.Contains(t, src, tt.appImport)
			require.Contains(t, src, tt.genImport)
			require.Contains(t, src, tt.genPkgName+".NewServer")
		})
	}
}

func compareFile(t *testing.T, name, gotPath, wantPath string) {
	t.Helper()

	got, err := os.ReadFile(gotPath)
	require.NoError(t, err, "reading generated %s", name)

	want, err := os.ReadFile(wantPath)
	require.NoError(t, err, "reading reference %s", name)

	// Format both to normalize whitespace differences.
	gotFmt, err := format.Source(got)
	if err != nil {
		// If formatting fails, compare raw.
		gotFmt = got
	}
	wantFmt, err := format.Source(want)
	if err != nil {
		wantFmt = want
	}

	if string(gotFmt) != string(wantFmt) {
		t.Errorf("%s differs from reference.\nGenerated: %s\nReference: %s",
			name, gotPath, wantPath)
	}
}
