package generator

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// GenerateCmd generates a default cmd/server main.go at dstDir.
// appImportPath and genImportPath are the full Go import paths of the app
// and generated packages. genPkgName is the Go package name of the generated
// package (e.g. "datapagesgen").
func GenerateCmd(
	dstDir string,
	appImportPath, genImportPath, genPkgName string,
	perm os.FileMode,
) error {
	w := writerPool.Get().(*Writer)
	defer writerPool.Put(w)

	w.Reset()
	w.WriteCmd(appImportPath, genImportPath, genPkgName)
	var err error
	w.Buf, err = format.Source(w.Buf)
	if err != nil {
		return fmt.Errorf("formatting cmd/main.go: %w", err)
	}
	if err := os.MkdirAll(dstDir, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dstDir, err)
	}
	if err := os.WriteFile(
		filepath.Join(dstDir, "main.go"), w.Buf, perm,
	); err != nil {
		return fmt.Errorf("writing cmd/main.go: %w", err)
	}
	return nil
}

// WriteCmd generates a default server main.go and appends it to buffer.
func (w *Writer) WriteCmd(appImportPath, genImportPath, genPkgName string) {
	g := genPkgName // shorthand

	w.Line(0, "// Generated by github.com/romshark/datapages. DO NOT EDIT.")
	w.Line(0, "")
	w.Line(0, "package main")
	w.Line(0, "")
	w.Line(0, "import (")
	w.Line(1, `"context"`)
	w.Line(1, `"errors"`)
	w.Line(1, `"log/slog"`)
	w.Line(1, `"net"`)
	w.Line(1, `"net/http"`)
	w.Line(1, `"os"`)
	w.Line(1, `"os/signal"`)
	w.Line(0, "")
	w.Line(1, `csrfhmac "github.com/romshark/datapages/modules/csrf/hmac"`)
	w.Line(1, `"github.com/romshark/datapages/modules/msgbroker/natsjs"`)
	w.Line(1, `"github.com/romshark/datapages/modules/sessmanager/natskv"`)
	w.Line(1, `"github.com/romshark/datapages/modules/sesstokgen"`)
	w.Line(0, "")
	w.Linef(1, "%q", appImportPath)
	w.Linef(1, "%q", genImportPath)
	w.Line(0, "")
	w.Line(1, `"github.com/nats-io/nats.go"`)
	w.Line(0, ")")
	w.Line(0, "")

	// main
	w.Line(0, "func main() {")
	w.Line(1, `host := envOr("HOST", "localhost")`)
	w.Line(1, `port := envOr("PORT", "8080")`)
	w.Line(0, "")
	w.Line(1, "ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)")
	w.Line(1, "defer cancel()")
	w.Line(0, "")
	w.Linef(1, "var opts []%s.ServerOption", g)
	w.Line(1, "withAccessLogger(&opts)")
	w.Line(1, "withAuth(&opts)")
	w.Line(1, "withCSRFProtection(&opts)")
	w.Line(1, "initMetrics(&opts)")
	w.Line(0, "")
	w.Line(1, "messageBroker, sessionManager := connectNATS()")
	w.Line(0, "")
	w.Line(1, "// TODO: Initialize your app.")
	w.Line(1, "a := &app.App{}")
	w.Line(0, "")
	w.Linef(1, "s := %s.NewServer(a, messageBroker, sessionManager, opts...)", g)
	w.Line(1, "listenAndServe(ctx, s, net.JoinHostPort(host, port))")
	w.Line(0, "}")
	w.Line(0, "")

	// envOr
	w.Line(0, "func envOr(key, fallback string) string {")
	w.Line(1, `if v := os.Getenv(key); v != "" {`)
	w.Line(2, "return v")
	w.Line(1, "}")
	w.Line(1, "return fallback")
	w.Line(0, "}")
	w.Line(0, "")

	// withAccessLogger
	w.Linef(0, "func withAccessLogger(opts *[]%s.ServerOption) {", g)
	w.Line(1, "logger := slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{")
	w.Line(2, "Level: slog.LevelInfo,")
	w.Line(1, "}))")
	w.Linef(1, "*opts = append(*opts, %s.WithMiddleware(func(next http.Handler) http.Handler {", g)
	w.Line(2, "return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {")
	w.Line(3, `logger.Info("access",`)
	w.Line(4, `slog.String("method", r.Method),`)
	w.Line(4, `slog.String("path", r.URL.Path))`)
	w.Line(3, "next.ServeHTTP(w, r)")
	w.Line(2, "})")
	w.Line(1, "}))")
	w.Line(0, "}")
	w.Line(0, "")

	// withAuth
	w.Linef(0, "func withAuth(opts *[]%s.ServerOption) {", g)
	w.Linef(1, "*opts = append(*opts, %s.WithAuth(%s.AuthConfig{}))", g, g)
	w.Line(0, "}")
	w.Line(0, "")

	// withCSRFProtection
	w.Linef(0, "func withCSRFProtection(opts *[]%s.ServerOption) {", g)
	w.Line(1, `secret := os.Getenv("CSRF_SECRET")`)
	w.Line(1, "tm, err := csrfhmac.New([]byte(secret))")
	w.Line(1, "if err != nil {")
	w.Line(2, `slog.Error("initializing CSRF token manager", slog.Any("err", err))`)
	w.Line(2, "os.Exit(1)")
	w.Line(1, "}")
	w.Linef(1, "*opts = append(*opts, %s.WithCSRFProtection(%s.CSRFConfig{", g, g)
	w.Line(2, "TokenManager:   tm,")
	w.Line(2, `DevBypassToken: os.Getenv("CSRF_DEV_BYPASS"),`)
	w.Line(1, "}))")
	w.Line(0, "}")
	w.Line(0, "")

	// connectNATS
	w.Line(0, "func connectNATS() (")
	w.Line(1, "*natsjs.MessageBroker,")
	w.Line(1, "*natskv.SessionManager[app.Session],")
	w.Line(0, ") {")
	w.Line(1, `u := os.Getenv("NATS_URL")`)
	w.Line(1, `if u == "" {`)
	w.Line(2, `slog.Error("NATS_URL not set")`)
	w.Line(2, "os.Exit(2)")
	w.Line(1, "}")
	w.Line(0, "")
	w.Line(1, `sessionEncryptionKey := os.Getenv("SESSION_ENCRYPTION_KEY")`)
	w.Line(1, `if sessionEncryptionKey == "" {`)
	w.Line(2, `slog.Error("SESSION_ENCRYPTION_KEY not set")`)
	w.Line(2, "os.Exit(2)")
	w.Line(1, "}")
	w.Line(0, "")
	w.Line(1, "conn, err := nats.Connect(u)")
	w.Line(1, "if err != nil {")
	w.Line(2, `slog.Error("opening NATS connection", slog.Any("err", err))`)
	w.Line(2, "os.Exit(1)")
	w.Line(1, "}")
	w.Line(0, "")
	w.Line(1, "sessionManager, err := natskv.New[app.Session](")
	w.Line(2, "conn,")
	w.Line(2, "sesstokgen.Generator{Length: sesstokgen.DefaultLength},")
	w.Line(2, "natskv.Config{EncryptionKey: []byte(sessionEncryptionKey)},")
	w.Line(1, ")")
	w.Line(1, "if err != nil {")
	w.Line(2, `slog.Error("initializing session manager", slog.Any("err", err))`)
	w.Line(2, "os.Exit(1)")
	w.Line(1, "}")
	w.Line(0, "")
	w.Line(1, "messageBroker, err := natsjs.New(conn, natsjs.Config{")
	w.Line(2, "StreamConfig: &nats.StreamConfig{")
	w.Line(3, `Name:    "DATAPAGES",`)
	w.Line(3, "Storage: nats.MemoryStorage,")
	w.Line(2, "},")
	w.Line(1, "})")
	w.Line(1, "if err != nil {")
	w.Line(2, `slog.Error("initializing message broker", slog.Any("err", err))`)
	w.Line(2, "os.Exit(1)")
	w.Line(1, "}")
	w.Line(0, "")
	w.Line(1, "return messageBroker, sessionManager")
	w.Line(0, "}")
	w.Line(0, "")

	// initMetrics
	w.Linef(0, "func initMetrics(opts *[]%s.ServerOption) {", g)
	w.Line(1, `host := envOr("HOST_METRICS", "localhost")`)
	w.Line(1, `port := envOr("PORT_METRICS", "9090")`)
	w.Linef(1, "*opts = append(*opts, %s.WithPrometheus(%s.PrometheusConfig{", g, g)
	w.Line(2, "Host: net.JoinHostPort(host, port),")
	w.Line(1, "}))")
	w.Line(0, "}")
	w.Line(0, "")

	// listenAndServe
	w.Linef(0, "func listenAndServe(ctx context.Context, s *%s.Server, host string) {", g)
	w.Line(1, `pathCert := os.Getenv("PATH_TLS_CERT")`)
	w.Line(1, `pathKey := os.Getenv("PATH_TLS_KEY")`)
	w.Line(0, "")
	w.Line(1, "var err error")
	w.Line(1, `if pathCert == "" && pathKey == "" {`)
	w.Line(2, "err = s.ListenAndServe(ctx, host)")
	w.Line(1, "} else {")
	w.Line(2, "err = s.ListenAndServeTLS(ctx, host, pathCert, pathKey)")
	w.Line(1, "}")
	w.Line(1, "if err != nil && !errors.Is(err, http.ErrServerClosed) {")
	w.Line(2, `slog.Error("listening", slog.Any("err", err))`)
	w.Line(1, "}")
	w.Line(0, "}")
}
