package generator

import (
	_ "embed"
	"strings"

	"github.com/romshark/datapages/parser/model"
)

//go:embed app_static.go.txt
var appStaticContent string

// WriteApp generates code for the generated root package and appends it to buffer.
// pkgName is the Go package name (e.g. "datapagesgen").
func (w *Writer) WriteApp(pkgName string, m *model.App) {
	appPkg := appPkgName(m.PkgPath)
	w.buildEventMap(m.Events)

	w.writeAppHeader(pkgName, m.PkgPath, needsJSON(m))
	w.Raw(appStaticContent)
	w.writeAppCheckCSRF(appPkg)
	w.writeAppWriteHTML(m, appPkg)
	w.writeAppHandleStreamRequest(appPkg)
	w.writeAppServerStruct(appPkg)
	w.writeAppNewServer(appPkg)
	w.writeEventSubjectConsts(m.Events)
	w.writeMessageBrokerStreamSubjects(m.Events)
	w.writeEvSubjPageFuncs(m.Pages)
	w.writeAppAuth(appPkg)
	w.writeBrokerSubjectKind(m.Events)
	w.writeSetupHandlers(m)
	w.writeAppErrHelpers(m, appPkg)

	if m.PageError404 != nil {
		w.writeRender404(m, appPkg)
	}

	// App-level action handlers.
	for _, h := range m.Actions {
		w.writeAppActionHandler(h, m, appPkg)
	}

	// Per-page handlers.
	for _, p := range m.Pages {
		if p.GET != nil {
			w.writePageGETHandler(p, m, appPkg)
		}
		if pageHasStream(p) {
			w.writePageGETStreamHandler(p, m, appPkg)
			if pageHasAnonStream(p, w.eventMap) {
				w.writePageGETStreamAnonHandler(p, appPkg)
			}
		}
		for _, h := range p.Actions {
			w.writePageActionHandler(p, h, m, appPkg)
		}
	}
}

func needsJSON(m *model.App) bool {
	for _, h := range m.Actions {
		if h.InputDispatch != nil {
			return true
		}
	}
	for _, p := range m.Pages {
		for _, h := range p.Actions {
			if h.InputDispatch != nil {
				return true
			}
		}
	}
	return false
}

func (w *Writer) writeAppHeader(pkgName string, appPkgPath string, jsonImport bool) {
	w.Line(0, "// Generated by github.com/romshark/datapages. DO NOT EDIT.")
	w.Line(0, "")
	w.Linef(0, "package %s", pkgName)
	w.Line(0, "")
	w.Line(0, "import (")
	w.Line(1, `"bufio"`)
	w.Line(1, `"context"`)
	if jsonImport {
		w.Line(1, `"encoding/json"`)
	}
	w.Line(1, `"errors"`)
	w.Line(1, `"fmt"`)
	w.Line(1, `"io"`)
	w.Line(1, `"log/slog"`)
	w.Line(1, `"net"`)
	w.Line(1, `"net/http"`)
	w.Line(1, `"os"`)
	w.Line(1, `"slices"`)
	w.Line(1, `"strconv"`)
	w.Line(1, `"strings"`)
	w.Line(1, `"sync"`)
	w.Line(1, `"time"`)
	w.Line(0, "")
	w.Line(1, `"github.com/a-h/templ"`)
	w.Line(1, `"github.com/romshark/datapages/modules/csrf"`)
	w.Line(1, `"github.com/romshark/datapages/modules/msgbroker"`)
	w.Line(1, `"github.com/romshark/datapages/modules/sessmanager"`)
	w.Line(1, `"github.com/romshark/datapages/modules/sesstokgen"`)
	w.Line(1, `"golang.org/x/sync/errgroup"`)
	w.Line(0, "")
	w.Byte('\t')
	w.writeQuoted(appPkgPath)
	w.Byte('\n')
	w.Line(0, "")
	w.Line(1, `"github.com/prometheus/client_golang/prometheus"`)
	w.Line(1, `"github.com/prometheus/client_golang/prometheus/promhttp"`)
	w.Line(1, `"github.com/starfederation/datastar-go/datastar"`)
	w.Line(0, ")")
}

func (w *Writer) writeAppCheckCSRF(appPkg string) {
	w.Raw(`
func (s *Server) checkCSRF(
	w http.ResponseWriter, r *http.Request, sess `)
	w.Raw(appPkg)
	w.Raw(`.Session,
) (ok bool) {
	if sess.UserID == "" ||
		r.Method == http.MethodGet ||
		r.Method == http.MethodOptions ||
		r.Method == http.MethodHead ||
		s.csrfConf == nil {
		return true
	}
	t := r.Header.Get("X-CSRF-Token")
	if t == "" {
		http.Error(
			w,
			http.StatusText(http.StatusForbidden),
			http.StatusForbidden,
		)
		return false
	}
	if s.csrfConf.DevBypassToken != "" &&
		t == s.csrfConf.DevBypassToken {
		return true
	}
	if !s.csrfConf.TokenManager.ValidateToken(sess.UserID, sess.IssuedAt.Unix(), t) {
		http.Error(
			w,
			http.StatusText(http.StatusForbidden),
			http.StatusForbidden,
		)
		return false
	}
	return true
}
`)
}

func (w *Writer) writeAppWriteHTML(m *model.App, appPkg string) {
	w.Raw(`
func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	sess `)
	w.Raw(appPkg)
	w.Raw(`.Session,
	headGeneric, head, body templ.Component,
	writeBodyAttrs func(w http.ResponseWriter),
) error {
	_, err := io.WriteString(w, ` + "`" + `<!DOCTYPE html><html><head><meta charset="UTF-8"/>
		<script type="module" src="/static/ds.min.js"></script>` + "`" + `)
	if err != nil {
		return err
	}
`)

	if m.GlobalHeadGenerator != nil {
		w.Raw(`	if headGeneric != nil {
		if err := headGeneric.Render(r.Context(), w); err != nil {
			return err
		}
	}
`)
	}

	w.Raw(`	if head != nil {
		if err := head.Render(r.Context(), w); err != nil {
			return err
		}
	}
	if s.csrfConf != nil && sess.UserID != "" {
		csrfToken := s.csrfConf.TokenManager.GenerateToken(
			sess.UserID, sess.IssuedAt.Unix(),
		)
		if csrfToken != "" {
			// Write the fetch X-CSRF-Token header injector.
			if _, err := io.WriteString(w, ` + "`" + `
	<script type="module">
		const o = globalThis.fetch.bind(globalThis)
		globalThis.fetch=(i,init={}) => {
			const isReq=i instanceof Request
			const r=isReq ? i:new Request(i,init)
			if (r.headers.get("Datastar-Request")!=="true" ||
				r.method=="GET"||r.method=="HEAD"||r.method=="OPTIONS"
			) return isReq ? o(r,init):o(r)
			const h=new Headers(r.headers)
			h.set("X-CSRF-Token",'` + "`" + `); err != nil {
				return err
			}
			if _, err := io.WriteString(w, csrfToken); err != nil {
				return err
			}
			if _, err := io.WriteString(w, ` + "`" + `')
			return o(new Request(r,{...init,headers:h}))
		}
	</script>` + "`" + `); err != nil {
				return err
			}
		} else {
			s.logger.Warn("generated empty CSRF token",
				slog.String("user-id", sess.UserID),
				slog.Time("issued-at", sess.IssuedAt))
		}
	}
	if _, err := io.WriteString(w, "</head><body "); err != nil {
		return err
	}
	if writeBodyAttrs != nil {
		writeBodyAttrs(w)
	}
	if _, err := io.WriteString(w, ">"); err != nil {
		return err
	}
	if err := body.Render(r.Context(), w); err != nil {
		return err
	}
	_, err = io.WriteString(w, "</body></html>")
	return err
}
`)
}

func (w *Writer) writeAppHandleStreamRequest(appPkg string) {
	w.Raw(`
func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request, sessKey string, sess `)
	w.Raw(appPkg)
	w.Raw(`.Session,
	subjects []string,
	fn func(
		sse *datastar.ServerSentEventGenerator,
		ch <-chan msgbroker.Message,
	),
) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	sse := datastar.NewSSE(w, r, datastar.WithCompression())
	mSSEConnections.Inc()
	defer mSSEConnections.Dec()
	start := time.Now()

	ctx := r.Context()
	sub, err := s.messageBroker.Subscribe(ctx, s.messageBrokerMetrics, subjects...)
	if err != nil {
		s.httpErrIntern(w, r, sse, "subscribing to message broker", err)
		return
	}

	subC := sub.C()
	sessionClosed := make(chan struct{})

	if sess.UserID != "" {
		ctx, cancel := context.WithCancel(ctx)
		defer cancel()
		if err := s.sessionManager.NotifyClosed(ctx, sessKey, func() {
			close(sessionClosed)
		}); err != nil {
			s.httpErrIntern(w, r, sse, "setting up session closure watcher", err)
			return
		}
	}

	go func() {
		// Close the subscription when the request is canceled or the session is closed.
		select {
		case <-sessionClosed:
			mSSEDisconnects.WithLabelValues("close").Inc()
		case <-r.Context().Done():
			mSSEDisconnects.WithLabelValues("client").Inc()
		case <-s.shutdownCh:
			mSSEDisconnects.WithLabelValues("shutdown").Inc()
		}
		mSSEConnectionDuration.Observe(time.Since(start).Seconds())
		sub.Close()
	}()

	fn(sse, subC)
}
`)
}

func (w *Writer) writeAppServerStruct(appPkg string) {
	w.Raw(`
type Server struct {
	shutdownCh           chan struct{} // Closed when shutting down.
	shutdownOnce         sync.Once
	runCancel            context.CancelFunc
	httpServer           *http.Server
	messageBroker        msgbroker.MessageBroker
	messageBrokerMetrics brokerMetrics
	app                  *`)
	w.Raw(appPkg)
	w.Raw(`.App
	mux                  *http.ServeMux
	logger               *slog.Logger
	middleware           []func(http.Handler) http.Handler
	staticURLPath        string
	staticFS             http.FileSystem
	enabledTLS           bool

	metricsServer         *http.Server
	authConf              *AuthConfig
	sessionTokenGenerator sessmanager.TokenGenerator
	sessionManager        sessmanager.SessionManager[`)
	w.Raw(appPkg)
	w.Raw(`.Session]
	csrfConf              *CSRFConfig
}
`)
}

func (w *Writer) writeAppNewServer(appPkg string) {
	w.Raw(`
// NewServer creates a new server instance.
// Supported options:
//
//   - WithMiddleware
//   - WithHTTPServer
//   - WithStaticFS
//   - WithCSRFProtection
//   - WithPrometheus
func NewServer(
	app *`)
	w.Raw(appPkg)
	w.Raw(`.App,
	messageBroker msgbroker.MessageBroker,
	sessionManager sessmanager.SessionManager[`)
	w.Raw(appPkg)
	w.Raw(`.Session],
	opts ...ServerOption,
) *Server {
	s := &Server{
		shutdownCh: make(chan struct{}),
		httpServer: &http.Server{
			// Time to read request headers + body
			ReadTimeout: DefaultHTTPReadTimeout,
			// Time to read just headers (helps prevent Slowloris attacks)
			ReadHeaderTimeout: DefaultHTTPReadHeaderTimeout,
			// Time to write response
			WriteTimeout: DefaultHTTPWriteTimeout,
			// Time to wait for next request when using keep-alive
			IdleTimeout:    DefaultHTTPIdleTimeout,
			MaxHeaderBytes: DefaultHTTPMaxHeaderBytes,
		},
		app:                  app,
		mux:                  http.NewServeMux(),
		middleware:           []func(http.Handler) http.Handler{},
		messageBroker:        messageBroker,
		messageBrokerMetrics: brokerMetrics{},
		sessionManager:       sessionManager,
	}

	// Apply options
	for _, opt := range opts {
		if err := opt(s); err != nil {
			panic(fmt.Errorf("applying server option: %w", err))
		}
	}

	// Reverse handlers such that they're invoked in the order of definition.
	slices.Reverse(s.middleware)

	if s.metricsServer == nil {
		// package app is using prometheus metrics, hence WithPrometheus is required.
		panic("missing option WithPrometheus")
	}

	if s.sessionManager == nil {
		panic("missing SessionManager")
	}
	if s.authConf == nil {
		s.authConf = &AuthConfig{
			TokenCookie: AuthSessionConfigTokenCookie{
				Name: DefaultAuthSessionCookieName,
			},
		}
	}
	if s.sessionTokenGenerator == nil {
		s.sessionTokenGenerator = sesstokgen.Generator{
			Length: sesstokgen.DefaultLength,
		}
	}

	// Use defaults if not set.
	if s.logger == nil {
		opt := &slog.HandlerOptions{
			Level: slog.LevelInfo,
		}
		if IsDevMode() {
			opt.Level = slog.LevelDebug
		}
		s.logger = slog.New(slog.NewJSONHandler(os.Stderr, opt))
	}
	s.httpServer.Handler = s
	if s.httpServer.ErrorLog == nil {
		s.httpServer.ErrorLog = slog.NewLogLogger(
			slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{}),
			slog.LevelInfo,
		)
	}
	if s.messageBroker == nil {
		panic("missing message broker")
	}
	if si, ok := s.messageBroker.(msgbroker.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			panic(fmt.Sprintf("initializing message broker streams: %v", err))
		}
	}
	if s.csrfConf == nil {
		panic("missing option WithCSRFProtection")
	} else if s.csrfConf != nil && s.csrfConf.TokenManager == nil {
		panic("CSRFConfig.TokenManager is nil")
	}

	if s.metricsServer != nil {
		s.middleware = append(s.middleware, s.metricsMiddleware)
	}

	setupHandlers(s)
	if s.staticFS != nil {
		h := http.StripPrefix("/static/", http.FileServer(s.staticFS))
		if IsDevMode() {
			h = devNoCache(h)
		}
		s.mux.Handle("GET /static/", h)
	}

	return s
}
`)
}

func (w *Writer) writeEventSubjectConsts(events []*model.Event) {
	// EvSubj* constants (subscription subjects with wildcards for per-user events).
	w.Line(0, "")
	w.Line(0, "const (")

	// Private events first.
	for _, e := range events {
		if e.HasTargetUserIDs {
			w.Byte('\t')
			w.Raw(evSubjConst(e))
			w.Raw(" = ")
			w.writeQuoted(evSubjValue(e))
			w.Byte('\n')
		}
	}

	w.Line(0, "")
	w.Line(1, "// Public events:")
	w.Line(0, "")

	for _, e := range events {
		if !e.HasTargetUserIDs {
			w.Byte('\t')
			w.Raw(evSubjConst(e))
			w.Raw(" = ")
			w.writeQuoted(evSubjValue(e))
			w.Byte('\n')
		}
	}

	w.Line(0, ")")

	// EvSubjPref* constants (prefix for publishing per-user events).
	hasPrivate := false
	for _, e := range events {
		if e.HasTargetUserIDs {
			hasPrivate = true
			break
		}
	}
	if hasPrivate {
		w.Line(0, "")
		w.Line(0, "const (")
		for _, e := range events {
			if e.HasTargetUserIDs {
				w.Byte('\t')
				w.Raw(evSubjPrefConst(e))
				w.Raw(" = ")
				w.writeQuoted(evSubjPrefValue(e))
				w.Byte('\n')
			}
		}
		w.Line(0, ")")
	}
}

func (w *Writer) writeMessageBrokerStreamSubjects(events []*model.Event) {
	w.Line(0, "")
	w.Line(0, "func MessageBrokerStreamSubjects() []string {")
	w.Line(1, "return []string{")
	for _, e := range events {
		w.Raw("\t\t")
		w.Raw(evSubjConst(e))
		w.Raw(",\n")
	}
	w.Line(1, "}")
	w.Line(0, "}")
}

func (w *Writer) writeEvSubjPageFuncs(pages []*model.Page) {
	for _, p := range pages {
		if !pageHasStream(p) {
			continue
		}

		// Determine which events this page handles.
		hasPublic := false
		hasPrivate := false
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil {
				continue
			}
			if ev.HasTargetUserIDs {
				hasPrivate = true
			} else {
				hasPublic = true
			}
		}

		name := "evSubj" + p.TypeName

		if hasPrivate && !hasPublic {
			// All events are per-user, just take userID.
			w.Line(0, "")
			w.Raw("func ")
			w.Raw(name)
			w.Raw("(userID string) []string {\n")
			w.Line(1, "return []string{")
			for _, eh := range p.EventHandlers {
				ev := w.eventMap[eh.EventTypeName]
				if ev == nil {
					continue
				}
				w.Raw("\t\t")
				w.Raw(evSubjPrefConst(ev))
				w.Raw(" + userID,\n")
			}
			w.Line(1, "}")
			w.Line(0, "}")
			continue
		}

		if hasPublic && !hasPrivate {
			// All events are public. No userID needed.
			w.Line(0, "")
			w.Raw("func ")
			w.Raw(name)
			w.Raw("() []string {\n")
			w.Line(1, "return []string{")
			for _, eh := range p.EventHandlers {
				ev := w.eventMap[eh.EventTypeName]
				if ev == nil {
					continue
				}
				w.Raw("\t\t")
				w.Raw(evSubjConst(ev))
				w.Raw(",\n")
			}
			w.Line(1, "}")
			w.Line(0, "}")
			continue
		}

		// Mixed: public + private. Need conditional.
		w.Line(0, "")
		w.Raw("func ")
		w.Raw(name)
		w.Raw("(userID string) []string {\n")
		w.Line(1, "if userID == \"\" {")
		w.Line(2, "return []string{")
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || ev.HasTargetUserIDs {
				continue
			}
			w.Raw("\t\t\t")
			w.Raw(evSubjConst(ev))
			w.Raw(",\n")
		}
		w.Line(2, "}")
		w.Line(1, "}")
		w.Line(1, "return []string{")

		// Public first, then private.
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || ev.HasTargetUserIDs {
				continue
			}
			w.Raw("\t\t")
			w.Raw(evSubjConst(ev))
			w.Raw(",\n")
		}
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || !ev.HasTargetUserIDs {
				continue
			}
			w.Raw("\t\t")
			w.Raw(evSubjPrefConst(ev))
			w.Raw(" + userID,\n")
		}

		w.Line(1, "}")
		w.Line(0, "}")
	}
}

func (w *Writer) writeAppAuth(appPkg string) {
	w.Raw(`
// --- Auth ---

const DefaultAuthSessionCookieName = "sessiontoken"

type AuthConfig struct {
	// SessionTokenGenerator is optional; defaults to sesstokgen.Generator
	SessionTokenGenerator sessmanager.TokenGenerator

	// TokenCookie is optional; defaults to DefaultAuthSessionCookieName
	TokenCookie AuthSessionConfigTokenCookie

	// DisableHTTPOnly is optional; By default, httponly is enabled.
	DisableHTTPOnly bool
}

type AuthSessionConfigTokenCookie struct {
	// Name is optional; Default is DefaultAuthSessionCookieName
	Name string
	// Domain is optional; Not set by default.
	Domain string
}

// WithAuth sets session-based authentication configuration.
func WithAuth(o AuthConfig) ServerOption {
	return func(s *Server) error {
		if o.TokenCookie.Name == "" {
			o.TokenCookie.Name = DefaultAuthSessionCookieName
		}
		s.authConf = &o
		s.sessionTokenGenerator = o.SessionTokenGenerator
		return nil
	}
}

func (s *Server) setSessionCookie(w http.ResponseWriter, value string) {
	cookie := http.Cookie{
		Name:     s.authConf.TokenCookie.Name,
		Value:    value,
		Path:     "/",
		Domain:   s.authConf.TokenCookie.Domain,
		HttpOnly: !s.authConf.DisableHTTPOnly,
		Secure:   s.enabledTLS,
		SameSite: http.SameSiteLaxMode,
	}
	if value == "" {
		cookie.MaxAge = -1
		cookie.Expires = time.Unix(0, 0)
	}
	http.SetCookie(w, &cookie)
}

func (s *Server) createSession(
	w http.ResponseWriter, r *http.Request, session `)
	w.Raw(appPkg)
	w.Raw(`.Session,
) error {
	token, err := s.sessionManager.CreateSession(r.Context(), session.UserID, session)
	if err != nil {
		mSessionCreations.WithLabelValues("error").Inc()
		return err
	}
	mSessionCreations.WithLabelValues("success").Inc()
	s.setSessionCookie(w, token)
	return nil
}

func (s *Server) closeSession(
	w http.ResponseWriter, r *http.Request,
	token string,
) error {
	if err := s.sessionManager.CloseSession(r.Context(), token); err != nil {
		mSessionClosures.WithLabelValues("error").Inc()
		return err
	}
	mSessionClosures.WithLabelValues("success").Inc()
	s.setSessionCookie(w, "")
	return nil
}

// authSess reads the session token from r and checks CSRF when necessary.
// If onClose != nil it will be closed once the session is closed.
func (s *Server) auth(
	w http.ResponseWriter, r *http.Request,
) (sess `)
	w.Raw(appPkg)
	w.Raw(`.Session, token string, ok bool) {
	c, err := r.Cookie(s.authConf.TokenCookie.Name)
	if err != nil {
		if errors.Is(err, http.ErrNoCookie) {
			mSessionReads.WithLabelValues("none").Inc()
			return sess, "", true
		}
		return sess, "", false
	}

	sess, token, userID, ok, err := s.sessionManager.ReadSessionFromCookie(c)
	if err != nil {
		// Transient backend failure; keep the cookie, fail the request.
		mSessionReads.WithLabelValues("error").Inc()
		http.Error(w, "Service Unavailable", http.StatusServiceUnavailable)
		return `)
	w.Raw(appPkg)
	w.Raw(`.Session{}, "", false
	}
	if !ok {
		// Cookie is stale or malformed; clear it and continue as unauthenticated.
		mSessionReads.WithLabelValues("stale").Inc()
		s.setSessionCookie(w, "")
		return `)
	w.Raw(appPkg)
	w.Raw(`.Session{}, "", true
	}
	sess.UserID = userID

	mSessionReads.WithLabelValues("valid").Inc()

	if !s.checkCSRF(w, r, sess) {
		return sess, token, false
	}

	return sess, token, true
}
`)
}

func (w *Writer) writeBrokerSubjectKind(events []*model.Event) {
	w.Raw(`
// brokerSubjectKind collapses high-cardinality subjects (per-user) into stable kinds.
func brokerSubjectKind(subject string) string {
	switch {
`)
	for _, e := range events {
		if e.HasTargetUserIDs {
			w.Raw("\tcase strings.HasPrefix(subject, ")
			w.Raw(evSubjPrefConst(e))
			w.Raw("):\n")
		} else {
			w.Raw("\tcase subject == ")
			w.Raw(evSubjConst(e))
			w.Raw(":\n")
		}
		w.Raw("\t\treturn ")
		w.writeQuoted(e.Subject)
		w.Byte('\n')
	}
	w.Line(1, "default:")
	w.Line(2, `return "unknown"`)
	w.Line(1, "}")
	w.Line(0, "}")
}

func (w *Writer) writeSetupHandlers(m *model.App) {
	w.Line(0, "")
	w.Line(0, "func setupHandlers(s *Server) {")
	w.Line(1, "// Pages")

	for _, p := range m.Pages {
		if p.GET == nil {
			continue
		}

		routeForHandler := routeWithTrailingSlash(p.Route)

		if p.PageSpecialization == model.PageTypeIndex {
			// Index page: GET /
			w.Line(1, "s.mux.HandleFunc(")
			w.Line(2, "\"GET /\",")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw("GET)\n")
		} else {
			w.Line(1, "s.mux.HandleFunc(")
			w.Raw("\t\t\"GET ")
			w.Raw(routeForHandler)
			w.Raw("{$}\",\n")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw("GET)\n")
		}

		// Stream endpoint.
		if pageHasStream(p) {
			streamPath := routeStreamPath(p.Route)

			w.Line(1, "s.mux.HandleFunc(")
			w.Raw("\t\t\"GET ")
			w.Raw(streamPath)
			w.Raw("{$}\",\n")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw("GETStream)\n")

			if pageHasAnonStream(p, w.eventMap) {
				w.Line(1, "s.mux.HandleFunc(")
				w.Raw("\t\t\"GET ")
				w.Raw(streamPath)
				w.Raw("anon/{$}\",\n")
				w.Raw("\t\ts.handle")
				w.Raw(p.TypeName)
				w.Raw("GETStreamAnon)\n")
			}
		}
	}

	// App-level actions.
	for _, h := range m.Actions {
		route := routeWithTrailingSlash(h.Route)
		method := strings.ToUpper(h.HTTPMethod)

		w.Line(1, "s.mux.HandleFunc(")
		w.Raw("\t\t\"")
		w.Raw(method)
		w.Byte(' ')
		w.Raw(route)
		w.Raw("{$}\",\n")
		w.Raw("\t\ts.handle")
		w.Raw(method)
		w.Raw(h.Name)
		w.Raw(")\n")
	}

	// Page actions.
	for _, p := range m.Pages {
		for _, h := range p.Actions {
			route := routeWithTrailingSlash(h.Route)
			method := strings.ToUpper(h.HTTPMethod)

			w.Line(1, "s.mux.HandleFunc(")
			w.Raw("\t\t\"")
			w.Raw(method)
			w.Byte(' ')
			w.Raw(route)
			w.Raw("{$}\",\n")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw(method)
			w.Raw(h.Name)
			w.Raw(")\n")
		}
	}

	w.Line(0, "}")
}

func (w *Writer) writeAppErrHelpers(m *model.App, appPkg string) {
	// httpErrIntern calls Recover500 if available.
	if m.Recover500 != nil && m.PageError500 != nil {
		w.Raw(`
func (s *Server) httpErrIntern(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.logErr(msg, err)
	if !isDSReq(r) {
		s.handlePageError500GET(w, r)
		return
	}
	if sse == nil {
		sse = datastar.NewSSE(w, r, datastar.WithCompression())
	}
	errRecover := s.`)
		w.Raw(appPkg)
		w.Raw(`.Recover500(err, sse)
	if errRecover == nil {
		mInternalErrorsRecovered.Inc()
		return // Feedback delivered gracefully.
	}
	// Fallback to ugly 500
	mInternalErrorsNotRecovered.Inc()
	s.logger.Error("recovering 500",
		slog.Any("orig.msg", msg),
		slog.Any("orig.err", err),
		slog.Any("err", errRecover))
	const code = http.StatusInternalServerError
	http.Error(w, http.StatusText(code), code)
}
`)
	} else {
		w.Raw(`
func (s *Server) httpErrIntern(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.logErr(msg, err)
	const code = http.StatusInternalServerError
	http.Error(w, http.StatusText(code), code)
}
`)
	}
}

func (w *Writer) writeRender404(m *model.App, appPkg string) {
	p := m.PageError404

	w.Line(0, "")
	w.Line(0, "func (s *Server) render404(w http.ResponseWriter, r *http.Request) {")
	w.Line(1, "sess, _, ok := s.auth(w, r)")
	w.Line(1, "if !ok {")
	w.Line(2, "return")
	w.Line(1, "}")
	w.Line(0, "")

	w.writePageConstructorStmt("p", p, appPkg)
	w.Line(0, "")

	// Call GET.
	w.writeGETCall(p, appPkg, "render404")

	w.Line(0, "}")
}

func (w *Writer) writePageConstructorStmt(varName string, p *model.Page, appPkg string) {
	w.Byte('\t')
	w.Raw(varName)
	w.Raw(" := ")
	w.Raw(appPkg)
	w.Byte('.')
	w.Raw(p.TypeName)
	w.Raw("{\n")
	w.Line(2, "App: s.app,")
	for _, embed := range p.Embeds {
		w.writeEmbedInitStmt(embed, appPkg, 2)
	}
	w.Line(1, "}")
}

func (w *Writer) writeEmbedInitStmt(ap *model.AbstractPage, appPkg string, indent int) {
	for range indent {
		w.Byte('\t')
	}
	w.Raw(ap.TypeName)
	w.Raw(": ")
	w.Raw(appPkg)
	w.Byte('.')
	w.Raw(ap.TypeName)
	w.Raw("{\n")
	w.Line(indent+1, "App: s.app,")
	for _, sub := range ap.Embeds {
		w.writeEmbedInitStmt(sub, appPkg, indent+1)
	}
	w.Line(indent, "},")
}

// App-level action handler generation kept here; methodized.

func (w *Writer) writeAppActionHandler(h *model.Handler, m *model.App, appPkg string) {
	w.Line(0, "")
	w.Raw("func (s *Server) handle")
	w.Raw(strings.ToUpper(h.HTTPMethod))
	w.Raw(h.Name)
	w.Raw("(w http.ResponseWriter, r *http.Request) {\n")

	if h.InputSSE != nil || h.InputSignals != nil {
		w.Line(1, "if !s.checkIsDSReq(w, r) {")
		w.Line(2, "return")
		w.Line(1, "}")
		w.Line(0, "")
	}

	// Auth.
	needsToken := h.InputSessionToken != nil || h.OutputCloseSession != nil
	if h.InputSession != nil || needsToken {
		if needsToken {
			w.Line(1, "sess, sessToken, ok := s.auth(w, r)")
		} else {
			w.Line(1, "sess, _, ok := s.auth(w, r)")
		}
		w.Line(1, "if !ok {")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Build the call.
	w.writeHandlerCallAndOutputs(nil, h, m, appPkg, true)

	w.Line(0, "}")
}

func (w *Writer) writeHandlerCallAndOutputs(
	p *model.Page, h *model.Handler, m *model.App, appPkg string, isAppLevel bool,
) {
	// Body size limit for non-GET actions.
	if h.InputSignals != nil && h.InputSSE == nil {
		w.Line(1, "r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)")
	}

	// Read signals.
	if h.InputSignals != nil {
		w.Raw("\tvar signals ")
		w.Raw(renderSignalsType(h.InputSignals, m))
		w.Byte('\n')
		w.Line(1, "if err := datastar.ReadSignals(r, &signals); err != nil {")
		w.Line(2, `s.httpErrBad(w, "reading signals", err)`)
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Read query params.
	if h.InputQuery != nil {
		w.writeReadQuery(h.InputQuery, m)
	}

	// Read path params.
	if h.InputPath != nil {
		w.writeReadPath(h.InputPath, m)
	}

	// Dispatch closure.
	if h.InputDispatch != nil {
		w.writeDispatchClosure(h.InputDispatch, m, appPkg)
	}

	// SSE for actions that take it.
	if h.InputSSE != nil && !isAppLevel {
		w.Line(0, "")
		w.Line(1, "sse := datastar.NewSSE(w, r, datastar.WithCompression())")
	}

	// Page constructor (for page actions).
	if p != nil {
		w.writePageConstructorStmt("p", p, appPkg)
	}

	// Build the actual method call.
	w.writeMethodCall(p, h, m, appPkg, isAppLevel)
}

func (w *Writer) writeMethodCall(
	p *model.Page, h *model.Handler, m *model.App, appPkg string, isAppLevel bool,
) {
	// Build output variable list.
	var outsBuf [8]string
	outs := outsBuf[:0]
	if h.OutputBody != nil {
		outs = append(outs, h.OutputBody.Name)
	}
	if h.OutputCloseSession != nil {
		outs = append(outs, h.OutputCloseSession.Name)
	}
	if h.OutputRedirect != nil {
		outs = append(outs, h.OutputRedirect.Name)
	}
	if h.OutputRedirectStatus != nil {
		outs = append(outs, h.OutputRedirectStatus.Name)
	}
	if h.OutputNewSession != nil {
		outs = append(outs, h.OutputNewSession.Name)
	}
	if h.OutputEnableBgStream != nil {
		outs = append(outs, h.OutputEnableBgStream.Name)
	}
	if h.OutputDisableRefresh != nil {
		outs = append(outs, h.OutputDisableRefresh.Name)
	}
	if h.OutputErr != nil {
		outs = append(outs, "err")
	}

	// Build input args.
	var argsBuf [8]string
	args := argsBuf[:0]
	if h.InputRequest != nil {
		args = append(args, "r")
	}
	if h.InputSSE != nil && !isAppLevel {
		args = append(args, "sse")
	}
	if h.InputSessionToken != nil {
		args = append(args, "sessToken")
	}
	if h.InputSession != nil {
		args = append(args, "sess")
	}
	if h.InputPath != nil {
		args = append(args, "path")
	}
	if h.InputQuery != nil {
		args = append(args, "query")
	}
	if h.InputSignals != nil {
		args = append(args, "signals")
	}
	if h.InputDispatch != nil {
		args = append(args, "dispatch")
	}

	// Build the call expression.
	receiver := "p"
	if isAppLevel {
		receiver = "s.app"
	}
	methodName := h.HTTPMethod + h.Name

	if len(outs) == 0 {
		// Void return or only error.
		if h.OutputErr != nil {
			w.Raw("\tif err := ")
			w.writeCallExpr(receiver, methodName, args)
			w.Raw("; err != nil {\n")
			w.Raw("\t\ts.httpErrIntern(w, r, nil, \"handling action ")
			w.Raw(actionOwnerName(p, isAppLevel))
			w.Byte('.')
			w.Raw(h.Name)
			w.Raw("\", err)\n")
			w.Line(1, "}")
		} else {
			w.Byte('\t')
			w.writeCallExpr(receiver, methodName, args)
			w.Byte('\n')
		}
		return
	}

	w.Byte('\t')
	w.writeCommaSep(outs)
	w.Raw(" := ")
	w.writeCallExpr(receiver, methodName, args)
	w.Byte('\n')

	if h.OutputErr != nil {
		sseRef := "nil"
		if h.InputSSE != nil && !isAppLevel {
			sseRef = "sse"
		}
		w.Line(1, "if err != nil {")
		w.Raw("\t\ts.httpErrIntern(w, r, ")
		w.Raw(sseRef)
		w.Raw(", \"handling ")
		w.Raw(handlerKind(h))
		if handlerKind(h) != "" {
			w.Byte(' ')
		}
		w.Raw(actionOwnerName(p, isAppLevel))
		w.Byte('.')
		w.Raw(h.Name)
		w.Raw("\", err)\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Close session.
	if h.OutputCloseSession != nil {
		w.Raw("\tif ")
		w.Raw(h.OutputCloseSession.Name)
		w.Raw(" {\n")
		w.Line(2, "if err := s.closeSession(w, r, sessToken); err != nil {")
		w.Line(3, `s.httpErrIntern(w, r, nil, "removing session", err)`)
		w.Line(3, "return")
		w.Line(2, "}")
		w.Line(1, "}")
	}

	// New session.
	if h.OutputNewSession != nil {
		w.Raw("\tif j := ")
		w.Raw(h.OutputNewSession.Name)
		w.Raw("; j.UserID != \"\" {\n")
		w.Raw("\t\tif err := s.createSession(w, r, ")
		w.Raw(h.OutputNewSession.Name)
		w.Raw("); err != nil {\n")
		w.Line(3, `s.httpErrIntern(w, r, nil, "creating session", err)`)
		w.Line(2, "}")
		w.Line(1, "}")
	}

	// Redirect.
	if h.OutputRedirect != nil {
		statusArg := "0"
		if h.OutputRedirectStatus != nil {
			statusArg = h.OutputRedirectStatus.Name
		}
		w.Raw("\tif httpRedirect(w, r, ")
		w.Raw(h.OutputRedirect.Name)
		w.Raw(", ")
		w.Raw(statusArg)
		w.Raw(") {\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Render body (if action returns templ.Component).
	if h.OutputBody != nil {
		ownerName := actionOwnerName(p, isAppLevel)

		if m.GlobalHeadGenerator != nil {
			w.Line(1, "genericHead, err := s.app.Head(r)")
			w.Line(1, "if err != nil {")
			w.Raw("\t\ts.httpErrIntern(w, r, nil, \"generating generic head for ")
			w.Raw(ownerName)
			w.Byte('.')
			w.Raw(h.HTTPMethod)
			w.Raw(h.Name)
			w.Raw("\", err)\n")
			w.Line(2, "return")
			w.Line(1, "}")
		}

		genericHeadArg := "nil"
		if m.GlobalHeadGenerator != nil {
			genericHeadArg = "genericHead"
		}

		sessArg := "sess"
		if !hasSessionInput(h) {
			sessArg = appPkg + ".Session{}"
		}

		w.Line(1, "if err := s.writeHTML(")
		w.Raw("\t\tw, r, ")
		w.Raw(sessArg)
		w.Raw(", ")
		w.Raw(genericHeadArg)
		w.Raw(", nil, ")
		w.Raw(h.OutputBody.Name)
		w.Raw(", nil,\n")
		w.Line(1, "); err != nil {")
		w.Raw("\t\ts.logErr(\"rendering response of ")
		w.Raw(ownerName)
		w.Byte('.')
		w.Raw(h.HTTPMethod)
		w.Raw(h.Name)
		w.Raw("\", err)\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}
}

func (w *Writer) writeDispatchClosure(d *model.InputDispatch, m *model.App, appPkg string) {
	w.Line(0, "")
	w.Line(1, "dispatch := func(")
	for i, evName := range d.EventTypeNames {
		w.Raw("\t\te")
		w.Raw(itoa(i + 1))
		w.Byte(' ')
		w.Raw(appPkg)
		w.Byte('.')
		w.Raw(evName)
		w.Raw(",\n")
	}
	w.Line(1, ") error {")

	for i, evName := range d.EventTypeNames {
		idx := itoa(i + 1)
		ev := w.eventMap[evName]
		w.Line(2, "{")
		w.Raw("\t\t\tj, err := json.Marshal(e")
		w.Raw(idx)
		w.Raw(")\n")
		w.Line(3, "if err != nil {")
		w.Raw("\t\t\t\treturn fmt.Errorf(\"marshaling ")
		w.Raw(evName)
		w.Raw(" JSON: %w\", err)\n")
		w.Line(3, "}")

		if ev != nil && ev.HasTargetUserIDs {
			w.Raw("\t\t\tfor _, uid := range e")
			w.Raw(idx)
			w.Raw(".TargetUserIDs {\n")
			w.Raw("\t\t\t\tsubj := ")
			w.Raw(evSubjPrefConst(ev))
			w.Raw(" + uid\n")
			w.Line(4, "err = s.messageBroker.Publish(r.Context(), s.messageBrokerMetrics, subj, j)")
			w.Line(4, "if err != nil {")
			w.Line(5, "return fmt.Errorf(\"publishing subject %q: %w\", subj, err)")
			w.Line(4, "}")
			w.Line(3, "}")
		} else if ev != nil {
			w.Raw("\t\t\terr = s.messageBroker.Publish(r.Context(), s.messageBrokerMetrics, ")
			w.Raw(evSubjConst(ev))
			w.Raw(", j)\n")
			w.Line(3, "if err != nil {")
			w.Raw("\t\t\t\treturn fmt.Errorf(\"publishing subject %q: %w\", ")
			w.Raw(evSubjConst(ev))
			w.Raw(", err)\n")
			w.Line(3, "}")
		}
		w.Line(2, "}")
	}

	w.Line(2, "return nil")
	w.Line(1, "}")
}

func renderSignalsType(input *model.Input, m *model.App) string {
	if isNamedType(input.Type) {
		return renderType(input.Type, m.PkgPath)
	}
	return renderAnonStructType(input.Type, m.Fset)
}

func renderQueryType(input *model.Input, m *model.App) string {
	if isNamedType(input.Type) {
		return renderType(input.Type, m.PkgPath)
	}
	return renderAnonStructType(input.Type, m.Fset)
}

func renderPathType(input *model.Input, m *model.App) string {
	if isNamedType(input.Type) {
		return renderType(input.Type, m.PkgPath)
	}
	return renderAnonStructType(input.Type, m.Fset)
}

func handlerKind(h *model.Handler) string {
	if h.HTTPMethod == "" || h.HTTPMethod == "GET" {
		return ""
	}
	return "action"
}

func actionOwnerName(p *model.Page, isAppLevel bool) string {
	if isAppLevel {
		return "App"
	}
	if p != nil {
		return p.TypeName
	}
	return "App"
}

// writeGETCall generates the GET method call and HTML rendering for a page.
func (w *Writer) writeGETCall(p *model.Page, appPkg string, context string) {
	if p.GET == nil {
		return
	}
	h := p.GET.Handler

	// Build output list.
	var outsBuf [8]string
	outs := outsBuf[:0]
	if p.GET.OutputBody != nil {
		outs = append(outs, p.GET.OutputBody.Name)
	}
	if p.GET.OutputHead != nil {
		outs = append(outs, p.GET.OutputHead.Name)
	}
	if h.OutputRedirect != nil {
		outs = append(outs, h.OutputRedirect.Name)
	}
	if h.OutputDisableRefresh != nil {
		outs = append(outs, h.OutputDisableRefresh.Name)
	}
	if h.OutputEnableBgStream != nil {
		outs = append(outs, h.OutputEnableBgStream.Name)
	}
	if h.OutputErr != nil {
		outs = append(outs, "err")
	}

	// Build input args.
	var argsBuf [8]string
	args := argsBuf[:0]
	if h.InputRequest != nil {
		args = append(args, "r")
	}
	if h.InputSession != nil {
		args = append(args, "sess")
	}
	if h.InputPath != nil {
		args = append(args, "path")
	}
	if h.InputQuery != nil {
		args = append(args, "query")
	}

	w.Byte('\t')
	w.writeCommaSep(outs)
	w.Raw(" := ")
	w.writeCallExpr("p", "GET", args)
	w.Byte('\n')

	if h.OutputErr != nil {
		w.Line(1, "if err != nil {")
		w.Raw("\t\ts.httpErrIntern(w, r, nil, \"handling ")
		w.Raw(p.TypeName)
		w.Raw(".GET\", err)\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Redirect.
	if h.OutputRedirect != nil {
		w.Raw("\tif httpRedirect(w, r, ")
		w.Raw(h.OutputRedirect.Name)
		w.Raw(", 0) {\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Generic head.
	w.Line(1, "genericHead, err := s.app.Head(r)")
	w.Line(1, "if err != nil {")
	w.Raw("\t\ts.httpErrIntern(w, r, nil, \"generating generic head for ")
	w.Raw(p.TypeName)
	w.Raw("\", err)\n")
	w.Line(2, "return")
	w.Line(1, "}")

	// Body attrs - simple for render404/error pages.
	w.Line(0, "")
	w.Line(1, "bodyAttrs := func(w http.ResponseWriter) {")
	w.Line(2, "writeBodyAttrOnVisibilityChange(w)")
	w.Line(1, "}")

	// writeHTML call.
	sessArg := "sess"
	if p.PageSpecialization == model.PageTypeError500 {
		sessArg = appPkg + ".Session{}"
	} else if p.PageSpecialization == model.PageTypeError404 && context == "render404" {
		sessArg = appPkg + ".Session{}"
	}

	headArg := "nil"
	if p.GET.OutputHead != nil {
		headArg = p.GET.OutputHead.Name
	}

	w.Line(1, "if err := s.writeHTML(")
	w.Raw("\t\tw, r, ")
	w.Raw(sessArg)
	w.Raw(", genericHead, ")
	w.Raw(headArg)
	w.Raw(", body, bodyAttrs,\n")
	w.Line(1, "); err != nil {")
	w.Raw("\t\ts.logErr(\"rendering ")
	w.Raw(p.TypeName)
	w.Raw("\", err)\n")
	w.Line(2, "return")
	w.Line(1, "}")
}
