package generator

import (
	"slices"
	"strings"

	"github.com/romshark/datapages/parser/model"
)

// WritePkgAction generates code for the datapagesgen/action package
// and appends it to buffer.
func (w *Writer) WritePkgAction(m *model.App) {
	needsStrings := false

	// Count total page actions and check if any action uses path or query params.
	nPageActions := 0
	for _, a := range m.Actions {
		if a.InputPath != nil || a.InputQuery != nil {
			needsStrings = true
		}
	}
	for _, p := range m.Pages {
		nPageActions += len(p.Actions)
		if needsStrings {
			continue
		}
		for _, a := range p.Actions {
			if a.InputPath != nil || a.InputQuery != nil {
				needsStrings = true
			}
		}
	}

	w.writeActionHeader(needsStrings)

	type actionEntry struct {
		funcName   string
		httpMethod string
		route      string
		queryInput *model.Input
	}

	// Collect and sort app actions.
	appActions := make([]actionEntry, len(m.Actions))
	for i, a := range m.Actions {
		appActions[i] = actionEntry{
			funcName:   strings.ToUpper(a.HTTPMethod) + "App" + a.Name,
			httpMethod: a.HTTPMethod,
			route:      a.Route,
			queryInput: a.InputQuery,
		}
	}
	slices.SortFunc(appActions, func(a, b actionEntry) int {
		return strings.Compare(a.funcName, b.funcName)
	})

	// Collect and sort page actions.
	pageActions := make([]actionEntry, 0, nPageActions)
	for _, p := range m.Pages {
		pageSuffix := stripPagePrefix(p.TypeName)
		for _, a := range p.Actions {
			pageActions = append(pageActions, actionEntry{
				funcName:   strings.ToUpper(a.HTTPMethod) + "Page" + pageSuffix + a.Name,
				httpMethod: a.HTTPMethod,
				route:      a.Route,
				queryInput: a.InputQuery,
			})
		}
	}
	slices.SortFunc(pageActions, func(a, b actionEntry) int {
		return strings.Compare(a.funcName, b.funcName)
	})

	// Emit App actions first, then page actions.
	for _, a := range appActions {
		w.writeActionFunc(a.funcName, a.httpMethod, a.route, a.queryInput)
	}
	for _, a := range pageActions {
		w.writeActionFunc(a.funcName, a.httpMethod, a.route, a.queryInput)
	}
}

func (w *Writer) writeActionHeader(needsStrings bool) {
	w.Line(0, "// Generated by github.com/romshark/datapages. DO NOT EDIT.")
	w.Line(0, "")
	w.Line(0, "// Package action provides generators for datastar action hypertext references.")
	w.Line(0, "// These references must be used in the templates.")
	w.Line(0, "package action")
	w.Line(0, "")
	if needsStrings {
		w.Line(0, `import "strings"`)
	}
}

// writeActionRouteComment writes a doc comment line like
// "// FuncName references /route/\n".
// It strips {$} and ensures a trailing slash.
func (w *Writer) writeActionRouteComment(funcName, route string) {
	w.Raw("// ")
	w.Raw(funcName)
	w.Raw(" references ")
	w.writeRouteURL(route)
	w.Byte('\n')
}

func (w *Writer) writeActionFunc(
	funcName string,
	httpMethod string,
	route string,
	queryInput *model.Input,
) {
	pathVars := routeVars(route)
	hasPathVars := len(pathVars) > 0

	var queryFields []structFieldInfo
	if queryInput != nil {
		queryFields = structFields(queryInput.Type.Resolved)
	}
	hasQuery := len(queryFields) > 0

	method := strings.ToLower(httpMethod)

	// Doc comment.
	w.Line(0, "")
	w.writeActionRouteComment(funcName, route)

	if !hasPathVars && !hasQuery {
		// Simple return with literal string.
		w.Linef(0, "func %s() string {", funcName)
		w.Raw("\treturn \"@")
		w.Raw(method)
		w.Raw("('")
		w.writeRouteURL(route)
		w.Raw("')\"\n")
		w.Line(0, "}")
		return
	}

	if hasPathVars && !hasQuery {
		w.writeActionFuncPathOnly(funcName, method, route, pathVars)
		return
	}

	if !hasPathVars && hasQuery {
		w.writeActionFuncQueryOnly(funcName, method, route, queryFields)
		w.writeActionQueryType(funcName, queryFields)
		return
	}

	// Both path and query.
	w.writeActionFuncPathAndQuery(funcName, method, route, pathVars, queryFields)
	w.writeActionQueryType(funcName, queryFields)
}

func (w *Writer) writeActionFuncPathOnly(
	funcName string,
	method string,
	route string,
	pathVars []string,
) {
	literals, _ := routeSegments(route)

	// func FuncName(params) string {
	w.Raw("func ")
	w.Raw(funcName)
	w.Byte('(')
	w.writeJoinParams(pathVars)
	w.Raw(") string {\n")
	w.Line(1, "var b strings.Builder")

	// b.Grow(len("@method('lit0") + len(v0) + len("lit1") + ... + len("litN')")
	w.Raw("\tb.Grow(len(\"@")
	w.Raw(method)
	w.Raw("('")
	w.Raw(literals[0])
	w.Raw("\")")
	for i, v := range pathVars {
		w.Raw(" + len(")
		w.Raw(v)
		w.Raw(") + len(\"")
		w.Raw(literals[i+1])
		if i == len(pathVars)-1 {
			w.Raw("')")
		}
		w.Raw("\")")
	}
	w.Raw(")\n")

	// b.WriteString("@method('lit0")
	w.Raw("\tb.WriteString(\"@")
	w.Raw(method)
	w.Raw("('")
	w.Raw(literals[0])
	w.Raw("\")\n")
	for i, v := range pathVars {
		w.Raw("\tb.WriteString(")
		w.Raw(v)
		w.Raw(")\n")
		w.Raw("\tb.WriteString(\"")
		w.Raw(literals[i+1])
		if i == len(pathVars)-1 {
			w.Raw("')")
		}
		w.Raw("\")\n")
	}

	w.Line(1, "return b.String()")
	w.Line(0, "}")
}

func (w *Writer) writeActionFuncQueryOnly(
	funcName string,
	method string,
	route string,
	fields []structFieldInfo,
) {
	// func FuncName(query QueryFuncName) string {
	w.Raw("func ")
	w.Raw(funcName)
	w.Raw("(query Query")
	w.Raw(funcName)
	w.Raw(") string {\n")

	// anyQuery check.
	w.writeAnyCheck("anyQuery", fields)
	w.Line(0, "")

	// Builder and length calculation.
	w.Line(1, "var b strings.Builder")
	w.Raw("\tl := len(\"@")
	w.Raw(method)
	w.Raw("('")
	w.writeRouteURL(route)
	w.Raw("\") + len(\"')\")\n")
	w.Line(1, "if anyQuery {")
	w.Line(2, `l += len("?")`)
	w.Line(1, "}")

	// Query param length accumulation.
	w.Line(1, "n := 0")
	for _, f := range fields {
		tag := queryTagValue(f.Tag)
		w.writeIfZeroCheck(1, "query."+f.Name, f.Type)
		w.Line(2, "if n > 0 {")
		w.Line(3, `l += len("&")`)
		w.Line(2, "}")
		w.Line(2, "n++")
		w.Raw("\t\tl += len(\"")
		w.Raw(tag)
		w.Raw("=\") + len(query.")
		w.Raw(f.Name)
		w.Raw(")\n")
		w.Line(1, "}")
	}
	w.Line(1, "_ = n")
	w.Line(0, "")

	// Grow and write.
	w.Line(1, "b.Grow(l)")
	w.Line(0, "")
	w.Raw("\tb.WriteString(\"@")
	w.Raw(method)
	w.Raw("('")
	w.writeRouteURL(route)
	w.Raw("\")\n")
	w.Line(1, "if anyQuery {")
	w.Line(2, `b.WriteString("?")`)
	w.Line(1, "}")

	// Write query params.
	w.Line(1, "n = 0")
	for _, f := range fields {
		tag := queryTagValue(f.Tag)
		w.writeIfZeroCheck(1, "query."+f.Name, f.Type)
		w.Line(2, "if n > 0 {")
		w.Line(3, `b.WriteString("&")`)
		w.Line(2, "}")
		w.Line(2, "n++")
		w.Line(2, "_ = n")
		w.Raw("\t\tb.WriteString(\"")
		w.Raw(tag)
		w.Raw("=\")\n")
		w.Raw("\t\tb.WriteString(query.")
		w.Raw(f.Name)
		w.Raw(")\n")
		w.Line(1, "}")
	}

	w.Line(1, `b.WriteString("')")`)
	w.Line(0, "")
	w.Line(1, "return b.String()")
	w.Line(0, "}")
}

func (w *Writer) writeActionFuncPathAndQuery(
	funcName string,
	method string,
	route string,
	pathVars []string,
	fields []structFieldInfo,
) {
	literals, _ := routeSegments(route)

	// func FuncName(params, query QueryFuncName) string {
	w.Raw("func ")
	w.Raw(funcName)
	w.Byte('(')
	w.writeJoinParams(pathVars)
	w.Raw(", query Query")
	w.Raw(funcName)
	w.Raw(") string {\n")

	// anyQuery check.
	w.writeAnyCheck("anyQuery", fields)
	w.Line(0, "")

	// Builder and length calculation.
	w.Line(1, "var b strings.Builder")

	// l := len("@method('lit0") + len(v0) + len("lit1") + ... + len("')")
	w.Raw("\tl := len(\"@")
	w.Raw(method)
	w.Raw("('")
	w.Raw(literals[0])
	w.Raw("\")")
	for i, v := range pathVars {
		w.Raw(" + len(")
		w.Raw(v)
		w.Raw(") + len(\"")
		w.Raw(literals[i+1])
		w.Raw("\")")
	}
	w.Raw(" + len(\"')\")\n")

	w.Line(1, "if anyQuery {")
	w.Line(2, `l += len("?")`)
	w.Line(1, "}")

	// Query param length accumulation.
	w.Line(1, "n := 0")
	for _, f := range fields {
		tag := queryTagValue(f.Tag)
		w.writeIfZeroCheck(1, "query."+f.Name, f.Type)
		w.Line(2, "if n > 0 {")
		w.Line(3, `l += len("&")`)
		w.Line(2, "}")
		w.Line(2, "n++")
		w.Raw("\t\tl += len(\"")
		w.Raw(tag)
		w.Raw("=\") + len(query.")
		w.Raw(f.Name)
		w.Raw(")\n")
		w.Line(1, "}")
	}
	w.Line(1, "_ = n")
	w.Line(0, "")

	// Grow and write path segments.
	w.Line(1, "b.Grow(l)")
	w.Line(0, "")
	w.Raw("\tb.WriteString(\"@")
	w.Raw(method)
	w.Raw("('")
	w.Raw(literals[0])
	w.Raw("\")\n")
	for i, v := range pathVars {
		w.Raw("\tb.WriteString(")
		w.Raw(v)
		w.Raw(")\n")
		w.Raw("\tb.WriteString(\"")
		w.Raw(literals[i+1])
		w.Raw("\")\n")
	}

	w.Line(1, "if anyQuery {")
	w.Line(2, `b.WriteString("?")`)
	w.Line(1, "}")

	// Write query params.
	w.Line(1, "n = 0")
	for _, f := range fields {
		tag := queryTagValue(f.Tag)
		w.writeIfZeroCheck(1, "query."+f.Name, f.Type)
		w.Line(2, "if n > 0 {")
		w.Line(3, `b.WriteString("&")`)
		w.Line(2, "}")
		w.Line(2, "n++")
		w.Line(2, "_ = n")
		w.Raw("\t\tb.WriteString(\"")
		w.Raw(tag)
		w.Raw("=\")\n")
		w.Raw("\t\tb.WriteString(query.")
		w.Raw(f.Name)
		w.Raw(")\n")
		w.Line(1, "}")
	}

	w.Line(1, `b.WriteString("')")`)
	w.Line(0, "")
	w.Line(1, "return b.String()")
	w.Line(0, "}")
}

func (w *Writer) writeActionQueryType(funcName string, fields []structFieldInfo) {
	w.Line(0, "")
	w.Raw("type Query")
	w.Raw(funcName)
	w.Raw(" struct {\n")

	// Find longest field name for alignment.
	maxNameLen := 0
	for _, f := range fields {
		if len(f.Name) > maxNameLen {
			maxNameLen = len(f.Name)
		}
	}
	// Find longest type name for alignment.
	maxTypeLen := 0
	for _, f := range fields {
		typeName := fieldTypeName(f.Type)
		if len(typeName) > maxTypeLen {
			maxTypeLen = len(typeName)
		}
	}

	for _, f := range fields {
		tag := queryTagValue(f.Tag)
		typeName := fieldTypeName(f.Type)
		w.Linef(1, "\t%-*s %-*s `query:\"%s\"`",
			maxNameLen, f.Name, maxTypeLen, typeName, tag)
	}

	w.Line(0, "}")
}
