// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"

	"github.com/a-h/templ"
	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/httpserve"

	"github.com/romshark/datapages/example/fast-shim/app"
	"github.com/romshark/datapages/example/fast-shim/app/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

const DefaultBodySizeLimit = httpserve.DefaultBodySizeLimit

// newPageCache builds the page cache handle for the request. sse is the
// action's SSE generator, or nil for GET and redirect handlers.
func newPageCache(
	s *Server, r *http.Request, sse *datastar.ServerSentEventGenerator,
) *pageCacheWriter {
	return &pageCacheWriter{s: s, r: r, sse: sse}
}

// pageCacheBuf adapts a buffer to http.ResponseWriter. Cached bodies render
// through the same writeHTML the live pages use.
type pageCacheBuf struct {
	b strings.Builder
	h http.Header
}

func (p *pageCacheBuf) Header() http.Header {
	if p.h == nil {
		p.h = http.Header{}
	}
	return p.h
}
func (p *pageCacheBuf) Write(b []byte) (int, error) { return p.b.Write(b) }
func (p *pageCacheBuf) WriteHeader(int)             {}

func (s *Server) pageCacheHead(r *http.Request) datapages.Head {
	return s.app.Head(r)
}

type pageCacheWriter struct {
	s        *Server
	r        *http.Request
	sse      *datastar.ServerSentEventGenerator // nil for GET handlers
	clearAll bool
	sets     []pageCachePendingSet
	clears   []string
}

type pageCachePendingSet struct {
	url     string
	body    datapages.Component
	version uint64
	shim    bool
}

// Version reports the version the client holds for this request's URL. A missing
// or malformed header parses to 0, meaning nothing cached. The handler
// re-caches instead of trusting a bad value.
func (c *pageCacheWriter) Version() uint64 {
	v, _ := strconv.ParseUint(
		c.r.Header.Get(datapages.HeaderOfflineVersion), 10, 64,
	)
	return v
}

func (c *pageCacheWriter) Set(url string, body datapages.Component, version uint64) {
	c.sets = append(c.sets, pageCachePendingSet{url: url, body: body, version: version})
}

func (c *pageCacheWriter) SetShim(
	url string, body datapages.Component, version uint64,
) {
	c.sets = append(c.sets, pageCachePendingSet{
		url: url, body: body, version: version, shim: true,
	})
}

func (c *pageCacheWriter) Clear(url string) { c.clears = append(c.clears, url) }

func (c *pageCacheWriter) ClearAll() { c.clearAll = true }

type pageCacheEntry struct {
	URL     string `json:"url"`
	HTML    string `json:"html"`
	Version uint64 `json:"version"`
	Shim    bool   `json:"shim,omitempty"`
}

// shimHydrateScript is appended to every shim. Datastar has no imperative API,
// so the script adds a data-init element. Datastar's MutationObserver sees it,
// requests this URL, and morphs in the live page the worker prefetched. The
// element stays in the DOM (removing it on a timer can beat Datastar's deferred
// module load); the morph drops it, as the live page has no such element.
func withShimHydrate(body datapages.Component) datapages.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		if err := body.Render(ctx, w); err != nil {
			return err
		}
		_, err := io.WriteString(w, shimHydrateScript)
		return err
	})
}

const shimHydrateScript = `<script>(function(){
var el=document.createElement("div");
el.setAttribute("data-init","@get(window.location.pathname)");
document.body.appendChild(el);
})();</script>`

func (c *pageCacheWriter) payload() (string, error) {
	if !c.clearAll && len(c.sets) == 0 && len(c.clears) == 0 {
		return "", nil
	}
	entries := make([]pageCacheEntry, 0, len(c.sets))
	for _, s := range c.sets {
		// Cached entries are served standalone. Render a complete document, the
		// same <head>, stylesheets and Datastar bundle as a live page.
		var buf pageCacheBuf
		body := s.body
		if s.shim {
			body = withShimHydrate(body)
		}
		if err := c.s.writeHTML(
			&buf, c.r, c.s.pageCacheHead(c.r), nil, body, nil, nil,
		); err != nil {
			return "", fmt.Errorf("rendering page cache body for %s: %w", s.url, err)
		}
		entries = append(entries, pageCacheEntry{
			URL: s.url, HTML: buf.b.String(), Version: s.version, Shim: s.shim,
		})
	}
	msg := struct {
		Type     string           `json:"type"`
		ClearAll bool             `json:"clearAll"`
		Sets     []pageCacheEntry `json:"sets"`
		Clears   []string         `json:"clears"`
	}{
		Type:     "datapages-offline:apply",
		ClearAll: c.clearAll,
		Sets:     entries,
		Clears:   c.clears,
	}
	b, err := json.Marshal(msg)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func pageCachePostToWorkerJS(payloadJSON string) string {
	return "navigator.serviceWorker&&navigator.serviceWorker.ready.then(function(reg){" +
		"var w=reg.active||navigator.serviceWorker.controller;if(w)w.postMessage(" +
		payloadJSON + ");});"
}

// flush delivers the queued writes over the action's SSE stream.
func (c *pageCacheWriter) flush() error {
	if c.sse == nil {
		return nil
	}
	payload, err := c.payload()
	if err != nil || payload == "" {
		return err
	}
	return c.sse.ExecuteScript(pageCachePostToWorkerJS(payload))
}

// writeBake writes the queued writes as a trailing <script> into a GET response
// so the worker applies them on load.
func (c *pageCacheWriter) writeBake(w http.ResponseWriter) error {
	payload, err := c.payload()
	if err != nil || payload == "" {
		return err
	}
	_, err = fmt.Fprintf(w, "<script>%s</script>", pageCachePostToWorkerJS(payload))
	return err
}

// redirectScript returns JavaScript that delivers the queued writes to the worker
// and then navigates to target. Used by redirect-returning actions, whose response
// is a text/javascript body rather than an SSE stream. The navigation runs only
// after the message is posted. A ClearAll on sign-in or sign-out is not lost to
// the page unload.
func (c *pageCacheWriter) redirectScript(target string) (string, error) {
	tj, err := json.Marshal(target)
	if err != nil {
		return "", err
	}
	nav := "window.location=" + string(tj) + ";"

	payload, err := c.payload()
	if err != nil {
		return "", err
	}
	if payload == "" {
		return nav, nil
	}

	var b strings.Builder
	b.WriteString("(function(){var go=function(){")
	b.WriteString(nav)
	b.WriteString("};if(!navigator.serviceWorker){go();return;}")
	b.WriteString("var done=false,once=function(){if(!done){done=true;go();}};")
	b.WriteString("navigator.serviceWorker.ready.then(function(reg){")
	b.WriteString("var w=reg.active||navigator.serviceWorker.controller;")
	b.WriteString("if(w)w.postMessage(")
	b.WriteString(payload)
	b.WriteString(");once();},once);setTimeout(once,500);})();")
	return b.String(), nil
}

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	headGeneric, head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	return s.Core.WriteHTML(w, r, httpserve.HTMLDocument{
		HeadGeneric:     headGeneric,
		Head:            head,
		Body:            body,
		WriteBodyAttrs:  writeBodyAttrs,
		WriteBodySuffix: writeBodySuffix,
	})
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics messaging.NoopMetrics
	app                  *app.App
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[app.App, datapages.DisableSessions, datapages.DisablePrometheus, Server](app, broker, opts...)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *app.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[datapages.DisableSessions],
) error {
	if sessionManager != nil {
		return errors.New("unexpected option WithSessionManager: package app declares no session type")
	}
	if cfg.Prometheus != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}

	assetsFS, err := httpserve.AssetsFileSystem(cfg, "", "")
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core, err = httpserve.NewCore(cfg, "")
	if err != nil {
		return err
	}
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = messaging.NoopMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.Logger())

	return nil
}

const (

// Public events:

)

func MessageBrokerStreamSubjects() []string {
	return []string{}
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /",
		s.handlePageIndexGET)
	s.Mux().HandleFunc(
		"GET /noshim/{$}",
		s.handlePageNoShimGET)
	s.Mux().HandleFunc(
		"GET /noshim2/{$}",
		s.handlePageNoShim2GET)
	s.Mux().HandleFunc(
		"GET /subpage/{$}",
		s.handlePageSubpageGET)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	_ *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	const code = http.StatusInternalServerError
	http.Error(w, http.StatusText(code), code)
}

func (s *Server) handlePageIndexGET(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}
	pageCache := newPageCache(s, r, nil)

	p := app.PageIndex{
		App: s.app,
	}
	body, err := p.GET(r, pageCache)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, genericHead, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
	_ = pageCache.writeBake(w)
}

func (s *Server) handlePageNoShimGET(w http.ResponseWriter, r *http.Request) {
	p := app.PageNoShim{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageNoShim.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, genericHead, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageNoShim", err)
		return
	}
}

func (s *Server) handlePageNoShim2GET(w http.ResponseWriter, r *http.Request) {
	p := app.PageNoShim2{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageNoShim2.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, genericHead, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageNoShim2", err)
		return
	}
}

func (s *Server) handlePageSubpageGET(w http.ResponseWriter, r *http.Request) {
	pageCache := newPageCache(s, r, nil)
	p := app.PageSubpage{
		App: s.app,
	}
	body, err := p.GET(r, pageCache)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageSubpage.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, genericHead, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageSubpage", err)
		return
	}
	_ = pageCache.writeBake(w)
}
