// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strings"
	"sync/atomic"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/httpserve"
	dpsse "github.com/romshark/datapages/runtime/sse"
	"github.com/romshark/datapages/runtime/subject"

	"github.com/romshark/datapages/internal/acceptance/events/app"
	"github.com/romshark/datapages/internal/acceptance/events/app/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

// assetsFileSystem rejects datapages.WithAssets: the app package declares no
// embed.FS with a URL path in its doc comment, hence there is nothing to serve.
func assetsFileSystem(cfg datapages.ServerConfig) (http.FileSystem, error) {
	if cfg.AssetsFS != nil {
		return cfg.AssetsFS, nil
	}
	if cfg.AssetsEmbed != nil {
		return nil, errors.New(
			"datapages.WithAssets: the app package declares no assets",
		)
	}
	return nil, nil
}

// brokerMetrics implements messaging.Metrics as a no-op.
type brokerMetrics struct{}

func (m brokerMetrics) OnPublish(subject string) {}
func (m brokerMetrics) OnDeliveryDropped()       {}

// --- Message Broker ---

const DefaultBodySizeLimit = 1024 * 1024 // 1 MiB

func (s *Server) httpErrBad(w http.ResponseWriter, msg string, err error) {
	s.Logger().Debug("bad request", slog.String("cause", msg), slog.Any("err", err))
	http.Error(w, msg, http.StatusBadRequest)
}

func (s *Server) checkIsDSReq(w http.ResponseWriter, r *http.Request) (ok bool) {
	if !httpserve.IsDatastarRequest(r) {
		s.Logger().Debug("not a datastar request",
			slog.Any("method", r.Method),
			slog.String("path", r.URL.Path))
		http.Error(w, http.StatusText(http.StatusNotAcceptable), http.StatusNotAcceptable)
		return false
	}
	return true
}

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	_, err := io.WriteString(w, s.HTMLPrefix())
	if err != nil {
		return err
	}
	if head != nil {
		if err := head.Render(r.Context(), w); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "</head><body "); err != nil {
		return err
	}
	if writeBodyAttrs != nil {
		writeBodyAttrs(w)
	}
	if _, err := io.WriteString(w, ">"); err != nil {
		return err
	}
	if body != nil {
		if err := body.Render(r.Context(), w); err != nil {
			return err
		}
	}
	if writeBodySuffix != nil {
		if _, err := io.WriteString(w, "<template "); err != nil {
			return err
		}
		writeBodySuffix(w)
		if _, err := io.WriteString(w, "></template>"); err != nil {
			return err
		}
	}
	_, err = io.WriteString(w, "</body></html>")
	return err
}

func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request,
	subjects []string,
	onOpen func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
	) error,
	onClose func(streamID datapages.StreamID),
	fn func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
		ch <-chan messaging.Message,
	),
) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	streamID := datapages.StreamID(s.streamSeq.Add(1))

	// The subscription is established before the response head goes out.
	// A client learns the stream is open by reading that head and may dispatch
	// immediately after, which must not reach the broker before this.
	ctx := r.Context()
	sub, err := s.messageBroker.Subscribe(ctx, s.messageBrokerMetrics, subjects...)
	if err != nil {
		// Nothing has been written yet, so the error can still carry a status.
		s.httpErrIntern(w, r, nil, "subscribing to message broker", err)
		return
	}

	sse := datastar.NewSSE(w, r, datastar.WithCompression())

	subC := sub.C()
	if onOpen != nil {
		if err := onOpen(streamID, sse); err != nil {
			sub.Close()
			s.httpErrIntern(w, r, sse, "handling stream open hook", err)
			return
		}
	}
	go func() {
		select {
		case <-r.Context().Done():
		case <-s.ShutdownCh():
		}
		sub.Close()
		if onClose != nil {
			onClose(streamID)
		}
	}()

	fn(streamID, sse, subC)
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics brokerMetrics
	streamSeq            atomic.Uint64
	app                  *app.App
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[app.App, datapages.DisableSessions, datapages.DisablePrometheus, Server](app, broker, opts...)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *app.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[datapages.DisableSessions],
) error {
	if sessionManager != nil {
		return errors.New("unexpected option WithSessionManager: package app declares no session type")
	}
	if cfg.MetricsServer != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}

	assetsFS, err := assetsFileSystem(cfg)
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core = httpserve.NewCore(cfg, "")
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = brokerMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.Logger())

	return nil
}

const (

	// Public events:

	EvSubjNote          = "note"
	EvSubjPong          = "pong"
	EvSubjRoomBroadcast = "room.broadcast.*"
	EvSubjRoomSaid      = "room.said.*"
	EvSubjStreamGone    = "stream.gone"
	EvSubjTick          = "tick"
)

const (
	EvSubjPrefRoomBroadcast = "room.broadcast."
	EvSubjPrefRoomSaid      = "room.said."
)

func MessageBrokerStreamSubjects() []string {
	return []string{
		EvSubjNote,
		EvSubjPong,
		EvSubjRoomBroadcast,
		EvSubjRoomSaid,
		EvSubjStreamGone,
		EvSubjTick,
	}
}

var evSubjPageIndex = []string{
	EvSubjStreamGone,
	EvSubjPong,
	EvSubjTick,
	EvSubjNote,
}

var evSubjPageOther = []string{
	EvSubjTick,
}

func evSubjPageRoom(subjRoom string) []string {
	return []string{
		"room.said." + subjRoom,
		"room.broadcast." + subjRoom,
	}
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /",
		s.handlePageIndexGET)
	s.Mux().HandleFunc(
		"GET /_$/{$}",
		s.handlePageIndexGETStream)
	s.Mux().HandleFunc(
		"GET /log/{$}",
		s.handlePageLogGET)
	s.Mux().HandleFunc(
		"GET /other/{$}",
		s.handlePageOtherGET)
	s.Mux().HandleFunc(
		"GET /other/_$/{$}",
		s.handlePageOtherGETStream)
	s.Mux().HandleFunc(
		"GET /room/{$}",
		s.handlePageRoomGET)
	s.Mux().HandleFunc(
		"GET /room/_$/{$}",
		s.handlePageRoomGETStream)
	s.Mux().HandleFunc(
		"POST /note/{$}",
		s.handlePageIndexPOSTNote)
	s.Mux().HandleFunc(
		"POST /tick/{$}",
		s.handlePageIndexPOSTTick)
	s.Mux().HandleFunc(
		"POST /both/{$}",
		s.handlePageIndexPOSTBoth)
	s.Mux().HandleFunc(
		"POST /canceled/{$}",
		s.handlePageIndexPOSTCanceled)
	s.Mux().HandleFunc(
		"POST /room/say/{$}",
		s.handlePageRoomPOSTSay)
	s.Mux().HandleFunc(
		"POST /room/broadcast/{$}",
		s.handlePageRoomPOSTBroadcast)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	_ *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	switch {
	case errors.Is(err, datapages.ErrBadRequest):
		http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
	case errors.Is(err, datapages.ErrForbidden):
		http.Error(w, http.StatusText(http.StatusForbidden), http.StatusForbidden)
	case errors.Is(err, datapages.ErrNotFound):
		http.Error(w, http.StatusText(http.StatusNotFound), http.StatusNotFound)
	case errors.Is(err, datapages.ErrConflict):
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
	default:
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
	}
}

func (s *Server) handlePageIndexGET(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	p := app.PageIndex{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

func (s *Server) handlePageIndexGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	dispatchClosedStreamGone := dispatcherEventStreamGone{s: s, ctx: context.WithoutCancel(r.Context())}

	p := app.PageIndex{
		App: s.app,
	}
	s.handleStreamRequest(w, r, evSubjPageIndex,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			return p.StreamOpen(r, streamID)
		},
		func(streamID datapages.StreamID) {
			if err := p.StreamClose(r, streamID, dispatchClosedStreamGone); err != nil {
				s.LogErr("handling PageIndex.StreamClose", err)
			}
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventStreamGone app.EventStreamGone
			var eventPong app.EventPong
			var eventTick app.EventTick
			var eventNote app.EventNote
			for msg := range ch {
				switch msg.Subject {
				case EvSubjStreamGone:
					eventStreamGone = app.EventStreamGone{}
					if err := json.Unmarshal(msg.Data, &eventStreamGone); err != nil {
						s.LogErr("unmarshaling EventStreamGone JSON", err)
						continue
					}
					if err := p.OnStreamGone(eventStreamGone, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageIndex.OnStreamGone", err)
					}
				case EvSubjPong:
					eventPong = app.EventPong{}
					if err := json.Unmarshal(msg.Data, &eventPong); err != nil {
						s.LogErr("unmarshaling EventPong JSON", err)
						continue
					}
					if err := p.OnPong(eventPong, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageIndex.OnPong", err)
					}
				case EvSubjTick:
					eventTick = app.EventTick{}
					if err := json.Unmarshal(msg.Data, &eventTick); err != nil {
						s.LogErr("unmarshaling EventTick JSON", err)
						continue
					}
					if err := p.OnTick(eventTick, dpsse.New(sse), streamID); err != nil {
						s.LogErr("handling PageIndex.OnTick", err)
					}
				case EvSubjNote:
					eventNote = app.EventNote{}
					if err := json.Unmarshal(msg.Data, &eventNote); err != nil {
						s.LogErr("unmarshaling EventNote JSON", err)
						continue
					}
					if err := p.OnNote(eventNote, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageIndex.OnNote", err)
					}
				}
			}
		})
}

func (s *Server) handlePageIndexPOSTNote(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.checkIsDSReq(w, r) {
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		Text string `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.httpErrBad(w, "reading signals", err)
		return
	}

	dispatchNote := dispatcherEventNote{s: s, ctx: r.Context()}
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTNote(r, signals, dispatchNote)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Note", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTTick(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.checkIsDSReq(w, r) {
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		N int `json:"n"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.httpErrBad(w, "reading signals", err)
		return
	}

	dispatchTick := dispatcherEventTick{s: s, ctx: r.Context()}
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTTick(r, signals, dispatchTick)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Tick", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTBoth(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.checkIsDSReq(w, r) {
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		N int `json:"n"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.httpErrBad(w, "reading signals", err)
		return
	}

	dispatchTick := dispatcherEventTick{s: s, ctx: r.Context()}

	dispatchPong := dispatcherEventPong{s: s, ctx: r.Context()}
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTBoth(r, signals, dispatchTick, dispatchPong)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Both", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTCanceled(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.checkIsDSReq(w, r) {
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		N int `json:"n"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.httpErrBad(w, "reading signals", err)
		return
	}

	dispatchTick := dispatcherEventTick{s: s, ctx: r.Context()}
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTCanceled(r, signals, dispatchTick)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Canceled", err)
		return
	}
}

func (s *Server) handlePageLogGET(w http.ResponseWriter, r *http.Request) {
	p := app.PageLog{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageLog.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageLog", err)
		return
	}
}

func (s *Server) handlePageOtherGET(w http.ResponseWriter, r *http.Request) {
	p := app.PageOther{
		App: s.app,
		Notifier: app.Notifier{
			App: s.app,
		},
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageOther.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/other/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageOther", err)
		return
	}
}

func (s *Server) handlePageOtherGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	p := app.PageOther{
		App: s.app,
		Notifier: app.Notifier{
			App: s.app,
		},
	}
	s.handleStreamRequest(w, r, evSubjPageOther,
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventTick app.EventTick
			for msg := range ch {
				switch msg.Subject {
				case EvSubjTick:
					eventTick = app.EventTick{}
					if err := json.Unmarshal(msg.Data, &eventTick); err != nil {
						s.LogErr("unmarshaling EventTick JSON", err)
						continue
					}
					if err := p.OnTick(eventTick, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageOther.OnTick", err)
					}
				}
			}
		})
}

func (s *Server) handlePageRoomGET(w http.ResponseWriter, r *http.Request) {
	p := app.PageRoom{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageRoom.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/room/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageRoom", err)
		return
	}
}

func (s *Server) handlePageRoomGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	var subjSignals struct {
		Room string `json:"room"`
	}
	if err := datastar.ReadSignals(r, &subjSignals); err != nil {
		s.httpErrBad(w, "reading signals", err)
		return
	}
	if !subject.IsToken(subjSignals.Room) {
		s.httpErrBad(w, "invalid signal",
			fmt.Errorf("signal %q must be a non-empty subject token", "room"))
		return
	}

	p := app.PageRoom{
		App: s.app,
	}
	s.handleStreamRequest(w, r, evSubjPageRoom(subjSignals.Room),
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventRoomSaid app.EventRoomSaid
			var eventRoomBroadcast app.EventRoomBroadcast
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvSubjPrefRoomSaid):
					eventRoomSaid = app.EventRoomSaid{}
					if err := json.Unmarshal(msg.Data, &eventRoomSaid); err != nil {
						s.LogErr("unmarshaling EventRoomSaid JSON", err)
						continue
					}
					if err := p.OnRoomSaid(eventRoomSaid, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageRoom.OnRoomSaid", err)
					}
				case strings.HasPrefix(msg.Subject, EvSubjPrefRoomBroadcast):
					eventRoomBroadcast = app.EventRoomBroadcast{}
					if err := json.Unmarshal(msg.Data, &eventRoomBroadcast); err != nil {
						s.LogErr("unmarshaling EventRoomBroadcast JSON", err)
						continue
					}
					if err := p.OnRoomBroadcast(eventRoomBroadcast, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageRoom.OnRoomBroadcast", err)
					}
				}
			}
		})
}

func (s *Server) handlePageRoomPOSTSay(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.checkIsDSReq(w, r) {
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		Room string `json:"room"`
		Text string `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.httpErrBad(w, "reading signals", err)
		return
	}

	dispatchRoomSaid := dispatcherEventRoomSaid{s: s, ctx: r.Context()}
	p := app.PageRoom{
		App: s.app,
	}
	err := p.POSTSay(r, signals, dispatchRoomSaid)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageRoom.Say", err)
		return
	}
}

func (s *Server) handlePageRoomPOSTBroadcast(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.checkIsDSReq(w, r) {
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		Rooms []string `json:"rooms"`
		Text  string   `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.httpErrBad(w, "reading signals", err)
		return
	}

	dispatchRoomBroadcast := dispatcherEventRoomBroadcast{s: s, ctx: r.Context()}
	p := app.PageRoom{
		App: s.app,
	}
	err := p.POSTBroadcast(r, signals, dispatchRoomBroadcast)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageRoom.Broadcast", err)
		return
	}
}

type dispatcherEventStreamGone struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventStreamGone) Dispatch(e app.EventStreamGone) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventStreamGone) DispatchCtx(
	ctx context.Context, e app.EventStreamGone,
) error {
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventStreamGone JSON: %w", err)
	}
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, EvSubjStreamGone, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", EvSubjStreamGone, err)
	}
	return nil
}

type dispatcherEventNote struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventNote) Dispatch(e app.EventNote) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventNote) DispatchCtx(
	ctx context.Context, e app.EventNote,
) error {
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventNote JSON: %w", err)
	}
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, EvSubjNote, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", EvSubjNote, err)
	}
	return nil
}

type dispatcherEventTick struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventTick) Dispatch(e app.EventTick) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventTick) DispatchCtx(
	ctx context.Context, e app.EventTick,
) error {
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventTick JSON: %w", err)
	}
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, EvSubjTick, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", EvSubjTick, err)
	}
	return nil
}

type dispatcherEventPong struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventPong) Dispatch(e app.EventPong) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventPong) DispatchCtx(
	ctx context.Context, e app.EventPong,
) error {
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventPong JSON: %w", err)
	}
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, EvSubjPong, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", EvSubjPong, err)
	}
	return nil
}

type dispatcherEventRoomSaid struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventRoomSaid) Dispatch(e app.EventRoomSaid) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventRoomSaid) DispatchCtx(
	ctx context.Context, e app.EventRoomSaid,
) error {
	if !subject.IsToken(string(e.Room)) {
		return fmt.Errorf(
			"EventRoomSaid.Room must be a non-empty subject token, received %q",
			e.Room)
	}
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventRoomSaid JSON: %w", err)
	}
	subj := "room.said." + string(e.Room)
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, subj, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", subj, err)
	}
	return nil
}

type dispatcherEventRoomBroadcast struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventRoomBroadcast) Dispatch(e app.EventRoomBroadcast) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventRoomBroadcast) DispatchCtx(
	ctx context.Context, e app.EventRoomBroadcast,
) error {
	if !subject.IsToken(string(e.Room)) {
		return fmt.Errorf(
			"EventRoomBroadcast.Room must be a non-empty subject token, received %q",
			e.Room)
	}
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventRoomBroadcast JSON: %w", err)
	}
	subj := "room.broadcast." + string(e.Room)
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, subj, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", subj, err)
	}
	return nil
}
