// Code generated by github.com/romshark/datapages; DO NOT EDIT.

// Package action provides generators for datastar action attribute expressions.
// Use these in templates instead of hardcoding action URLs.
package action

import (
	"net/url"
	"strings"

	"github.com/romshark/datapages/runtime/actionexpr"
)

// The generated helpers take the options of runtime/actionexpr.
// Aliases keep them nameable from a template that imports only this package.
type (
	option              = actionexpr.Option
	ContentType         = actionexpr.ContentType
	Retry               = actionexpr.Retry
	RequestCancellation = actionexpr.RequestCancellation
)

const (
	// ContentTypeJSON sends all signals in a JSON request (default).
	ContentTypeJSON = actionexpr.ContentTypeJSON
	// ContentTypeForm looks for the closest form to the element,
	// performs validation on form elements, and sends them as a form request.
	// No signals are sent. Use WithSelector to target a specific form.
	ContentTypeForm = actionexpr.ContentTypeForm

	// RetryAuto retries on network errors only (default).
	RetryAuto = actionexpr.RetryAuto
	// RetryError retries on 4xx and 5xx responses.
	RetryError = actionexpr.RetryError
	// RetryAlways retries on all non-204 responses except redirects.
	RetryAlways = actionexpr.RetryAlways
	// RetryNever disables retries.
	RetryNever = actionexpr.RetryNever

	// RequestCancellationAuto cancels existing requests on the same element (default).
	RequestCancellationAuto = actionexpr.RequestCancellationAuto
	// RequestCancellationCleanup cancels existing requests on the same element
	// and on element or attribute cleanup.
	RequestCancellationCleanup = actionexpr.RequestCancellationCleanup
	// RequestCancellationDisabled allows concurrent requests.
	RequestCancellationDisabled = actionexpr.RequestCancellationDisabled
)

// WithOption creates an action option key-value pair.
// The key is an option name and the value is a raw JavaScript expression.
//
// WARNING: Use WithOption only when no typed helper is available.
// Typed helpers provide compile-time safety:
//   - WithContentType
//   - WithFilterSignals
//   - WithHeaders
//   - WithOpenWhenHidden
//   - WithPayload
//   - WithSelector
//   - WithRetry
//   - WithRetryInterval
//   - WithRetryScaler
//   - WithRetryMaxWaitMs
//   - WithRetryMaxCount
//   - WithRequestCancellation
//   - WithRequestCancellationController
//
// See https://data-star.dev/reference/actions#options
func WithOption(key, value string) option {
	return actionexpr.WithOption(key, value)
}

// WithBefore prepends a JavaScript expression before the action call.
// Multiple before expressions are joined with "; " separators.
func WithBefore(expr string) option { return actionexpr.WithBefore(expr) }

// WithAfter appends a JavaScript expression after the action call.
// Multiple after expressions are joined with "; " separators.
func WithAfter(expr string) option { return actionexpr.WithAfter(expr) }

// WithContentType creates an action option that controls the content type:
//   - ContentTypeJSON (default)
//   - ContentTypeForm
func WithContentType(ct ContentType) option {
	return actionexpr.WithContentType(ct)
}

// WithFilterSignals creates an action option with a regex pattern to match
// signal paths to include. If exclude is non-empty, it specifies a regex
// pattern to exclude. Defaults to include all (/.*/), exclude signals
// with a _ prefix (/(^_|\._).*/).
//
// See https://data-star.dev/reference/actions#options
func WithFilterSignals(include, exclude string) option {
	return actionexpr.WithFilterSignals(include, exclude)
}

// WithHeaders creates an action option with HTTP headers to send with the request.
func WithHeaders(headers map[string]string) option {
	return actionexpr.WithHeaders(headers)
}

// WithOpenWhenHidden creates an action option that controls whether to keep
// the connection open when the page is hidden. Useful for dashboards but can
// cause a drain on battery life. Defaults to false for get requests,
// and true for all other HTTP methods.
func WithOpenWhenHidden(open bool) option {
	return actionexpr.WithOpenWhenHidden(open)
}

// WithPayload creates an action option with a JavaScript expression
// for the request payload.
func WithPayload(expr string) option { return actionexpr.WithPayload(expr) }

// WithSelector creates an action option that specifies a CSS selector for
// the form to send when ContentType is ContentTypeForm.
// If not specified, the closest form to the element is used.
func WithSelector(selector string) option {
	return actionexpr.WithSelector(selector)
}

// WithRetry creates an action option that determines when to retry requests:
//   - RetryAuto (default)
//   - RetryError
//   - RetryAlways
//   - RetryNever
func WithRetry(r Retry) option { return actionexpr.WithRetry(r) }

// WithRetryInterval creates an action option for the retry interval in milliseconds.
// Defaults to 1000 (one second).
func WithRetryInterval(ms int) option {
	return actionexpr.WithRetryInterval(ms)
}

// WithRetryScaler creates an action option for the numeric multiplier
// applied to scale retry wait times. Defaults to 2.
func WithRetryScaler(multiplier float64) option {
	return actionexpr.WithRetryScaler(multiplier)
}

// WithRetryMaxWaitMs creates an action option for the maximum allowable wait time
// in milliseconds between retries. Defaults to 30000 (30 seconds).
func WithRetryMaxWaitMs(ms int) option {
	return actionexpr.WithRetryMaxWaitMs(ms)
}

// WithRetryMaxCount creates an action option for the maximum number
// of retry attempts. Defaults to 10.
func WithRetryMaxCount(count int) option {
	return actionexpr.WithRetryMaxCount(count)
}

// WithRequestCancellation creates an action option that controls
// request cancellation behavior:
//   - RequestCancellationAuto (default)
//   - RequestCancellationCleanup
//   - RequestCancellationDisabled
func WithRequestCancellation(rc RequestCancellation) option {
	return actionexpr.WithRequestCancellation(rc)
}

// WithRequestCancellationController creates an action option that uses
// a JavaScript AbortController expression for custom request cancellation.
// The expression should reference a signal holding an AbortController instance,
// for example "$controller".
//
// See https://data-star.dev/reference/actions#request-cancellation
func WithRequestCancellationController(expr string) option {
	return actionexpr.WithRequestCancellationController(expr)
}

// POSTPageItemRename references /item/{name}/rename/
func POSTPageItemRename(name string, query QueryPOSTPageItemRename, options ...option) string {
	s_name := url.PathEscape(name)
	var (
		toStr string
	)

	if query.To != "" {
		toStr = url.QueryEscape(query.To)
	}

	anyQuery := query.To != ""

	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	l := bl + len("@post('/item/") + len(s_name) + len("/rename/") + len("'") + actionexpr.OptionsLen(options) + len(")") + al
	if anyQuery {
		l += len("?")
	}
	n := 0
	if query.To != "" {
		if n > 0 {
			l += len("&")
		}
		l += len("to=") + len(toStr)
	}

	b.Grow(l)

	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/item/")
	b.WriteString(s_name)
	b.WriteString("/rename/")
	if anyQuery {
		b.WriteString("?")
	}
	n = 0
	if query.To != "" {
		if n > 0 {
			b.WriteString("&")
		}
		b.WriteString("to=")
		b.WriteString(toStr)
	}
	b.WriteString("'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)

	return b.String()
}

type QueryPOSTPageItemRename struct {
	To string `query:"to"`
}
