// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"runtime/debug"
	"strings"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/actionexpr"
	"github.com/romshark/datapages/runtime/auth"
	"github.com/romshark/datapages/runtime/htmlattr"
	"github.com/romshark/datapages/runtime/httpserve"
	dpsse "github.com/romshark/datapages/runtime/sse"
	"github.com/romshark/datapages/runtime/stream"
	"github.com/romshark/datapages/runtime/subject"

	dpapp "github.com/romshark/datapages/internal/acceptance/anonstreams/app"
	"github.com/romshark/datapages/internal/acceptance/anonstreams/app/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

const DefaultBodySizeLimit = httpserve.DefaultBodySizeLimit

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	sess datapages.Session[struct{}],
	headGeneric, head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	return s.Core.WriteHTML(w, r, httpserve.HTMLDocument{
		CSRF:            s.Manager,
		UserID:          sess.UserID(),
		SessionToken:    sess.Token(),
		HeadGeneric:     headGeneric,
		Head:            head,
		Body:            body,
		WriteBodyAttrs:  writeBodyAttrs,
		WriteBodySuffix: writeBodySuffix,
	})
}

func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request, sessKey string, sess datapages.Session[struct{}],
	subjects []string,
	onOpen func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
	) error,
	onClose func(streamID datapages.StreamID),
	fn func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
		ch <-chan messaging.Message,
	),
) {
	s.streams.Handle(w, r, sessKey, sess.UserID(), subjects, onOpen, onClose, fn)
}

// recoverPanic turns a panicking handler into an error and hands it to the error path.
func (s *Server) recoverPanic(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, handler string,
) {
	v := recover()
	if v == nil {
		return
	}
	stack := debug.Stack()
	s.Logger().Error("recovered panic",
		slog.String("handler", handler),
		slog.Any("panic", v),
		slog.String("stack", string(stack)))
	s.httpErrIntern(w, r, sse, "panic in "+handler,
		datapages.PanicError{Value: v, Stack: stack})
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics messaging.NoopMetrics
	streams              *stream.Handler
	app                  *dpapp.App
	*auth.Manager[struct{}]
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[dpapp.App, struct{}, datapages.DisablePrometheus, Server](
//		app, broker, opts...,
//	)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithLogSampling
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
//   - datapages.WithSessionManager (required)
//   - datapages.WithSessions
//   - datapages.WithCSRFProtection
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *dpapp.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[struct{}],
) error {
	if cfg.Prometheus != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}
	if sessionManager == nil {
		return errors.New("missing option WithSessionManager")
	}

	assetsFS, err := httpserve.AssetsFileSystem(cfg, "", "")
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core, err = httpserve.NewCore(cfg, "")
	if err != nil {
		return err
	}
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = messaging.NoopMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}
	s.Manager = auth.NewManager(s.Core, sessionManager, cfg, nil)
	s.streams = stream.NewHandler(
		s.Core, messageBroker, s.messageBrokerMetrics,
		s.SessionManager(),
		nil,
		s.httpErrIntern,
	)

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.SampledLogger())
	actionexpr.SetLogger(s.SampledLogger())

	return nil
}

const (
	EvSubjDMed    = "dmed.*.*"
	EvSubjNoticed = "noticed.*"

	// Public events:

	EvSubjRoomPosted = "room.posted.*"
	EvSubjTicked     = "ticked"
)

const (
	EvPrefixDMed       = "dmed."
	EvPrefixNoticed    = "noticed."
	EvPrefixRoomPosted = "room.posted."
)

func MessageBrokerStreamSubjects() []string {
	return []string{
		EvSubjDMed,
		EvSubjNoticed,
		EvSubjRoomPosted,
		EvSubjTicked,
	}
}

func evSubjPageFeed(userID string) []string {
	if userID == "" {
		return []string{
			EvSubjTicked,
		}
	}
	return []string{
		EvSubjTicked,
		"noticed." + subject.Encode(userID),
	}
}

func evSubjPagePost(userID string) []string {
	if userID == "" {
		return []string{
			EvSubjTicked,
		}
	}
	return []string{
		EvSubjTicked,
		"noticed." + subject.Encode(userID),
	}
}

func evSubjPageRooms(userID string, subjRoom string) []string {
	if userID == "" {
		return []string{
			"room.posted." + subject.Encode(subjRoom),
		}
	}
	return []string{
		"noticed." + subject.Encode(userID),
		"dmed." + subject.Encode(userID) + ".*",
		"room.posted." + subject.Encode(subjRoom),
	}
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /feed/{$}",
		pageFeedHandlers{s}.GET)
	s.Mux().HandleFunc(
		"GET /feed/_$/{$}",
		pageFeedHandlers{s}.GETStream)
	s.Mux().HandleFunc(
		"GET /feed/_$/anon/{$}",
		pageFeedHandlers{s}.GETStreamAnon)
	s.Mux().HandleFunc(
		"GET /",
		pageIndexHandlers{s}.GET)
	s.Mux().HandleFunc(
		"GET /post/{slug}/{$}",
		pagePostHandlers{s}.GET)
	s.Mux().HandleFunc(
		"GET /post/{slug}/_$/{$}",
		pagePostHandlers{s}.GETStream)
	s.Mux().HandleFunc(
		"GET /post/{slug}/_$/anon/{$}",
		pagePostHandlers{s}.GETStreamAnon)
	s.Mux().HandleFunc(
		"GET /rooms/{$}",
		pageRoomsHandlers{s}.GET)
	s.Mux().HandleFunc(
		"GET /rooms/_$/{$}",
		pageRoomsHandlers{s}.GETStream)
	s.Mux().HandleFunc(
		"GET /rooms/_$/anon/{$}",
		pageRoomsHandlers{s}.GETStreamAnon)
	s.Mux().HandleFunc(
		"POST /feed/tick/{$}",
		pageFeedHandlers{s}.POSTTick)
	s.Mux().HandleFunc(
		"POST /rooms/post/{$}",
		pageRoomsHandlers{s}.POSTPost)
	s.Mux().HandleFunc(
		"POST /rooms/notice/{$}",
		pageRoomsHandlers{s}.POSTNotice)
	s.Mux().HandleFunc(
		"POST /rooms/dm/{$}",
		pageRoomsHandlers{s}.POSTDM)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	sse *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	if sse != nil {
		// The stream is open, hence no status is left to send.
		return
	}
	if httpserve.ResponseBodyWritten(w) {
		// A status written now only appends its text to the body.
		return
	}
	httpserve.WriteErrStatus(w, err)
}

type pageFeedHandlers struct{ *Server }

func (s pageFeedHandlers) GET(w http.ResponseWriter, r *http.Request) {
	p := dpapp.PageFeed{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageFeed.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageFeed.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {
	}

	if err := s.writeHTML(
		w, r, datapages.Session[struct{}]{}, genericHead, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageFeed", err)
		return
	}
}

func (s pageFeedHandlers) GETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	sess, sessToken, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if sess.UserID() == "" {
		// The query carries the signals a stream subscribes by,
		// which the anonymous route needs as much as this one.
		// EscapedPath, not the decoded Path: a value carrying "?" or "#" re-parses
		// in the Location header as a query or a fragment.
		target := r.URL.EscapedPath() + "anon/"
		if r.URL.RawQuery != "" {
			target += "?" + r.URL.RawQuery
		}
		http.Redirect(w, r, target, http.StatusSeeOther)
		return
	}

	p := dpapp.PageFeed{
		App: s.app,
	}
	s.handleStreamRequest(w, r, sessToken, sess, evSubjPageFeed(sess.UserID()),
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			defer s.recoverPanic(w, r, sse, "PageFeed stream")
			var eventTicked dpapp.EventTicked
			var eventNoticed dpapp.EventNoticed
			for msg := range ch {
				switch {
				case msg.Subject == EvSubjTicked:
					eventTicked = dpapp.EventTicked{}
					if err := json.Unmarshal(msg.Data, &eventTicked); err != nil {
						s.LogErr("unmarshaling EventTicked JSON", err)
						continue
					}
					if err := p.OnTicked(eventTicked, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageFeed.OnTicked", err)
					}
				case strings.HasPrefix(msg.Subject, EvPrefixNoticed):
					eventNoticed = dpapp.EventNoticed{}
					if err := json.Unmarshal(msg.Data, &eventNoticed); err != nil {
						s.LogErr("unmarshaling EventNoticed JSON", err)
						continue
					}
					if err := p.OnNoticed(eventNoticed, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageFeed.OnNoticed", err)
					}
				}
			}
		})
}

func (s pageFeedHandlers) GETStreamAnon(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	sess, sessToken, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if sess.UserID() != "" {
		s.HTTPErrBad(w, "authenticated client on anonymous stream", nil)
		return
	}

	p := dpapp.PageFeed{
		App: s.app,
	}
	s.handleStreamRequest(w, r, sessToken, sess, evSubjPageFeed(sess.UserID()),
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventTicked dpapp.EventTicked
			for msg := range ch {
				switch msg.Subject {
				case EvSubjTicked:
					eventTicked = dpapp.EventTicked{}
					if err := json.Unmarshal(msg.Data, &eventTicked); err != nil {
						s.LogErr("unmarshaling EventTicked JSON", err)
						continue
					}
					if err := p.OnTicked(eventTicked, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageFeed.OnTicked", err)
					}
				}
			}
		})
}

func (s pageFeedHandlers) POSTTick(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	// The CSRF token comes from the cookie, hence no store read here.
	if !s.CheckCSRFOnly(w, r) {
		return
	}
	httpserve.LimitRequestBody(w, r, s.BodySizeLimit())
	var signals datapages.Signals[struct {
		N int `json:"n"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}

	dispatchTicked := dispatcherEventTicked{s: s.Server, ctx: r.Context()}
	defer s.recoverPanic(w, r, nil, "PageFeed.Tick")
	p := dpapp.PageFeed{
		App: s.app,
	}
	err := p.POSTTick(r, signals, dispatchTicked)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageFeed.Tick", err)
		return
	}
}

type pageIndexHandlers struct{ *Server }

func (s pageIndexHandlers) GET(w http.ResponseWriter, r *http.Request) {
	sess, _, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	p := dpapp.PageIndex{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageIndex.GET")
	body, err := p.GET(r, sess)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, sess, genericHead, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

type pagePostHandlers struct{ *Server }

func (s pagePostHandlers) GET(w http.ResponseWriter, r *http.Request) {
	sess, _, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	var path datapages.Path[struct {
		Slug string `path:"slug"`
	}]
	path.Values.Slug = r.PathValue("slug")

	p := dpapp.PagePost{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PagePost.GET")
	body, err := p.GET(r, path, sess)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PagePost.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('`)
		_, _ = io.WriteString(w, `/post/`)
		htmlattr.WritePathValue(w, path.Values.Slug)
		_, _ = io.WriteString(w, `/`)
		if sess.UserID() != "" {
			_, _ = io.WriteString(w, `_$/')"`)
		} else {
			_, _ = io.WriteString(w, `_$/anon/')"`)
		}
	}

	if err := s.writeHTML(
		w, r, sess, genericHead, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PagePost", err)
		return
	}
}

func (s pagePostHandlers) GETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	sess, sessToken, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if sess.UserID() == "" {
		// The query carries the signals a stream subscribes by,
		// which the anonymous route needs as much as this one.
		// EscapedPath, not the decoded Path: a value carrying "?" or "#" re-parses
		// in the Location header as a query or a fragment.
		target := r.URL.EscapedPath() + "anon/"
		if r.URL.RawQuery != "" {
			target += "?" + r.URL.RawQuery
		}
		http.Redirect(w, r, target, http.StatusSeeOther)
		return
	}

	p := dpapp.PagePost{
		App: s.app,
	}
	s.handleStreamRequest(w, r, sessToken, sess, evSubjPagePost(sess.UserID()),
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			defer s.recoverPanic(w, r, sse, "PagePost stream")
			var eventTicked dpapp.EventTicked
			var eventNoticed dpapp.EventNoticed
			for msg := range ch {
				switch {
				case msg.Subject == EvSubjTicked:
					eventTicked = dpapp.EventTicked{}
					if err := json.Unmarshal(msg.Data, &eventTicked); err != nil {
						s.LogErr("unmarshaling EventTicked JSON", err)
						continue
					}
					if err := p.OnTicked(eventTicked, dpsse.New(sse)); err != nil {
						s.LogErr("handling PagePost.OnTicked", err)
					}
				case strings.HasPrefix(msg.Subject, EvPrefixNoticed):
					eventNoticed = dpapp.EventNoticed{}
					if err := json.Unmarshal(msg.Data, &eventNoticed); err != nil {
						s.LogErr("unmarshaling EventNoticed JSON", err)
						continue
					}
					if err := p.OnNoticed(eventNoticed, dpsse.New(sse)); err != nil {
						s.LogErr("handling PagePost.OnNoticed", err)
					}
				}
			}
		})
}

func (s pagePostHandlers) GETStreamAnon(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	sess, sessToken, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if sess.UserID() != "" {
		s.HTTPErrBad(w, "authenticated client on anonymous stream", nil)
		return
	}

	p := dpapp.PagePost{
		App: s.app,
	}
	s.handleStreamRequest(w, r, sessToken, sess, evSubjPagePost(sess.UserID()),
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventTicked dpapp.EventTicked
			for msg := range ch {
				switch msg.Subject {
				case EvSubjTicked:
					eventTicked = dpapp.EventTicked{}
					if err := json.Unmarshal(msg.Data, &eventTicked); err != nil {
						s.LogErr("unmarshaling EventTicked JSON", err)
						continue
					}
					if err := p.OnTicked(eventTicked, dpsse.New(sse)); err != nil {
						s.LogErr("handling PagePost.OnTicked", err)
					}
				}
			}
		})
}

type pageRoomsHandlers struct{ *Server }

func (s pageRoomsHandlers) GET(w http.ResponseWriter, r *http.Request) {
	p := dpapp.PageRooms{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageRooms.GET")
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageRooms.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {
	}

	if err := s.writeHTML(
		w, r, datapages.Session[struct{}]{}, genericHead, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageRooms", err)
		return
	}
}

func (s pageRoomsHandlers) GETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	sess, sessToken, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if sess.UserID() == "" {
		// The query carries the signals a stream subscribes by,
		// which the anonymous route needs as much as this one.
		// EscapedPath, not the decoded Path: a value carrying "?" or "#" re-parses
		// in the Location header as a query or a fragment.
		target := r.URL.EscapedPath() + "anon/"
		if r.URL.RawQuery != "" {
			target += "?" + r.URL.RawQuery
		}
		http.Redirect(w, r, target, http.StatusSeeOther)
		return
	}

	var subjSignals struct {
		Room string `json:"room"`
	}
	if err := datastar.ReadSignals(r, &subjSignals); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}
	if subjSignals.Room == "" {
		s.HTTPErrBad(w, "invalid signal",
			fmt.Errorf("signal %q must not be empty", "room"))
		return
	}

	p := dpapp.PageRooms{
		App: s.app,
	}
	s.handleStreamRequest(w, r, sessToken, sess, evSubjPageRooms(sess.UserID(), subjSignals.Room),
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			defer s.recoverPanic(w, r, sse, "PageRooms stream")
			var eventRoomPosted dpapp.EventRoomPosted
			var eventNoticed dpapp.EventNoticed
			var eventDMed dpapp.EventDMed
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvPrefixRoomPosted):
					eventRoomPosted = dpapp.EventRoomPosted{}
					if err := json.Unmarshal(msg.Data, &eventRoomPosted); err != nil {
						s.LogErr("unmarshaling EventRoomPosted JSON", err)
						continue
					}
					if err := p.OnRoomPosted(eventRoomPosted, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageRooms.OnRoomPosted", err)
					}
				case strings.HasPrefix(msg.Subject, EvPrefixNoticed):
					eventNoticed = dpapp.EventNoticed{}
					if err := json.Unmarshal(msg.Data, &eventNoticed); err != nil {
						s.LogErr("unmarshaling EventNoticed JSON", err)
						continue
					}
					if err := p.OnNoticed(eventNoticed, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageRooms.OnNoticed", err)
					}
				case strings.HasPrefix(msg.Subject, EvPrefixDMed):
					eventDMed = dpapp.EventDMed{}
					if err := json.Unmarshal(msg.Data, &eventDMed); err != nil {
						s.LogErr("unmarshaling EventDMed JSON", err)
						continue
					}
					if err := p.OnDMed(eventDMed, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageRooms.OnDMed", err)
					}
				}
			}
		})
}

func (s pageRoomsHandlers) GETStreamAnon(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	sess, sessToken, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if sess.UserID() != "" {
		s.HTTPErrBad(w, "authenticated client on anonymous stream", nil)
		return
	}

	var subjSignals struct {
		Room string `json:"room"`
	}
	if err := datastar.ReadSignals(r, &subjSignals); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}
	if subjSignals.Room == "" {
		s.HTTPErrBad(w, "invalid signal",
			fmt.Errorf("signal %q must not be empty", "room"))
		return
	}

	p := dpapp.PageRooms{
		App: s.app,
	}
	s.handleStreamRequest(w, r, sessToken, sess, evSubjPageRooms(sess.UserID(), subjSignals.Room),
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventRoomPosted dpapp.EventRoomPosted
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvPrefixRoomPosted):
					eventRoomPosted = dpapp.EventRoomPosted{}
					if err := json.Unmarshal(msg.Data, &eventRoomPosted); err != nil {
						s.LogErr("unmarshaling EventRoomPosted JSON", err)
						continue
					}
					if err := p.OnRoomPosted(eventRoomPosted, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageRooms.OnRoomPosted", err)
					}
				}
			}
		})
}

func (s pageRoomsHandlers) POSTPost(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	// The CSRF token comes from the cookie, hence no store read here.
	if !s.CheckCSRFOnly(w, r) {
		return
	}
	httpserve.LimitRequestBody(w, r, s.BodySizeLimit())
	var signals datapages.Signals[struct {
		Room string `json:"room"`
		Text string `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}

	dispatchRoomPosted := dispatcherEventRoomPosted{s: s.Server, ctx: r.Context()}
	defer s.recoverPanic(w, r, nil, "PageRooms.Post")
	p := dpapp.PageRooms{
		App: s.app,
	}
	err := p.POSTPost(r, signals, dispatchRoomPosted)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageRooms.Post", err)
		return
	}
}

func (s pageRoomsHandlers) POSTNotice(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	// The CSRF token comes from the cookie, hence no store read here.
	if !s.CheckCSRFOnly(w, r) {
		return
	}
	httpserve.LimitRequestBody(w, r, s.BodySizeLimit())
	var signals datapages.Signals[struct {
		User string `json:"user"`
		Text string `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}

	dispatchNoticed := dispatcherEventNoticed{s: s.Server, ctx: r.Context()}
	defer s.recoverPanic(w, r, nil, "PageRooms.Notice")
	p := dpapp.PageRooms{
		App: s.app,
	}
	err := p.POSTNotice(r, signals, dispatchNoticed)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageRooms.Notice", err)
		return
	}
}

func (s pageRoomsHandlers) POSTDM(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	// The CSRF token comes from the cookie, hence no store read here.
	if !s.CheckCSRFOnly(w, r) {
		return
	}
	httpserve.LimitRequestBody(w, r, s.BodySizeLimit())
	var signals datapages.Signals[struct {
		To   string `json:"to"`
		Cc   string `json:"cc"`
		Text string `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}

	dispatchDMed := dispatcherEventDMed{s: s.Server, ctx: r.Context()}
	defer s.recoverPanic(w, r, nil, "PageRooms.DM")
	p := dpapp.PageRooms{
		App: s.app,
	}
	err := p.POSTDM(r, signals, dispatchDMed)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageRooms.DM", err)
		return
	}
}

type dispatcherEventTicked struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventTicked) Dispatch(e dpapp.EventTicked) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventTicked) DispatchCtx(
	ctx context.Context, e dpapp.EventTicked,
) error {
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventTicked JSON: %w", err)
	}
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, EvSubjTicked, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", EvSubjTicked, err)
	}
	return nil
}

type dispatcherEventRoomPosted struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventRoomPosted) Dispatch(e dpapp.EventRoomPosted) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventRoomPosted) DispatchCtx(
	ctx context.Context, e dpapp.EventRoomPosted,
) error {
	if e.Room == "" {
		return errors.New("EventRoomPosted.Room must not be empty")
	}
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventRoomPosted JSON: %w", err)
	}
	subj := "room.posted." + subject.Encode(string(e.Room))
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, subj, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", subj, err)
	}
	return nil
}

type dispatcherEventNoticed struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventNoticed) Dispatch(e dpapp.EventNoticed) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventNoticed) DispatchCtx(
	ctx context.Context, e dpapp.EventNoticed,
) error {
	if e.Recipient == "" {
		return errors.New("EventNoticed.Recipient must not be empty")
	}
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventNoticed JSON: %w", err)
	}
	subj := "noticed." + subject.Encode(string(e.Recipient))
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, subj, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", subj, err)
	}
	return nil
}

type dispatcherEventDMed struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventDMed) Dispatch(e dpapp.EventDMed) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventDMed) DispatchCtx(
	ctx context.Context, e dpapp.EventDMed,
) error {
	if e.To == "" {
		return errors.New("EventDMed.To must not be empty")
	}
	if e.Cc == "" {
		return errors.New("EventDMed.Cc must not be empty")
	}
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventDMed JSON: %w", err)
	}
	subj := "dmed." + subject.Encode(string(e.To)) + "." + subject.Encode(string(e.Cc))
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, subj, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", subj, err)
	}
	return nil
}
