// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/auth"
	"github.com/romshark/datapages/runtime/httpserve"

	"github.com/romshark/datapages/internal/acceptance/csrfcoverage/app"
	"github.com/romshark/datapages/internal/acceptance/csrfcoverage/app/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

const DefaultBodySizeLimit = 1024 * 1024 // 1 MiB

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	sess datapages.Session[struct{}],
	head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	return s.Core.WriteHTML(w, r, httpserve.HTMLDocument{
		CSRF:            s.Manager,
		UserID:          sess.UserID(),
		SessionToken:    sess.Token(),
		Head:            head,
		Body:            body,
		WriteBodyAttrs:  writeBodyAttrs,
		WriteBodySuffix: writeBodySuffix,
	})
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics messaging.NoopMetrics
	app                  *app.App
	*auth.Manager[struct{}]
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[app.App, struct{}, datapages.DisablePrometheus, Server](app, broker, opts...)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
//   - datapages.WithSessionManager (required)
//   - datapages.WithSessions
//   - datapages.WithCSRFProtection
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *app.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[struct{}],
) error {
	if cfg.Prometheus != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}
	if sessionManager == nil {
		return errors.New("missing option WithSessionManager")
	}

	assetsFS, err := httpserve.AssetsFileSystem(cfg, "", "")
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core, err = httpserve.NewCore(cfg, "")
	if err != nil {
		return err
	}
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = messaging.NoopMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}
	s.Manager = auth.NewManager(s.Core, sessionManager, cfg, nil)

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.Logger())

	return nil
}

const (

// Public events:

)

func MessageBrokerStreamSubjects() []string {
	return []string{}
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /",
		s.handlePageIndexGET)
	s.Mux().HandleFunc(
		"POST /sign-in/{$}",
		s.handlePageIndexPOSTSignIn)
	s.Mux().HandleFunc(
		"POST /delete/{$}",
		s.handlePageIndexPOSTDelete)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	_ *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	httpserve.WriteErrStatus(w, err)
}

func (s *Server) handlePageIndexGET(w http.ResponseWriter, r *http.Request) {
	sess, _, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	p := app.PageIndex{
		App: s.app,
	}
	body, err := p.GET(r, sess)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	if err := s.writeHTML(
		w, r, sess, nil, body, bodyAttrs, nil,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

func (s *Server) handlePageIndexPOSTSignIn(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	// CSRF protection covers every state-changing action, including
	// the ones that read nothing of the session.
	if _, _, ok := s.ReadSession(w, r); !ok {
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		User string `json:"user"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}
	p := app.PageIndex{
		App: s.app,
	}
	newSession, err := p.POSTSignIn(r, signals)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.SignIn", err)
		return
	}
	if j := newSession; j.UserID != "" {
		if err := s.CreateSession(w, r, newSession); err != nil {
			s.httpErrIntern(w, r, nil, "creating session", err)
			return
		}
	}
}

func (s *Server) handlePageIndexPOSTDelete(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	// CSRF protection covers every state-changing action, including
	// the ones that read nothing of the session.
	if _, _, ok := s.ReadSession(w, r); !ok {
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		Confirm bool `json:"confirm"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTDelete(r, signals)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Delete", err)
		return
	}
}
