// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"hash/maphash"
	"io"
	"net/http"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/httpserve"
	dpsse "github.com/romshark/datapages/runtime/sse"
	"github.com/romshark/datapages/runtime/stream"
	"github.com/romshark/datapages/runtime/subject"

	"github.com/romshark/datapages/internal/acceptance/statefulpages/app"
	"github.com/romshark/datapages/internal/acceptance/statefulpages/app/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

const DefaultBodySizeLimit = 1024 * 1024 // 1 MiB

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	headGeneric, head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	return s.Core.WriteHTML(w, r, httpserve.HTMLDocument{
		HeadGeneric: headGeneric,
		WriteHeadPrologue: func(io.Writer) error {
			// The instance id is a bearer credential: presenting it claims a tab's state.
			// The script below closes over the id and then drops its own node.
			// The closure is what the fetch wrapper reads, and no copy is
			// left in the DOM for a later reader to lift, a session replay
			// recorder or an error reporter included. The response body still
			// carries the id, which is what the page's Cache-Control: no-store is for.
			if id := w.Header().Get(stateInstanceIDHeader); s.verifyStateInstanceID(id) {
				if _, err := io.WriteString(w, `<script>(() => {
		let __dpInstance="`); err != nil {
					return err
				}
				if _, err := io.WriteString(w, id); err != nil {
					return err
				}
				if _, err := io.WriteString(w, `"
		document.currentScript?.remove()
		const k="datapages-reloaded:"+location.pathname
		const mark=v => { try { v ? sessionStorage.setItem(k,"1"):sessionStorage.removeItem(k) } catch {} }
		const marked=() => { try { return !!sessionStorage.getItem(k) } catch { return false } }
		const o2 = globalThis.fetch.bind(globalThis)
		globalThis.fetch=(i,init={}) => {
			const isReq=i instanceof Request
			const r=isReq ? i:new Request(i,init)
			if (r.headers.get("Datastar-Request")!=="true" ||
				new URL(r.url,location.href).origin!==location.origin
			) return isReq ? o2(r,init):o2(r)
			const h=new Headers(r.headers)
			if (__dpInstance) h.set("Datapages-Instance",__dpInstance)
			return o2(new Request(r,{...init,headers:h})).then(resp => {
				if (resp.status===409 && resp.headers.get("Datapages-Retry")==="reconnect") {
					__dpInstance=""
					if (!marked()) {
						mark(true)
						location.reload()
					}
				} else if (resp.ok) {
					mark(false)
				}
				return resp
			})
		}
		globalThis.addEventListener("pageshow", e => {
			if (e.persisted) location.reload()
		})
	})()</script>`); err != nil {
					return err
				}
			}
			return nil
		},
		Head:            head,
		Body:            body,
		WriteBodyAttrs:  writeBodyAttrs,
		WriteBodySuffix: writeBodySuffix,
	})
}

func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request,
	subjects []string,
	onOpen func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
	) error,
	onClose func(streamID datapages.StreamID),
	fn func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
		ch <-chan messaging.Message,
	),
) {
	s.streams.Handle(w, r, "", "", subjects, onOpen, onClose, fn)
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics messaging.NoopMetrics
	streams              *stream.Handler
	app                  *app.App

	stateConf *datapages.StateConfig
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[app.App, datapages.DisableSessions, datapages.DisablePrometheus, Server](app, broker, opts...)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *app.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[datapages.DisableSessions],
) error {
	if sessionManager != nil {
		return errors.New("unexpected option WithSessionManager: package app declares no session type")
	}
	if cfg.Prometheus != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}
	if cfg.State == nil {
		return errors.New("missing option WithStateConfig: " +
			"this app has stateful pages")
	}

	assetsFS, err := httpserve.AssetsFileSystem(cfg, "", "")
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core, err = httpserve.NewCore(cfg, "")
	if err != nil {
		return err
	}
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = messaging.NoopMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}
	s.stateConf = cfg.State
	s.streams = stream.NewHandler(
		s.Core, messageBroker, s.messageBrokerMetrics,
		nil,
		nil,
		s.httpErrIntern,
	)

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.Logger())

	return nil
}

const (

	// Public events:

	EvSubjFiltersUpdated = "filters.updated.*"
)

const (
	EvSubjPrefFiltersUpdated = "filters.updated."
)

func MessageBrokerStreamSubjects() []string {
	return []string{
		EvSubjFiltersUpdated,
	}
}

var evSubjPageFailOpen = []string{}

func evSubjPageIndex(stateID string) []string {
	return []string{
		EvSubjPrefFiltersUpdated + stateID,
	}
}

var evSubjPagePanicOnClose = []string{}

// stateInstanceIDHeader is the request/response header used to carry the
// server-issued per-page-instance identifier.
const stateInstanceIDHeader = "Datapages-Instance"

// stateRetryHeader signals the client to reconnect before retrying an
// action that was rejected because no live instance was found.
const stateRetryHeader = "Datapages-Retry"

// stateRetryReconnect is the only value currently emitted on stateRetryHeader.
const stateRetryReconnect = "reconnect"

// stateInstanceIDSep separates payload and signature in a Datapages-Instance value.
// It must not be "." and must not appear in the base64url alphabet:
// the identifier is used verbatim as a single message-broker subject token
// (see the SubjectStateID event routing), and "." would split it in two,
// breaking single-token wildcard matching.
const stateInstanceIDSep = '~'

// stateInstanceIDTag and the tag stateRouteKey writes name what each MAC is for.
// One key, two derivations: without a tag of its own on each,
// a value computed for one of them is a value the other would accept.
var stateInstanceIDTag = []byte("datapages-instance\x00")

// signStateInstanceID produces an HMAC-signed Datapages-Instance value.
// The payload is 16 random bytes; the output is:
// base64url(payload) + "~" + base64url(hmacSHA256(tag, payload)).
func (s *Server) signStateInstanceID() (string, error) {
	if s.stateConf == nil {
		return "", errors.New("state runtime not configured")
	}
	var payload [16]byte
	if _, err := rand.Read(payload[:]); err != nil {
		return "", err
	}
	mac := hmac.New(sha256.New, s.stateConf.HMACKey)
	mac.Write(stateInstanceIDTag)
	mac.Write(payload[:])
	return base64.RawURLEncoding.EncodeToString(payload[:]) +
		string(stateInstanceIDSep) +
		base64.RawURLEncoding.EncodeToString(mac.Sum(nil)), nil
}

// verifyStateInstanceID returns true when the supplied Datapages-Instance
// value is well-formed and signed by the server's HMAC key.
func (s *Server) verifyStateInstanceID(id string) bool {
	if s.stateConf == nil || id == "" {
		return false
	}
	sep := strings.IndexByte(id, stateInstanceIDSep)
	if sep <= 0 || sep == len(id)-1 {
		return false
	}
	payload, err := base64.RawURLEncoding.DecodeString(id[:sep])
	if err != nil {
		return false
	}
	sig, err := base64.RawURLEncoding.DecodeString(id[sep+1:])
	if err != nil {
		return false
	}
	mac := hmac.New(sha256.New, s.stateConf.HMACKey)
	mac.Write(stateInstanceIDTag)
	mac.Write(payload)
	return hmac.Equal(mac.Sum(nil), sig)
}

// stateRouteKey derives the value that names a tab in message broker subjects.
// Subjects travel further than a request does: into broker logs,
// stream storage, traces and metrics. The Datapages-Instance id itself
// stays out of them, since presenting it is what claims a tab's state.
// Knowing the routing key only lets a dispatcher address that tab.
//
// Callers must verify the id first.
func (s *Server) stateRouteKey(id string) string {
	mac := hmac.New(sha256.New, s.stateConf.HMACKey)
	mac.Write([]byte("datapages-route\x00"))
	mac.Write([]byte(id))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil)[:16])
}

// stateLiveInstances counts the instances of every state type.
// Memory is shared between them,
// and so is the budget in datapages.StateConfig.MaxConcurrentInstances.
var stateLiveInstances atomic.Int64

// stateNoInstanceLimit is what a negative MaxConcurrentInstances means:
// no budget at all. The counter is still kept, since releases decrement it
// unconditionally and a configuration is free to change between processes.
func (s *Server) stateNoInstanceLimit() bool {
	return s.stateConf.MaxConcurrentInstances < 0
}

// stateReserveInstance takes one slot out of the budget. It reports false
// when the server is full, which fails the stream open that asked for it.
// An unlimited server serves every caller.
func (s *Server) stateReserveInstance() bool {
	n := stateLiveInstances.Add(1)
	if s.stateNoInstanceLimit() {
		return true
	}
	if n > int64(s.stateConf.MaxConcurrentInstances) {
		stateLiveInstances.Add(-1)
		return false
	}
	return true
}

// stateHasCapacity reports whether the budget has room right now.
// It is a look, not a claim, and callers use it before a stream commits its status line.
// stateReserveInstance is what actually holds the bound.
func (s *Server) stateHasCapacity() bool {
	if s.stateNoInstanceLimit() {
		return true
	}
	return stateLiveInstances.Load() < int64(s.stateConf.MaxConcurrentInstances)
}

// errStateAtCapacity fails a stream open that finds no free instance.
var errStateAtCapacity = errors.New("state instance limit reached")

// stateStoreShards is how many independent maps a stateStore spreads its keys over.
// Instance ids are random, so they distribute evenly,
// and each shard carries its own lock.
const stateStoreShards = 32

// stateStoreSeed randomizes shard selection per process.
var stateStoreSeed = maphash.MakeSeed()

// stateStoreShard is one lock and the keys that belong to it.
type stateStoreShard[S any] struct {
	mu sync.RWMutex
	m  map[string]*S
}

// stateStore maps a verified Datapages-Instance id to the live slot it names.
//
// Every key is written once and deleted once, and none is read after its deletion.
// That is the opposite of what sync.Map is tuned for,
// which is a read-mostly set of stable keys. Sharded plain maps read without a write
// barrier and delete without leaving a tombstone behind.
//
// The zero value is ready to use.
type stateStore[S any] struct {
	shards [stateStoreShards]stateStoreShard[S]
}

func (s *stateStore[S]) shard(id string) *stateStoreShard[S] {
	return &s.shards[maphash.String(stateStoreSeed, id)%stateStoreShards]
}

// Load returns the slot registered under id, or (nil, false).
func (s *stateStore[S]) Load(id string) (*S, bool) {
	sh := s.shard(id)
	sh.mu.RLock()
	slot, ok := sh.m[id]
	sh.mu.RUnlock()
	return slot, ok
}

// Store registers slot under id, replacing whatever was there.
func (s *stateStore[S]) Store(id string, slot *S) {
	sh := s.shard(id)
	sh.mu.Lock()
	if sh.m == nil {
		sh.m = make(map[string]*S)
	}
	sh.m[id] = slot
	sh.mu.Unlock()
}

// CompareAndDelete removes id only while it still names slot.
// A stream can allocate a fresh slot under an id whose predecessor is on its way out,
// and the one leaving must not take the new one with it.
func (s *stateStore[S]) CompareAndDelete(id string, slot *S) bool {
	sh := s.shard(id)
	sh.mu.Lock()
	defer sh.mu.Unlock()
	if sh.m[id] != slot {
		return false
	}
	delete(sh.m, id)
	return true
}

// stateSlotStateFilters holds one instance of StateFilters.
// It is allocated on StreamOpen and dropped on StreamClose.
// An instance lives exactly as long as the stream that created it and
// is never reused: a client that reconnects gets a new one.
type stateSlotStateFilters struct {
	state *app.StateFilters
	mu    sync.Mutex // serializes all stateful handler calls on this instance
	dead  bool       // true once the stream closed and the state was dropped
}

// stateInstancesStateFilters maps a verified Datapages-Instance id to the live slot.
var stateInstancesStateFilters stateStore[stateSlotStateFilters]

// allocateStateFilters allocates a zeroed state value, registers it under id
// and hands it to the SSE stream that asked for it.
// Returns the slot so callers (StreamOpen) can pass the state to the user,
// or nil when the server holds as many instances as it may.
func (s *Server) allocateStateFilters(id string) *stateSlotStateFilters {
	if !s.stateReserveInstance() {
		return nil
	}
	slot := &stateSlotStateFilters{state: new(app.StateFilters)}
	stateInstancesStateFilters.Store(id, slot)
	return slot
}

// lookupStateFilters returns the registered slot for id, or (nil, false)
// when no live instance matches. The id is not HMAC-verified here;
// call verifyStateInstanceID first.
func (s *Server) lookupStateFilters(id string) (*stateSlotStateFilters, bool) {
	return stateInstancesStateFilters.Load(id)
}

// releaseStateFilters drops the slot's state the moment its stream closes.
// Nothing of the instance outlives the stream: a client that
// reconnects opens a new stream and gets a freshly allocated state.
//
// The caller passes the slot it allocated rather than the id alone.
// A tab can hold two streams at once while the server still tears the
// older one down, and the second registers its own slot under the same id.
// Releasing by id would give back whichever slot the map holds now.
//
// Calling this twice on one slot releases it once.
func (s *Server) releaseStateFilters(id string, slot *stateSlotStateFilters) {
	slot.mu.Lock()
	if slot.dead {
		slot.mu.Unlock()
		return
	}
	slot.dead = true
	slot.state = nil
	slot.mu.Unlock()
	// A stream can allocate a fresh slot under this id while this
	// one is on its way out. Drop only the slot this call owns.
	stateInstancesStateFilters.CompareAndDelete(id, slot)
	stateLiveInstances.Add(-1)
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /failopen/{$}",
		s.handlePageFailOpenGET)
	s.Mux().HandleFunc(
		"GET /failopen/_$/{$}",
		s.handlePageFailOpenGETStream)
	s.Mux().HandleFunc(
		"GET /",
		s.handlePageIndexGET)
	s.Mux().HandleFunc(
		"GET /_$/{$}",
		s.handlePageIndexGETStream)
	s.Mux().HandleFunc(
		"GET /panicclose/{$}",
		s.handlePagePanicOnCloseGET)
	s.Mux().HandleFunc(
		"GET /panicclose/_$/{$}",
		s.handlePagePanicOnCloseGETStream)
	s.Mux().HandleFunc(
		"POST /update/{$}",
		s.handlePageIndexPOSTUpdate)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	_ *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	httpserve.WriteErrStatus(w, err)
}

func (s *Server) handlePageFailOpenGET(w http.ResponseWriter, r *http.Request) {

	// Mint the per-instance identifier for this page load.
	// The client echoes this value on action requests and on the SSE
	// stream connect via the Datapages-Instance header.
	instanceID, err := s.signStateInstanceID()
	if err != nil {
		s.httpErrIntern(w, r, nil, "minting state instance", err)
		return
	}
	w.Header().Set(stateInstanceIDHeader, instanceID)
	// The page carries an identifier that stands for one tab's state.
	// A cache that hands it to a second visitor hands over the state.
	w.Header().Set("Cache-Control", "no-store")

	p := app.PageFailOpen{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageFailOpen.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/failopen/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, genericHead, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageFailOpen", err)
		return
	}
}

func (s *Server) handlePageFailOpenGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}

	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	if _, live := s.lookupStateFilters(instanceID); !live && !s.stateHasCapacity() {
		w.Header().Set("Retry-After", "5")
		http.Error(w,
			http.StatusText(http.StatusServiceUnavailable),
			http.StatusServiceUnavailable)
		return
	}
	var slot *stateSlotStateFilters

	p := app.PageFailOpen{
		App: s.app,
	}
	s.handleStreamRequest(w, r, evSubjPageFailOpen,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			slot = s.allocateStateFilters(instanceID)
			// A stream that gets no slot never opens: the event loop and the
			// close hook run only once this hook has returned nil,
			// which is why neither of them checks again.
			if slot == nil {
				return errStateAtCapacity
			}
			// The close hook is wired up only once this one has returned nil.
			// An open that ends any other way gives the instance back here,
			// since nothing else is left to do it.
			opened := false
			defer func() {
				if !opened {
					s.releaseStateFilters(instanceID, slot)
				}
			}()
			slot.mu.Lock()
			defer slot.mu.Unlock()
			if err := p.StreamOpen(r, streamID, datapages.State[app.StateFilters]{Values: slot.state}); err != nil {
				return err
			}
			opened = true
			return nil
		},
		func(streamID datapages.StreamID) {
			s.releaseStateFilters(instanceID, slot)
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			for range ch {
			}
		})
}

func (s *Server) handlePageIndexGET(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	// Mint the per-instance identifier for this page load.
	// The client echoes this value on action requests and on the SSE
	// stream connect via the Datapages-Instance header.
	instanceID, err := s.signStateInstanceID()
	if err != nil {
		s.httpErrIntern(w, r, nil, "minting state instance", err)
		return
	}
	w.Header().Set(stateInstanceIDHeader, instanceID)
	// The page carries an identifier that stands for one tab's state.
	// A cache that hands it to a second visitor hands over the state.
	w.Header().Set("Cache-Control", "no-store")

	p := app.PageIndex{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, genericHead, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

func (s *Server) handlePageIndexGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}

	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	if _, live := s.lookupStateFilters(instanceID); !live && !s.stateHasCapacity() {
		w.Header().Set("Retry-After", "5")
		http.Error(w,
			http.StatusText(http.StatusServiceUnavailable),
			http.StatusServiceUnavailable)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	var slot *stateSlotStateFilters

	p := app.PageIndex{
		App: s.app,
	}
	s.handleStreamRequest(w, r, evSubjPageIndex(stateID),
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			slot = s.allocateStateFilters(instanceID)
			// A stream that gets no slot never opens: the event loop and the
			// close hook run only once this hook has returned nil,
			// which is why neither of them checks again.
			if slot == nil {
				return errStateAtCapacity
			}
			// The close hook is wired up only once this one has returned nil.
			// An open that ends any other way gives the instance back here,
			// since nothing else is left to do it.
			opened := false
			defer func() {
				if !opened {
					s.releaseStateFilters(instanceID, slot)
				}
			}()
			slot.mu.Lock()
			defer slot.mu.Unlock()
			if err := p.StreamOpen(r, streamID, datapages.State[app.StateFilters]{Values: slot.state}); err != nil {
				return err
			}
			opened = true
			return nil
		},
		func(streamID datapages.StreamID) {
			s.releaseStateFilters(instanceID, slot)
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			var eventFiltersUpdated app.EventFiltersUpdated
			for msg := range ch {
				switch {
				case strings.HasPrefix(msg.Subject, EvSubjPrefFiltersUpdated):
					eventFiltersUpdated = app.EventFiltersUpdated{}
					if err := json.Unmarshal(msg.Data, &eventFiltersUpdated); err != nil {
						s.LogErr("unmarshaling EventFiltersUpdated JSON", err)
						continue
					}
					slot.mu.Lock()
					if slot.dead {
						slot.mu.Unlock()
						continue
					}
					if err := p.OnFiltersUpdated(eventFiltersUpdated, dpsse.New(sse), datapages.State[app.StateFilters]{Values: slot.state}); err != nil {
						s.LogErr("handling PageIndex.OnFiltersUpdated", err)
					}
					slot.mu.Unlock()
				}
			}
		})
}

func (s *Server) handlePageIndexPOSTUpdate(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	slot, ok := s.lookupStateFilters(instanceID)
	if !ok {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	stateID := s.stateRouteKey(instanceID)
	r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)
	var signals datapages.Signals[struct {
		Filter string `json:"filter"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}
	slot.mu.Lock()
	defer slot.mu.Unlock()
	if slot.dead {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}

	dispatchFiltersUpdated := dispatcherEventFiltersUpdated{s: s, ctx: r.Context()}
	p := app.PageIndex{
		App: s.app,
	}
	err := p.POSTUpdate(r, datapages.State[app.StateFilters]{Values: slot.state}, stateID, signals, dispatchFiltersUpdated)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Update", err)
		return
	}
}

func (s *Server) handlePagePanicOnCloseGET(w http.ResponseWriter, r *http.Request) {

	// Mint the per-instance identifier for this page load.
	// The client echoes this value on action requests and on the SSE
	// stream connect via the Datapages-Instance header.
	instanceID, err := s.signStateInstanceID()
	if err != nil {
		s.httpErrIntern(w, r, nil, "minting state instance", err)
		return
	}
	w.Header().Set(stateInstanceIDHeader, instanceID)
	// The page carries an identifier that stands for one tab's state.
	// A cache that hands it to a second visitor hands over the state.
	w.Header().Set("Cache-Control", "no-store")

	p := app.PagePanicOnClose{
		App: s.app,
	}
	body, err := p.GET(r)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PagePanicOnClose.GET", err)
		return
	}
	genericHead := s.app.Head(r)

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/panicclose/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, genericHead, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PagePanicOnClose", err)
		return
	}
}

func (s *Server) handlePagePanicOnCloseGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}

	instanceID := r.Header.Get(stateInstanceIDHeader)
	if !s.verifyStateInstanceID(instanceID) {
		w.Header().Set(stateRetryHeader, stateRetryReconnect)
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
		return
	}
	if _, live := s.lookupStateFilters(instanceID); !live && !s.stateHasCapacity() {
		w.Header().Set("Retry-After", "5")
		http.Error(w,
			http.StatusText(http.StatusServiceUnavailable),
			http.StatusServiceUnavailable)
		return
	}
	var slot *stateSlotStateFilters

	p := app.PagePanicOnClose{
		App: s.app,
	}
	s.handleStreamRequest(w, r, evSubjPagePanicOnClose,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator,
		) error {
			slot = s.allocateStateFilters(instanceID)
			// A stream that gets no slot never opens: the event loop and the
			// close hook run only once this hook has returned nil,
			// which is why neither of them checks again.
			if slot == nil {
				return errStateAtCapacity
			}
			slot.mu.Lock()
			defer slot.mu.Unlock()
			return nil
		},
		func(streamID datapages.StreamID) {
			// Both of these run even when the hook below panics.
			// Deferred calls unwind in reverse, which puts the release after the unlock,
			// and the release takes this same mutex.
			defer s.releaseStateFilters(instanceID, slot)
			slot.mu.Lock()
			defer slot.mu.Unlock()
			if !slot.dead {
				if err := p.StreamClose(r, streamID, datapages.State[app.StateFilters]{Values: slot.state}); err != nil {
					s.LogErr("handling PagePanicOnClose.StreamClose", err)
				}
			}
		},
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			for range ch {
			}
		})
}

type dispatcherEventFiltersUpdated struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventFiltersUpdated) Dispatch(e app.EventFiltersUpdated) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventFiltersUpdated) DispatchCtx(
	ctx context.Context, e app.EventFiltersUpdated,
) error {
	if e.SubjectStateID == "" {
		return errors.New("EventFiltersUpdated.SubjectStateID must not be empty")
	}
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventFiltersUpdated JSON: %w", err)
	}
	subj := "filters.updated." + subject.Encode(string(e.SubjectStateID))
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, subj, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", subj, err)
	}
	return nil
}
