// Code generated by github.com/romshark/datapages; DO NOT EDIT.

// Package action provides generators for datastar action attribute expressions.
// Use these in templates instead of hardcoding action URLs.
package action

import (
	"log/slog"
	"strings"

	"github.com/romshark/datapages/runtime/actionexpr"
)

// Option configures a generated action call. [ContentType], [Retry],
// and [RequestCancellation] constrain values accepted by typed helpers.
type (
	Option              = actionexpr.Option
	ContentType         = actionexpr.ContentType
	Retry               = actionexpr.Retry
	RequestCancellation = actionexpr.RequestCancellation
)

const (
	// ContentTypeJSON sends signals as JSON and is the default.
	ContentTypeJSON = actionexpr.ContentTypeJSON
	// ContentTypeForm validates and sends the closest form without signals.
	// [WithSelector] selects another form.
	ContentTypeForm = actionexpr.ContentTypeForm

	// RetryAuto retries network errors only and is the default.
	RetryAuto = actionexpr.RetryAuto
	// RetryError retries on 4xx and 5xx responses.
	RetryError = actionexpr.RetryError
	// RetryAlways retries on all non-204 responses except redirects.
	RetryAlways = actionexpr.RetryAlways
	// RetryNever disables retries.
	RetryNever = actionexpr.RetryNever

	// RequestCancellationAuto cancels existing requests on
	// the same element and is the default.
	RequestCancellationAuto = actionexpr.RequestCancellationAuto
	// RequestCancellationCleanup cancels existing requests on
	// the same element and on element or attribute cleanup.
	RequestCancellationCleanup = actionexpr.RequestCancellationCleanup
	// RequestCancellationDisabled allows concurrent requests.
	RequestCancellationDisabled = actionexpr.RequestCancellationDisabled
)

// reporter keeps logging and metrics within this generated application.
// A runtime variable would make servers in one process overwrite each other.
var reporter actionexpr.Reporter

// SetLogger sets the logger for invalid options. A nil logger uses
// [slog.Default]. SetLogger is safe for concurrent use.
func SetLogger(l *slog.Logger) { reporter.SetLogger(l) }

// Metrics counts options omitted because their values are invalid.
type Metrics = actionexpr.Metrics

// SetMetrics sets the counter for omitted options. A Prometheus-enabled server
// installs it during initialization. SetMetrics is safe for concurrent use.
func SetMetrics(m Metrics) { reporter.SetMetrics(m) }

// WithOption adds key with a raw JavaScript value. It performs no validation
// or escaping. Use a typed helper when one is available.
//
// See https://data-star.dev/reference/actions#options
//
// Use WithOption only when no typed helper is available.
// Typed helpers provide compile-time safety:
//   - [WithContentType]
//   - [WithFilterSignals]
//   - [WithHeaders]
//   - [WithOpenWhenHidden]
//   - [WithPayload]
//   - [WithSelector]
//   - [WithRetry]
//   - [WithRetryInterval]
//   - [WithRetryScaler]
//   - [WithRetryMaxWaitMs]
//   - [WithRetryMaxCount]
//   - [WithRequestCancellation]
//   - [WithRequestCancellationController]
func WithOption(key, value string) Option {
	return actionexpr.WithOption(key, value)
}

// WithBefore inserts a JavaScript expression before the action call.
// Multiple expressions run in option order, separated by "; ".
func WithBefore(expr string) Option { return actionexpr.WithBefore(expr) }

// WithAfter inserts a JavaScript expression after the action call.
// Multiple expressions run in option order, separated by "; ".
func WithAfter(expr string) Option { return actionexpr.WithAfter(expr) }

// WithContentType sets the request encoding.
// An invalid value is omitted and reported.
func WithContentType(ct ContentType) Option {
	return actionexpr.WithContentType(&reporter, ct)
}

// WithFilterSignals includes signal paths matching include and excludes paths
// matching exclude. Empty arguments use Datastar's defaults. A line terminator
// makes the option invalid; an invalid option is omitted and reported.
//
// See https://data-star.dev/reference/actions#options
func WithFilterSignals(include, exclude string) Option {
	return actionexpr.WithFilterSignals(&reporter, include, exclude)
}

// WithHeaders sets request headers. An empty map emits no option.
func WithHeaders(headers map[string]string) Option {
	return actionexpr.WithHeaders(headers)
}

// WithOpenWhenHidden controls whether the request remains open while the
// page is hidden. Datastar defaults to false for GET and true for other methods.
func WithOpenWhenHidden(open bool) Option {
	return actionexpr.WithOpenWhenHidden(open)
}

// WithPayload sets the request payload to the raw JavaScript expression expr.
func WithPayload(expr string) Option { return actionexpr.WithPayload(expr) }

// WithSelector selects the form sent by [ContentTypeForm].
// Without this option, Datastar uses the closest form.
func WithSelector(selector string) Option {
	return actionexpr.WithSelector(selector)
}

// WithRetry sets the retry policy. An invalid value is omitted and reported.
func WithRetry(r Retry) Option { return actionexpr.WithRetry(&reporter, r) }

// WithRetryInterval sets the initial retry interval in milliseconds.
// The default is 1000. A negative value is omitted and reported.
func WithRetryInterval(ms int) Option {
	return actionexpr.WithRetryInterval(&reporter, ms)
}

// WithRetryScaler sets the multiplier for successive retry intervals.
// The default is 2. An infinite or NaN value is omitted and reported.
func WithRetryScaler(multiplier float64) Option {
	return actionexpr.WithRetryScaler(&reporter, multiplier)
}

// WithRetryMaxWaitMs sets the maximum interval between retries in milliseconds.
// The default is 30_000. A negative value is omitted and reported.
func WithRetryMaxWaitMs(ms int) Option {
	return actionexpr.WithRetryMaxWaitMs(&reporter, ms)
}

// WithRetryMaxCount sets the maximum number of retries.
// The default is 10. A negative value is omitted and reported.
func WithRetryMaxCount(count int) Option {
	return actionexpr.WithRetryMaxCount(&reporter, count)
}

// WithRequestCancellation sets the cancellation policy.
// An invalid value is omitted and reported.
func WithRequestCancellation(rc RequestCancellation) Option {
	return actionexpr.WithRequestCancellation(&reporter, rc)
}

// WithRequestCancellationController sets request cancellation to the raw
// JavaScript AbortController expression expr. It commonly names a signal
// such as "$controller".
//
// See https://data-star.dev/reference/actions#request-cancellation
func WithRequestCancellationController(expr string) Option {
	return actionexpr.WithRequestCancellationController(expr)
}

var App app

type app struct {
	SignOut app_SignOut
}

type app_SignOut struct{}

// POST references /sign-out/
func (app_SignOut) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/sign-out/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/sign-out/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/sign-out/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

var PageIndex pageIndex

type pageIndex struct {
	Render pageIndex_Render
}

type pageIndex_Render struct{}

// POST references /render/
func (pageIndex_Render) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/render/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/render/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/render/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

var PageLogin pageLogin

type pageLogin struct {
	Broadcast    pageLogin_Broadcast
	Notify       pageLogin_Notify
	Rename       pageLogin_Rename
	Submit       pageLogin_Submit
	SubmitInline pageLogin_SubmitInline
}

type pageLogin_Broadcast struct{}

// POST references /login/broadcast/
func (pageLogin_Broadcast) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/login/broadcast/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/login/broadcast/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/login/broadcast/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageLogin_Notify struct{}

// POST references /login/notify/
func (pageLogin_Notify) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/login/notify/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/login/notify/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/login/notify/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageLogin_Rename struct{}

// POST references /login/rename/
func (pageLogin_Rename) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/login/rename/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/login/rename/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/login/rename/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageLogin_Submit struct{}

// POST references /login/submit/
func (pageLogin_Submit) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/login/submit/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/login/submit/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/login/submit/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageLogin_SubmitInline struct{}

// POST references /login/submit-inline/
func (pageLogin_SubmitInline) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/login/submit-inline/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/login/submit-inline/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/login/submit-inline/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}
