// Code generated by github.com/romshark/datapages; DO NOT EDIT.

package datapagesgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"runtime/debug"

	"github.com/romshark/datapages"
	"github.com/romshark/datapages/modules/messaging"
	"github.com/romshark/datapages/modules/sessions"
	"github.com/romshark/datapages/runtime/auth"
	"github.com/romshark/datapages/runtime/httpserve"
	dpsse "github.com/romshark/datapages/runtime/sse"
	"github.com/romshark/datapages/runtime/stream"

	"github.com/romshark/datapages/internal/acceptance/multiapp/app/frontend"
	"github.com/romshark/datapages/internal/acceptance/multiapp/app/frontend/datapagesgen/href"

	"github.com/starfederation/datastar-go/datastar"
)

const (
	DefaultHTTPReadTimeout       = httpserve.DefaultHTTPReadTimeout
	DefaultHTTPReadHeaderTimeout = httpserve.DefaultHTTPReadHeaderTimeout
	DefaultHTTPWriteTimeout      = httpserve.DefaultHTTPWriteTimeout
	DefaultHTTPIdleTimeout       = httpserve.DefaultHTTPIdleTimeout
	DefaultHTTPMaxHeaderBytes    = httpserve.DefaultHTTPMaxHeaderBytes

	// DefaultDatastarJSSrc is the default URL for the Datastar JavaScript bundle.
	DefaultDatastarJSSrc = httpserve.DefaultDatastarJSSrc
)

const DefaultBodySizeLimit = httpserve.DefaultBodySizeLimit

func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
	sess datapages.Session[frontend.SessionData],
	head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
	return s.Core.WriteHTML(w, r, httpserve.HTMLDocument{
		CSRF:            s.Manager,
		UserID:          sess.UserID(),
		SessionToken:    sess.Token(),
		Head:            head,
		Body:            body,
		WriteBodyAttrs:  writeBodyAttrs,
		WriteBodySuffix: writeBodySuffix,
	})
}

func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request,
	subjects []string,
	onOpen func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
	) error,
	onClose func(streamID datapages.StreamID),
	fn func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
		ch <-chan messaging.Message,
	),
) {
	s.streams.Handle(w, r, "", "", subjects, onOpen, onClose, fn)
}

// recoverPanic turns a panicking handler into an error and hands it to the error path.
func (s *Server) recoverPanic(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, handler string,
) {
	v := recover()
	if v == nil {
		return
	}
	stack := debug.Stack()
	s.Logger().Error("recovered panic",
		slog.String("handler", handler),
		slog.Any("panic", v),
		slog.String("stack", string(stack)))
	s.httpErrIntern(w, r, sse, "panic in "+handler,
		datapages.PanicError{Value: v, Stack: stack})
}

type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics messaging.NoopMetrics
	streams              *stream.Handler
	app                  *frontend.App
	*auth.Manager[frontend.SessionData]
}

// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[frontend.App, frontend.SessionData, datapages.DisablePrometheus, Server](
//		app, broker, opts...,
//	)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets
//   - datapages.WithSessionManager (required)
//   - datapages.WithSessions
//   - datapages.WithCSRFProtection
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *frontend.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[frontend.SessionData],
) error {
	if cfg.Prometheus != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}
	if sessionManager == nil {
		return errors.New("missing option WithSessionManager")
	}

	assetsFS, err := httpserve.AssetsFileSystem(cfg, "", "")
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core, err = httpserve.NewCore(cfg, "")
	if err != nil {
		return err
	}
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = messaging.NoopMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}
	s.Manager = auth.NewManager(s.Core, sessionManager, cfg, nil)
	s.streams = stream.NewHandler(
		s.Core, messageBroker, s.messageBrokerMetrics,
		nil,
		nil,
		s.httpErrIntern,
	)

	setupHandlers(s)

	s.Build()
	href.SetLogger(s.Logger())

	return nil
}

const (

	// Public events:

	EvSubjNotice = "notice"
)

func MessageBrokerStreamSubjects() []string {
	return []string{
		EvSubjNotice,
	}
}

var evSubjPageIndex = []string{
	EvSubjNotice,
}

func setupHandlers(s *Server) {
	// Pages
	s.Mux().HandleFunc(
		"GET /",
		s.handlePageIndexGET)
	s.Mux().HandleFunc(
		"GET /_$/{$}",
		s.handlePageIndexGETStream)
	s.Mux().HandleFunc(
		"POST /sign-in/{$}",
		s.handlePageIndexPOSTSignIn)
	s.Mux().HandleFunc(
		"POST /notice/{$}",
		s.handlePageIndexPOSTNotice)
}

func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	_ *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
	if httpserve.ResponseBodyWritten(w) {
		// A status written now only appends its text to the body.
		return
	}
	httpserve.WriteErrStatus(w, err)
}

func (s *Server) handlePageIndexGET(w http.ResponseWriter, r *http.Request) {
	sess, _, ok := s.ReadSession(w, r)
	if !ok {
		return
	}

	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	p := frontend.PageIndex{
		App: s.app,
	}
	defer s.recoverPanic(w, r, nil, "PageIndex.GET")
	body, err := p.GET(r, sess)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling PageIndex.GET", err)
		return
	}

	bodyAttrs := func(w http.ResponseWriter) {
		httpserve.WriteReloadOnVisibility(w)
	}

	bodySuffix := func(w http.ResponseWriter) {

		_, _ = io.WriteString(w, `data-init="@get('/_$/')"`)
	}

	if err := s.writeHTML(
		w, r, sess, nil, body, bodyAttrs, bodySuffix,
	); err != nil {
		s.LogErr("rendering PageIndex", err)
		return
	}
}

func (s *Server) handlePageIndexGETStream(w http.ResponseWriter, r *http.Request) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}

	p := frontend.PageIndex{
		App: s.app,
	}
	s.handleStreamRequest(w, r, evSubjPageIndex,
		nil,
		nil,
		func(
			streamID datapages.StreamID,
			sse *datastar.ServerSentEventGenerator, ch <-chan messaging.Message,
		) {
			defer s.recoverPanic(w, r, sse, "PageIndex stream")
			var eventNotice frontend.EventNotice
			for msg := range ch {
				switch msg.Subject {
				case EvSubjNotice:
					eventNotice = frontend.EventNotice{}
					if err := json.Unmarshal(msg.Data, &eventNotice); err != nil {
						s.LogErr("unmarshaling EventNotice JSON", err)
						continue
					}
					if err := p.OnNotice(eventNotice, dpsse.New(sse)); err != nil {
						s.LogErr("handling PageIndex.OnNotice", err)
					}
				}
			}
		})
}

func (s *Server) handlePageIndexPOSTSignIn(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	// The CSRF token comes from the cookie, hence no store read here.
	if !s.CheckCSRFOnly(w, r) {
		return
	}
	httpserve.LimitRequestBody(w, r, s.BodySizeLimit())
	var signals datapages.Signals[struct {
		User     string `json:"user"`
		Nickname string `json:"nickname"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}
	defer s.recoverPanic(w, r, nil, "PageIndex.SignIn")
	p := frontend.PageIndex{
		App: s.app,
	}
	newSession, redirect, err := p.POSTSignIn(r, signals)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.SignIn", err)
		return
	}
	if j := newSession; j.UserID != "" {
		if err := s.CreateSession(w, r, newSession); err != nil {
			s.httpErrIntern(w, r, nil, "creating session", err)
			return
		}
	}
	if httpserve.Redirect(w, r, redirect) {
		return
	}
}

func (s *Server) handlePageIndexPOSTNotice(
	w http.ResponseWriter, r *http.Request,
) {
	if !s.CheckDatastarRequest(w, r) {
		return
	}
	// The CSRF token comes from the cookie, hence no store read here.
	if !s.CheckCSRFOnly(w, r) {
		return
	}
	httpserve.LimitRequestBody(w, r, s.BodySizeLimit())
	var signals datapages.Signals[struct {
		Text string `json:"text"`
	}]
	if err := datastar.ReadSignals(r, &signals.Values); err != nil {
		s.HTTPErrBad(w, "reading signals", err)
		return
	}

	dispatchNotice := dispatcherEventNotice{s: s, ctx: r.Context()}
	defer s.recoverPanic(w, r, nil, "PageIndex.Notice")
	p := frontend.PageIndex{
		App: s.app,
	}
	err := p.POSTNotice(r, signals, dispatchNotice)
	if err != nil {
		s.httpErrIntern(w, r, nil, "handling action PageIndex.Notice", err)
		return
	}
}

type dispatcherEventNotice struct {
	s   *Server
	ctx context.Context
}

func (d dispatcherEventNotice) Dispatch(e frontend.EventNotice) error {
	return d.DispatchCtx(d.ctx, e)
}

func (d dispatcherEventNotice) DispatchCtx(
	ctx context.Context, e frontend.EventNotice,
) error {
	j, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshaling EventNotice JSON: %w", err)
	}
	err = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, EvSubjNotice, j)
	if err != nil {
		return fmt.Errorf("publishing subject %q: %w", EvSubjNotice, err)
	}
	return nil
}
