// Code generated by github.com/romshark/datapages; DO NOT EDIT.

// Package action provides generators for datastar action attribute expressions.
// Use these in templates instead of hardcoding action URLs.
package action

import (
	"log/slog"
	"net/url"
	"strconv"
	"strings"

	"github.com/romshark/datapages/runtime/actionexpr"
)

// Option configures a generated action call. [ContentType], [Retry],
// and [RequestCancellation] constrain values accepted by typed helpers.
type (
	Option              = actionexpr.Option
	ContentType         = actionexpr.ContentType
	Retry               = actionexpr.Retry
	RequestCancellation = actionexpr.RequestCancellation
)

const (
	// ContentTypeJSON sends signals as JSON and is the default.
	ContentTypeJSON = actionexpr.ContentTypeJSON
	// ContentTypeForm validates and sends the closest form without signals.
	// [WithSelector] selects another form.
	ContentTypeForm = actionexpr.ContentTypeForm

	// RetryAuto retries network errors only and is the default.
	RetryAuto = actionexpr.RetryAuto
	// RetryError retries on 4xx and 5xx responses.
	RetryError = actionexpr.RetryError
	// RetryAlways retries on all non-204 responses except redirects.
	RetryAlways = actionexpr.RetryAlways
	// RetryNever disables retries.
	RetryNever = actionexpr.RetryNever

	// RequestCancellationAuto cancels existing requests on
	// the same element and is the default.
	RequestCancellationAuto = actionexpr.RequestCancellationAuto
	// RequestCancellationCleanup cancels existing requests on
	// the same element and on element or attribute cleanup.
	RequestCancellationCleanup = actionexpr.RequestCancellationCleanup
	// RequestCancellationDisabled allows concurrent requests.
	RequestCancellationDisabled = actionexpr.RequestCancellationDisabled
)

// reporter keeps logging and metrics within this generated application.
// A runtime variable would make servers in one process overwrite each other.
var reporter actionexpr.Reporter

// SetLogger sets the logger for invalid options. A nil logger uses
// [slog.Default]. SetLogger is safe for concurrent use.
func SetLogger(l *slog.Logger) { reporter.SetLogger(l) }

// Metrics counts options omitted because their values are invalid.
type Metrics = actionexpr.Metrics

// SetMetrics sets the counter for omitted options. A Prometheus-enabled server
// installs it during initialization. SetMetrics is safe for concurrent use.
func SetMetrics(m Metrics) { reporter.SetMetrics(m) }

// WithOption adds key with a raw JavaScript value. It performs no validation
// or escaping. Use a typed helper when one is available.
//
// See https://data-star.dev/reference/actions#options
//
// Use WithOption only when no typed helper is available.
// Typed helpers provide compile-time safety:
//   - [WithContentType]
//   - [WithFilterSignals]
//   - [WithHeaders]
//   - [WithOpenWhenHidden]
//   - [WithPayload]
//   - [WithSelector]
//   - [WithRetry]
//   - [WithRetryInterval]
//   - [WithRetryScaler]
//   - [WithRetryMaxWaitMs]
//   - [WithRetryMaxCount]
//   - [WithRequestCancellation]
//   - [WithRequestCancellationController]
func WithOption(key, value string) Option {
	return actionexpr.WithOption(key, value)
}

// WithBefore inserts a JavaScript expression before the action call.
// Multiple expressions run in option order, separated by "; ".
func WithBefore(expr string) Option { return actionexpr.WithBefore(expr) }

// WithAfter inserts a JavaScript expression after the action call.
// Multiple expressions run in option order, separated by "; ".
func WithAfter(expr string) Option { return actionexpr.WithAfter(expr) }

// WithContentType sets the request encoding.
// An invalid value is omitted and reported.
func WithContentType(ct ContentType) Option {
	return actionexpr.WithContentType(&reporter, ct)
}

// WithFilterSignals includes signal paths matching include and excludes paths
// matching exclude. Empty arguments use Datastar's defaults. A line terminator
// makes the option invalid; an invalid option is omitted and reported.
//
// See https://data-star.dev/reference/actions#options
func WithFilterSignals(include, exclude string) Option {
	return actionexpr.WithFilterSignals(&reporter, include, exclude)
}

// WithHeaders sets request headers. An empty map emits no option.
func WithHeaders(headers map[string]string) Option {
	return actionexpr.WithHeaders(headers)
}

// WithOpenWhenHidden controls whether the request remains open while the
// page is hidden. Datastar defaults to false for GET and true for other methods.
func WithOpenWhenHidden(open bool) Option {
	return actionexpr.WithOpenWhenHidden(open)
}

// WithPayload sets the request payload to the raw JavaScript expression expr.
func WithPayload(expr string) Option { return actionexpr.WithPayload(expr) }

// WithSelector selects the form sent by [ContentTypeForm].
// Without this option, Datastar uses the closest form.
func WithSelector(selector string) Option {
	return actionexpr.WithSelector(selector)
}

// WithRetry sets the retry policy. An invalid value is omitted and reported.
func WithRetry(r Retry) Option { return actionexpr.WithRetry(&reporter, r) }

// WithRetryInterval sets the initial retry interval in milliseconds.
// The default is 1000. A negative value is omitted and reported.
func WithRetryInterval(ms int) Option {
	return actionexpr.WithRetryInterval(&reporter, ms)
}

// WithRetryScaler sets the multiplier for successive retry intervals.
// The default is 2. An infinite or NaN value is omitted and reported.
func WithRetryScaler(multiplier float64) Option {
	return actionexpr.WithRetryScaler(&reporter, multiplier)
}

// WithRetryMaxWaitMs sets the maximum interval between retries in milliseconds.
// The default is 30_000. A negative value is omitted and reported.
func WithRetryMaxWaitMs(ms int) Option {
	return actionexpr.WithRetryMaxWaitMs(&reporter, ms)
}

// WithRetryMaxCount sets the maximum number of retries.
// The default is 10. A negative value is omitted and reported.
func WithRetryMaxCount(count int) Option {
	return actionexpr.WithRetryMaxCount(&reporter, count)
}

// WithRequestCancellation sets the cancellation policy.
// An invalid value is omitted and reported.
func WithRequestCancellation(rc RequestCancellation) Option {
	return actionexpr.WithRequestCancellation(&reporter, rc)
}

// WithRequestCancellationController sets request cancellation to the raw
// JavaScript AbortController expression expr. It commonly names a signal
// such as "$controller".
//
// See https://data-star.dev/reference/actions#request-cancellation
func WithRequestCancellationController(expr string) Option {
	return actionexpr.WithRequestCancellationController(expr)
}

var App app

type app struct {
	All  app_All
	Ping app_Ping
}

type app_All struct{}

// DELETE references /all/
func (app_All) DELETE(options ...Option) string {
	if len(options) == 0 {
		return "@delete('/all/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@delete('/all/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@delete('/all/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type app_Ping struct{}

// POST references /ping/
func (app_Ping) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/ping/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/ping/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/ping/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

var PageForm pageForm

type pageForm struct {
	Bump           pageForm_Bump
	Go             pageForm_Go
	GoStream       pageForm_GoStream
	Patch          pageForm_Patch
	PatchAt        pageForm_PatchAt
	Remove         pageForm_Remove
	Render         pageForm_Render
	Replace        pageForm_Replace
	SignalsBad     pageForm_SignalsBad
	SignalsMissing pageForm_SignalsMissing
	SignalsRaw     pageForm_SignalsRaw
	Submit         pageForm_Submit
	Touch          pageForm_Touch
}

type pageForm_Bump struct{}

// POST references /form/{id}/bump/
func (pageForm_Bump) POST(
	id int,
	query pageForm_Bump_POSTQuery,
	options ...Option,
) string {
	s_id := strconv.FormatInt(int64(id), 10)
	var (
		byStr string
	)

	if query.By != 0 {
		byStr = url.QueryEscape(strconv.FormatInt(int64(query.By), 10))
	}

	anyQuery := query.By != 0

	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	l := bl + len("@post('/form/") + len(s_id) + len("/bump/") + len("'") + actionexpr.OptionsLen(options) + len(")") + al
	if anyQuery {
		l += len("?")
	}
	n := 0
	if query.By != 0 {
		if n > 0 {
			l += len("&")
		}
		l += len("by=") + len(byStr)
	}

	b.Grow(l)

	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/")
	b.WriteString(s_id)
	b.WriteString("/bump/")
	if anyQuery {
		b.WriteString("?")
	}
	n = 0
	if query.By != 0 {
		if n > 0 {
			b.WriteString("&")
		}
		b.WriteString("by=")
		b.WriteString(byStr)
	}
	b.WriteString("'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)

	return b.String()
}

type pageForm_Bump_POSTQuery struct {
	By int `query:"by"`
}

func (pageForm_Bump) POSTQuery(vBy int) pageForm_Bump_POSTQuery {
	return pageForm_Bump_POSTQuery{
		By: vBy,
	}
}

type pageForm_Go struct{}

// POST references /form/go/
func (pageForm_Go) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/go/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/go/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/go/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_GoStream struct{}

// POST references /form/go-stream/
func (pageForm_GoStream) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/go-stream/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/go-stream/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/go-stream/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_Patch struct{}

// POST references /form/patch/
func (pageForm_Patch) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/patch/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/patch/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/patch/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_PatchAt struct{}

// POST references /form/patch-at/
func (pageForm_PatchAt) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/patch-at/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/patch-at/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/patch-at/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_Remove struct{}

// DELETE references /form/remove/
func (pageForm_Remove) DELETE(options ...Option) string {
	if len(options) == 0 {
		return "@delete('/form/remove/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@delete('/form/remove/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@delete('/form/remove/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

// POST references /form/remove/
func (pageForm_Remove) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/remove/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/remove/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/remove/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_Render struct{}

// POST references /form/render/
func (pageForm_Render) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/render/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/render/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/render/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_Replace struct{}

// PUT references /form/replace/
func (pageForm_Replace) PUT(options ...Option) string {
	if len(options) == 0 {
		return "@put('/form/replace/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@put('/form/replace/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@put('/form/replace/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_SignalsBad struct{}

// POST references /form/signals-bad/
func (pageForm_SignalsBad) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/signals-bad/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/signals-bad/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/signals-bad/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_SignalsMissing struct{}

// POST references /form/signals-missing/
func (pageForm_SignalsMissing) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/signals-missing/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/signals-missing/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/signals-missing/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_SignalsRaw struct{}

// POST references /form/signals-raw/
func (pageForm_SignalsRaw) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/signals-raw/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/signals-raw/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/signals-raw/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_Submit struct{}

// POST references /form/submit/
func (pageForm_Submit) POST(options ...Option) string {
	if len(options) == 0 {
		return "@post('/form/submit/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@post('/form/submit/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@post('/form/submit/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}

type pageForm_Touch struct{}

// PATCH references /form/touch/
func (pageForm_Touch) PATCH(options ...Option) string {
	if len(options) == 0 {
		return "@patch('/form/touch/')"
	}
	var b strings.Builder
	bl, al := actionexpr.BeforeAfterLen(options)
	b.Grow(bl + len("@patch('/form/touch/'") + actionexpr.OptionsLen(options) + len(")") + al)
	actionexpr.WriteBefore(&b, options)
	b.WriteString("@patch('/form/touch/'")
	actionexpr.WriteOptions(&b, options)
	b.WriteByte(')')
	actionexpr.WriteAfter(&b, options)
	return b.String()
}
