package generator

import (
	"fmt"
	"os"
	"path/filepath"

	goimports "golang.org/x/tools/imports"

	"github.com/romshark/datapages/internal/parser/model"
)

// GeneratedHeader is the comment every generated file starts with.
// It is what marks a package as one datapages wrote.
const GeneratedHeader = "// Code generated by github.com/romshark/datapages; DO NOT EDIT."

// Options configures code generation.
type Options struct {
	// Prometheus enables generation of Prometheus metrics instrumentation.
	Prometheus bool
	// AssetsURLPrefix is the URL path prefix for serving static asset files.
	// When non-empty, the generator emits an assets subpackage with a URLPrefix
	// constant and enables WithAssets. When empty, asset serving is disabled.
	AssetsURLPrefix string
	// AssetsDir is the subdirectory within the app package containing static files
	// (e.g. "static"). Used as the embed.FS subdirectory and for dev-mode disk serving.
	AssetsDir string
	// AppDir is the path to the app source package relative to the module root
	// (e.g. "app"). Used to compute the dev-mode disk path for assets.
	AppDir string
	// GenImport is the full import path of the generated root package
	// (e.g. "github.com/example/myapp/datapagesgen").
	// Required for generating subpackage imports.
	GenImport string
}

// Generate generates the complete generated Datapages package with subpackages to
// destination directory dstDir. pkgName is the Go package name for the generated
// root package (e.g. "datapagesgen"). When m is nil, minimal stub files containing
// only the package declaration are written so that IDEs can resolve the import.
//
// Nothing is written unless every file renders.
// On error the destination is left as it was.
// A failed run cannot replace working generated code with code that does not build.
func Generate(
	dstDir string, pkgName string, m *model.App, perm os.FileMode, opts Options,
) error {
	if m == nil {
		return generateStubs(dstDir, pkgName, perm, opts.AssetsURLPrefix != "")
	}
	w := writerPool.Get().(*Writer)
	defer writerPool.Put(w)

	// rendered holds every file to write.
	// They are written only after all of them are formatted.
	type file struct {
		path    string
		content []byte
	}
	var rendered []file

	render := func(rel string, write func()) error {
		path := filepath.Join(dstDir, rel)
		write()
		out, err := goimports.Process(path, w.Buf, nil)
		if err != nil {
			return fmt.Errorf("formatting %s: %w", rel, err)
		}
		// goimports may hand back the writer's own buffer,
		// which the next file reuses.
		rendered = append(rendered, file{path, append([]byte(nil), out...)})
		return nil
	}

	w.Reset()
	w.prometheus = opts.Prometheus
	w.assetsURLPrefix = opts.AssetsURLPrefix
	w.assetsDir = opts.AssetsDir
	w.appDir = opts.AppDir
	w.genImport = opts.GenImport

	assetsDir := filepath.Join(dstDir, "assets")
	if opts.AssetsURLPrefix != "" {
		// Rendered first. goimports resolves the import from app_gen.go against it.
		if err := render(filepath.Join("assets", "assets_gen.go"),
			w.WritePkgAssets); err != nil {
			return err
		}
	}

	if err := render("app_gen.go", func() {
		w.Reset()
		w.prometheus = opts.Prometheus
		w.assetsURLPrefix = opts.AssetsURLPrefix
		w.assetsDir = opts.AssetsDir
		w.appDir = opts.AppDir
		w.genImport = opts.GenImport
		w.WriteApp(pkgName, m)
	}); err != nil {
		return err
	}
	if err := render(filepath.Join("action", "action_gen.go"), func() {
		w.Reset()
		w.WritePkgAction(m)
	}); err != nil {
		return err
	}
	if err := render(filepath.Join("href", "href_gen.go"), func() {
		w.Reset()
		w.WritePkgHref(m)
	}); err != nil {
		return err
	}

	for _, f := range rendered {
		if err := os.MkdirAll(filepath.Dir(f.path), 0o755); err != nil {
			return fmt.Errorf("creating directory %s: %w", filepath.Dir(f.path), err)
		}
		if err := os.WriteFile(f.path, f.content, perm); err != nil {
			return fmt.Errorf("writing %s: %w", f.path, err)
		}
	}

	// An old assets package is removed once the rest is in place.
	// A failed run leaves it alone.
	if opts.AssetsURLPrefix == "" {
		_ = os.RemoveAll(assetsDir)
	}

	// TODO(v1): Remove this, projects will have regenerated by then.
	// Remove the httperr package generated by earlier versions.
	_ = os.RemoveAll(filepath.Join(dstDir, "httperr"))

	return nil
}

// generateStubs writes minimal package declaration files for each generated
// package so that IDEs can resolve the import even when the app model is nil.
//
// A stub carries the generated header like every other generated file:
// without it the next run reads the destination as one datapages did not write.
func generateStubs(dstDir, pkgName string, perm os.FileMode, hasAssets bool) error {
	stubs := []struct{ dir, name, file string }{
		{dstDir, pkgName, "app_gen.go"},
		{filepath.Join(dstDir, "action"), "action", "action_gen.go"},
		{filepath.Join(dstDir, "href"), "href", "href_gen.go"},
	}
	assetsDir := filepath.Join(dstDir, "assets")
	if hasAssets {
		stubs = append(stubs,
			struct{ dir, name, file string }{assetsDir, "assets", "assets_gen.go"})
	} else {
		_ = os.RemoveAll(assetsDir)
	}
	for _, pkg := range stubs {
		if err := os.MkdirAll(pkg.dir, 0o755); err != nil {
			return fmt.Errorf("creating directory %s: %w", pkg.dir, err)
		}
		content := []byte(GeneratedHeader + "\n\npackage " + pkg.name + "\n")
		p := filepath.Join(pkg.dir, pkg.file)
		if err := os.WriteFile(p, content, perm); err != nil {
			return fmt.Errorf("writing %s: %w", pkg.file, err)
		}
	}
	return nil
}
