package generator

import (
	_ "embed"
	"go/types"
	"slices"
	"strings"

	"github.com/romshark/datapages/internal/parser/model"
	"github.com/romshark/datapages/internal/routepattern"
)

//go:embed app_static.go.txt
var appStaticContent string

//go:embed app_static_prom.go.txt
var appStaticPromContent string

//go:embed app_static_noprom.go.txt
var appStaticNoPromContent string

//go:embed app_static_2.go.txt
var appStaticContent2 string

// WriteApp generates code for the generated root package and appends it to buffer.
// pkgName is the Go package name (e.g. "datapagesgen").
func (w *Writer) WriteApp(pkgName string, m *model.App) {
	appPkg := appPkgQualifier(m)
	w.appPkgQual = appPkg
	w.buildEventMap(m.Events)
	w.usage = computeAppUsage(m)
	w.setSessionType(m)

	w.writeAppHeader(pkgName, m.PkgPath, needsJSON(m))
	w.Raw(appStaticContent)
	w.writeAssetsFileSystem()
	if w.prometheus {
		w.Raw(appStaticPromContent)
	} else {
		w.Raw(appStaticNoPromContent)
	}
	w.Raw(appStaticContent2)
	if w.usage.httpErrBad {
		w.Raw(`
func (s *Server) httpErrBad(w http.ResponseWriter, msg string, err error) {
	s.Logger().Debug("bad request", slog.String("cause", msg), slog.Any("err", err))
	http.Error(w, msg, http.StatusBadRequest)
}
`)
	}
	if w.usage.needsCheckIsDSReq() {
		w.writeCheckIsDSReq()
	}
	if w.usage.privateStreams {
		w.writeCheckUserSubject()
	}
	if w.usage.auth && w.usage.hasSession {
		w.writeAppCheckCSRF()
	}
	w.writeAppWriteHTML(m)
	if w.usage.stream {
		w.writeAppHandleStreamRequest()
	}
	w.writeAppServerStruct(appPkg)
	w.writeAppInit(appPkg)
	w.writeEventSubjectConsts(m.Events)
	w.writeMessageBrokerStreamSubjects(m.Events)
	w.writeEvSubjPageFuncs(m.Pages)
	if w.prometheus {
		w.writeBrokerSubjectKind(m.Events)
	}
	w.writeStateRuntime(m, appPkg)
	w.writeSetupHandlers(m)
	w.writeAppErrHelpers(m, appPkg)

	if m.PageError404 != nil &&
		m.PageError404.GET != nil && m.PageError404.GET.OutputBody != nil {
		w.writeRender404(m, appPkg)
	}

	// App-level action handlers.
	for _, h := range m.Actions {
		w.writeAppActionHandler(h, m, appPkg)
	}

	// Per-page handlers.
	for _, p := range m.Pages {
		if p.GET != nil && p.GET.OutputBody != nil {
			w.writePageGETHandler(p, m, appPkg)
		}
		if pageHasStream(p) {
			w.writePageGETStreamHandler(p, m, appPkg)
			if pageHasAnonStream(p, w.eventMap) {
				w.writePageGETStreamAnonHandler(p, m, appPkg)
			}
		}
		for _, h := range p.Actions {
			w.writePageActionHandler(p, h, m, appPkg)
		}
	}

	w.writeDispatcherTypes(appPkg)
}

func needsJSON(m *model.App) bool {
	for _, h := range m.Actions {
		if len(h.InputDispatches) > 0 {
			return true
		}
	}
	for _, p := range m.Pages {
		if len(p.EventHandlers) > 0 {
			return true
		}
		for _, h := range []*model.Handler{p.StreamOpen, p.StreamClose} {
			if h != nil && len(h.InputDispatches) > 0 {
				return true
			}
		}
		for _, h := range p.Actions {
			if len(h.InputDispatches) > 0 {
				return true
			}
		}
	}
	return false
}

func (w *Writer) writeAppHeader(pkgName string, appPkgPath string, jsonImport bool) {
	w.Line(0, "// Code generated by github.com/romshark/datapages; DO NOT EDIT.")
	w.Line(0, "")
	w.Linef(0, "package %s", pkgName)
	w.Line(0, "")
	w.Line(0, "import (")
	w.Line(1, `"bufio"`)
	w.Line(1, `"context"`)
	if jsonImport {
		w.Line(1, `"encoding/json"`)
	}
	w.Line(1, `"errors"`)
	w.Line(1, `"fmt"`)
	w.Line(1, `"io"`)
	w.Line(1, `"log/slog"`)
	w.Line(1, `"net"`)
	w.Line(1, `"net/http"`)
	w.Line(1, `"os"`)
	if w.usage.stream {
		w.Line(1, `"runtime/debug"`)
	}
	w.Line(1, `"slices"`)
	w.Line(1, `"strconv"`)
	w.Line(1, `"strings"`)
	w.Line(1, `"sync"`)
	if w.usage.stream {
		w.Line(1, `"sync/atomic"`)
	}
	w.Line(1, `"time"`)
	if w.usage.stateRuntime {
		w.Line(1, `"crypto/hmac"`)
		w.Line(1, `"crypto/rand"`)
		w.Line(1, `"crypto/sha256"`)
		w.Line(1, `"encoding/base64"`)
		w.Line(1, `"hash/maphash"`)
	}
	w.Line(0, "")
	w.Line(1, `"github.com/a-h/templ"`)
	// Always needed: writeHTML renders datapages.Component values.
	w.Line(1, `"github.com/romshark/datapages"`)
	w.Line(1, `"github.com/romshark/datapages/modules/csrf"`)
	w.Line(1, `"github.com/romshark/datapages/modules/messaging"`)
	w.Line(1, `"github.com/romshark/datapages/modules/sessions"`)
	w.Line(1, `"github.com/romshark/datapages/runtime/auth"`)
	w.Line(1, `"github.com/romshark/datapages/runtime/htmlattr"`)
	w.Line(1, `"github.com/romshark/datapages/runtime/httpread"`)
	w.Line(1, `"github.com/romshark/datapages/runtime/httpserve"`)
	w.Line(1, `dpsse "github.com/romshark/datapages/runtime/sse"`)
	w.Line(1, `"github.com/romshark/datapages/runtime/subject"`)
	w.Line(1, `"golang.org/x/sync/errgroup"`)
	w.Line(0, "")
	w.Byte('\t')
	// An unaliased import binds to the name the package declares.
	// Name it anyway when that differs from the last element of the path,
	// which is what a reader and the import formatter both assume it to be.
	if w.appPkgQual != appPkgName(appPkgPath) {
		w.Raw(w.appPkgQual)
		w.Byte(' ')
	}
	w.writeQuoted(appPkgPath)
	w.Byte('\n')
	if w.hasAssets() && w.genImport != "" {
		w.Byte('\t')
		w.writeQuoted(w.genImport + "/assets")
		w.Byte('\n')
	}
	if w.genImport != "" {
		w.Byte('\t')
		w.writeQuoted(w.genImport + "/href")
		w.Byte('\n')
	}
	w.Line(0, "")
	if w.prometheus {
		w.Line(1, `"github.com/prometheus/client_golang/prometheus"`)
		w.Line(1, `"github.com/romshark/datapages/runtime/prom"`)
		w.Line(1, `"github.com/prometheus/client_golang/prometheus/promhttp"`)
	}
	w.Line(1, `"github.com/starfederation/datastar-go/datastar"`)
	w.Line(0, ")")
}

func (w *Writer) hasAssets() bool { return w.assetsURLPrefix != "" }

// writeAssetsFileSystem emits what turns the embed.FS of
// datapages.WithAssets into the file system the routes are served from.
// Only the generated code knows the subdirectory and the dev-mode path,
// both of which the app package declared.
func (w *Writer) writeAssetsFileSystem() {
	if !w.hasAssets() {
		w.Raw(`
// assetsFileSystem rejects datapages.WithAssets: the app package declares no
// embed.FS with a URL path in its doc comment, hence there is nothing to serve.
func assetsFileSystem(cfg datapages.ServerConfig) (http.FileSystem, error) {
	if cfg.AssetsFS != nil {
		return cfg.AssetsFS, nil
	}
	if cfg.AssetsEmbed != nil {
		return nil, errors.New(
			"datapages.WithAssets: the app package declares no assets",
		)
	}
	return nil, nil
}
`)
		return
	}
	w.Raw(`
// assetsFileSystem is what the static files are served from.
// In dev mode (datapages.IsDevMode) they are read from disk (assets.DevDir)
// so that a change reloads without recompilation.
func assetsFileSystem(cfg datapages.ServerConfig) (http.FileSystem, error) {
	if cfg.AssetsFS != nil {
		return cfg.AssetsFS, nil
	}
	if cfg.AssetsEmbed == nil {
		return nil, nil
	}
	if datapages.IsDevMode() {
		return http.Dir(assets.DevDir), nil
	}
	sub, err := fs.Sub(*cfg.AssetsEmbed, assets.Dir)
	if err != nil {
		return nil, fmt.Errorf("datapages.WithAssets: %w", err)
	}
	return http.FS(sub), nil
}
`)
}

func (w *Writer) writeAppCheckCSRF() {
	w.Raw(`
`)
}

func (w *Writer) writeAppWriteHTML(m *model.App) {
	w.Raw(`
func (s *Server) writeHTML(
	w http.ResponseWriter,
	r *http.Request,
`)
	if m.Session != nil {
		w.Raw(`	sess `)
		w.Raw(w.sessionType)
		w.Raw(`,
`)
	}
	if m.GlobalHeadGenerator != nil {
		w.Raw(`	headGeneric, `)
	} else {
		w.Raw(`	`)
	}
	w.Raw(`head datapages.Head,
	body datapages.Component,
	writeBodyAttrs func(w http.ResponseWriter),
	writeBodySuffix func(w http.ResponseWriter),
) error {
`)

	if !w.usage.stateRuntime {
		w.Raw(`	_, err := io.WriteString(w, s.HTMLPrefix())
	if err != nil {
		return err
	}
`)
	} else {
		// The fetch wrapper goes between the two halves of the prefix.
		// It must be installed before anything else on the page can fetch.
		w.Raw(`	_, err := io.WriteString(w, s.HTMLHead())
	if err != nil {
		return err
	}
`)
		w.writeStateFetchWrapper()
		w.Raw(`	if _, err := io.WriteString(w, s.HTMLDatastarScript()); err != nil {
		return err
	}
`)
	}

	if m.GlobalHeadGenerator != nil {
		w.Raw(`	if headGeneric != nil {
		if err := headGeneric.Render(r.Context(), w); err != nil {
			return err
		}
	}
`)
	}

	w.Raw(`	if head != nil {
		if err := head.Render(r.Context(), w); err != nil {
			return err
		}
	}
`)
	if m.Session != nil {
		w.Raw(`	if sess.UserID() != "" {
		csrfToken := s.CSRFToken(sess.UserID(), sess.IssuedAt())
		if csrfToken != "" {
			// Write the fetch X-CSRF-Token header injector.
			if _, err := io.WriteString(w, ` + "`" + `
	<script type="module">
		const o = globalThis.fetch.bind(globalThis)
		globalThis.fetch=(i,init={}) => {
			const isReq=i instanceof Request
			const r=isReq ? i:new Request(i,init)
			if (r.headers.get("Datastar-Request")!=="true" ||
				r.method=="GET"||r.method=="HEAD"||r.method=="OPTIONS"
			) return isReq ? o(r,init):o(r)
			const h=new Headers(r.headers)
			h.set("X-CSRF-Token",'` + "`" + `); err != nil {
				return err
			}
			if _, err := io.WriteString(w, csrfToken); err != nil {
				return err
			}
			if _, err := io.WriteString(w, ` + "`" + `')
			return o(new Request(r,{...init,headers:h}))
		}
	</script>` + "`" + `); err != nil {
				return err
			}
		} else {
			s.Logger().Warn("generated empty CSRF token",
				slog.String("user-id", sess.UserID()),
				slog.Time("issued-at", sess.IssuedAt()))
		}
	}
`)
	}
	w.Raw(`	if _, err := io.WriteString(w, "</head><body "); err != nil {
		return err
	}
	if writeBodyAttrs != nil {
		writeBodyAttrs(w)
	}
	if _, err := io.WriteString(w, ">"); err != nil {
		return err
	}
	if body != nil {
		if err := body.Render(r.Context(), w); err != nil {
			return err
		}
	}
	if writeBodySuffix != nil {
		if _, err := io.WriteString(w, "<template "); err != nil {
			return err
		}
		writeBodySuffix(w)
		if _, err := io.WriteString(w, "></template>"); err != nil {
			return err
		}
	}
	_, err = io.WriteString(w, "</body></html>")
	return err
}
`)
}

func (w *Writer) writeCheckIsDSReq() {
	w.Raw(`
func (s *Server) checkIsDSReq(w http.ResponseWriter, r *http.Request) (ok bool) {
	if !httpserve.IsDatastarRequest(r) {
		s.Logger().Debug("not a datastar request",
			slog.Any("method", r.Method),
			slog.String("path", r.URL.Path))
		http.Error(w, http.StatusText(http.StatusNotAcceptable), http.StatusNotAcceptable)
		return false
	}
	return true
}
`)
}

// writeCheckUserSubject emits the guard for the ID of the session owner,
// which names the subject a private subscription reads.
// A wildcard in it would widen that subscription to every user.
func (w *Writer) writeCheckUserSubject() {
	w.Raw(`
func (s *Server) checkUserSubject(w http.ResponseWriter, userID string) (ok bool) {
	if subject.IsToken(userID) {
		return true
	}
	s.LogErr("subscribing private events", fmt.Errorf(
		"session user ID %q is not a subject token", userID))
	http.Error(w,
		http.StatusText(http.StatusInternalServerError),
		http.StatusInternalServerError)
	return false
}
`)
}

func (w *Writer) writeAppHandleStreamRequest() {
	w.Raw(`
func (s *Server) handleStreamRequest(
	w http.ResponseWriter, r *http.Request,`)
	if w.usage.streamAuth {
		w.Raw(` sessKey string, sess `)
		w.Raw(w.sessionType)
		w.Raw(`,`)
	}
	w.Raw(`
	subjects []string,
	onOpen func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
	) error,
	onClose func(streamID datapages.StreamID),
	fn func(
		streamID datapages.StreamID,
		sse *datastar.ServerSentEventGenerator,
		ch <-chan messaging.Message,
	),
) {
	if !s.checkIsDSReq(w, r) {
		return
	}

	streamID := datapages.StreamID(s.streamSeq.Add(1))

	// The subscription is established before the response head goes out.
	// A client learns the stream is open by reading that head and may dispatch
	// immediately after, which must not reach the broker before this.
	ctx := r.Context()
	sub, err := s.messageBroker.Subscribe(ctx, s.messageBrokerMetrics, subjects...)
	if err != nil {
		// Nothing has been written yet, so the error can still carry a status.
		s.httpErrIntern(w, r, nil, "subscribing to message broker", err)
		return
	}

	sse := datastar.NewSSE(w, r, datastar.WithCompression())
`)
	if w.prometheus {
		w.Raw(`	prom.SSEConnectionOpened()
	defer prom.SSEConnectionClosed()
	start := time.Now()
`)
	}
	w.Raw(`
	subC := sub.C()
	if onOpen != nil {
		if err := onOpen(streamID, sse); err != nil {
			sub.Close()
			s.httpErrIntern(w, r, sse, "handling stream open hook", err)
			return
		}
	}
`)
	if w.usage.streamAuth {
		w.Raw(`	sessionClosed := make(chan struct{})

	if sess.UserID() != "" {
		ctx, cancel := context.WithCancel(ctx)
		defer cancel()
		if err := s.SessionManager().NotifyClosed(ctx, sessKey, func() {
			close(sessionClosed)
		}); err != nil {
			// The open hook already ran. This stream holds whatever it took:
			// a subscription, and on a stateful page an instance.
			// The watchdog below is what usually gives those back and it does
			// not exist yet.
			sub.Close()
			if onClose != nil {
				onClose(streamID)
			}
			s.httpErrIntern(w, r, sse, "setting up session closure watcher", err)
			return
		}
	}

`)
	}
	w.Raw(`	go func() {
		select {
`)
	if w.usage.streamAuth {
		w.Raw(`		case <-sessionClosed:
`)
		if w.prometheus {
			w.Raw(`			prom.SSEDisconnect("close")
`)
		}
	}
	w.Raw(`		case <-r.Context().Done():
`)
	if w.prometheus {
		w.Raw(`			prom.SSEDisconnect("client")
`)
	}
	w.Raw(`		case <-s.ShutdownCh():
`)
	if w.prometheus {
		w.Raw(`			prom.SSEDisconnect("shutdown")
`)
	}
	w.Raw(`		}
`)
	if w.prometheus {
		w.Raw(`		prom.SSEConnectionDuration(start)
`)
	}
	w.Raw(`		sub.Close()
		if onClose != nil {
			// Not the goroutine net/http recovers.
			defer func() {
				if rec := recover(); rec != nil {
					s.LogErr("recovering panic in stream close hook",
						fmt.Errorf("%v\n%s", rec, debug.Stack()))
				}
			}()
			onClose(streamID)
		}
	}()

	fn(streamID, sse, subC)
}
`)
}

func (w *Writer) writeAppServerStruct(appPkg string) {
	w.Raw(`
type Server struct {
	*httpserve.Core
	messageBroker        messaging.Broker
	messageBrokerMetrics brokerMetrics
	streamSeq            atomic.Uint64
	app                  *`)
	w.Raw(appPkg)
	w.Raw(`.App
`)
	if w.usage.hasSession {
		w.Raw(`	*auth.Manager[`)
		w.Raw(w.sessionDataType)
		w.Raw(`]`)
	}
	if w.usage.stateRuntime {
		w.Raw(`
	stateConf             *datapages.StateConfig`)
	}
	w.Raw(`
}
`)
}

func (w *Writer) writeAppInit(appPkg string) {
	w.Raw(`
// Init wires the server. It is called by datapages.NewServer,
// which is the only way to construct a Server:
//
//	s, err := datapages.NewServer[`)
	w.Raw(appPkg)
	w.Raw(`.App, `)
	if w.usage.hasSession {
		w.Raw(w.sessionDataType)
	} else {
		w.Raw(`datapages.DisableSessions`)
	}
	w.Raw(`, `)
	if w.prometheus {
		w.Raw(`datapages.EnablePrometheus`)
	} else {
		w.Raw(`datapages.DisablePrometheus`)
	}
	w.Raw(`, Server](app, broker, opts...)
//
// Supported options:
//
//   - datapages.WithLogger
//   - datapages.WithMiddleware
//   - datapages.WithHTTPServer
//   - datapages.WithDatastarJS
//   - datapages.WithAssets`)
	if w.usage.hasSession {
		w.Raw(`
//   - datapages.WithSessionManager (required)
//   - datapages.WithSessions
//   - datapages.WithCSRFProtection (required)`)
	}
	if w.prometheus {
		w.Raw(`
//   - datapages.WithPrometheus (required)`)
	}
	w.Raw(`
func (s *Server) Init(
	cfg datapages.ServerConfig,
	app *`)
	w.Raw(appPkg)
	w.Raw(`.App,
	messageBroker messaging.Broker,
	sessionManager sessions.Manager[`)
	if w.usage.hasSession {
		w.Raw(w.sessionDataType)
	} else {
		w.Raw(`datapages.DisableSessions`)
	}
	w.Raw(`],
) error {
`)
	if !w.usage.hasSession {
		w.Raw(`	if sessionManager != nil {
		return errors.New("unexpected option WithSessionManager: package `)
		w.Raw(appPkg)
		w.Raw(` declares no session type")
	}
`)
	}
	if w.prometheus {
		w.Raw(`	if cfg.MetricsServer == nil {
		// This server is generated with datapages.EnablePrometheus,
		// hence the metrics it counts must be served.
		return errors.New("missing option WithPrometheus")
	}
`)
	} else {
		w.Raw(`	if cfg.MetricsServer != nil {
		// This server is generated with datapages.DisablePrometheus,
		// hence there is no instrumentation for the metrics to count.
		return errors.New("unexpected option WithPrometheus: " +
			"the server is generated with datapages.DisablePrometheus")
	}
`)
	}
	if w.usage.hasSession {
		w.Raw(`	if sessionManager == nil {
		return errors.New("missing option WithSessionManager")
	}
	if cfg.CSRF == nil {
		return errors.New("missing option WithCSRFProtection")
	}
`)
	}
	if w.usage.stateRuntime {
		w.Raw(`	if cfg.State == nil {
		return errors.New("missing option WithStateConfig: " +
			"this app has stateful pages")
	}
`)
	}
	w.Raw(`
	assetsFS, err := assetsFileSystem(cfg)
	if err != nil {
		return err
	}
	cfg.AssetsFS = assetsFS

	s.Core = httpserve.NewCore(cfg, `)
	if w.hasAssets() {
		w.Raw(`assets.URLPrefix`)
	} else {
		w.Raw(`""`)
	}
	w.Raw(`)
	s.app = app
	s.messageBroker = messageBroker
	s.messageBrokerMetrics = brokerMetrics{}

	if si, ok := s.messageBroker.(messaging.StreamInitializer); ok {
		if err := si.InitStreams(MessageBrokerStreamSubjects()); err != nil {
			return fmt.Errorf("initializing message broker streams: %w", err)
		}
	}
`)
	if w.usage.stateRuntime {
		w.Raw(`	s.stateConf = cfg.State
`)
	}
	if w.usage.hasSession {
		w.Raw(`	s.Manager = auth.NewManager(s.Core, sessionManager, cfg.Auth, cfg.CSRF, `)
		if w.prometheus {
			w.Raw(`prom.AuthMetrics{}`)
		} else {
			w.Raw(`nil`)
		}
		w.Raw(`)
`)
	}
	w.Raw(`
	setupHandlers(s)
`)
	if w.hasAssets() {
		w.Raw(`	if assetsFS != nil {
		h := http.StripPrefix(assets.URLPrefix, http.FileServer(assetsFS))
		if datapages.IsDevMode() {
			h = httpserve.DevNoCache(h)
		}
		s.Mux().Handle("GET "+assets.URLPrefix, h)
	}
`)
	}
	w.Raw(`
	s.Build()
	href.SetLogger(s.Logger())

	return nil
}
`)
}

func (w *Writer) writeEventSubjectConsts(events []*model.Event) {
	// EvSubj* constants (subscription subjects with wildcards for prefixed events).
	w.Line(0, "")
	w.Line(0, "const (")

	// Private events first.
	for _, e := range events {
		if e.IsPrivate() {
			w.Byte('\t')
			w.Raw(evSubjConst(e))
			w.Raw(" = ")
			w.writeQuoted(evSubjValue(e))
			w.Byte('\n')
		}
	}

	w.Line(0, "")
	w.Line(1, "// Public events:")
	w.Line(0, "")

	for _, e := range events {
		if !e.IsPrivate() {
			w.Byte('\t')
			w.Raw(evSubjConst(e))
			w.Raw(" = ")
			w.writeQuoted(evSubjValue(e))
			w.Byte('\n')
		}
	}

	w.Line(0, ")")

	// EvSubjPref* constants
	// (prefix for matching events whose concrete subject is only known at runtime).
	hasPrefixed := slices.ContainsFunc(events, evUsesPrefixMatch)
	if hasPrefixed {
		w.Line(0, "")
		w.Line(0, "const (")
		for _, e := range events {
			if evUsesPrefixMatch(e) {
				w.Byte('\t')
				w.Raw(evSubjPrefConst(e))
				w.Raw(" = ")
				w.writeQuoted(evSubjPrefValue(e))
				w.Byte('\n')
			}
		}
		w.Line(0, ")")
	}
}

func (w *Writer) writeMessageBrokerStreamSubjects(events []*model.Event) {
	w.Line(0, "")
	w.Line(0, "func MessageBrokerStreamSubjects() []string {")
	w.Line(1, "return []string{")
	for _, e := range events {
		w.Raw("\t\t")
		w.Raw(evSubjConst(e))
		w.Raw(",\n")
	}
	w.Line(1, "}")
	w.Line(0, "}")
}

func (w *Writer) writeEvSubjPageFuncs(pages []*model.Page) {
	for _, p := range pages {
		if !pageHasStream(p) {
			continue
		}
		if len(p.EventHandlers) == 0 {
			w.Line(0, "")
			w.Raw("var evSubj")
			w.Raw(p.TypeName)
			w.Raw(" = []string{}\n")
			continue
		}

		// Determine which events this page handles.
		hasPublic := false
		hasPrivate := false
		hasSignalScoped := false
		hasStateIDScoped := false
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil {
				continue
			}
			// An event can be both, which is what the call site tests for.
			// Classifying it as one leaves the builder a parameter short.
			switch {
			case ev.IsStateIDScoped():
				hasStateIDScoped = true
			case ev.IsPrivate() || ev.IsSignalScoped():
				hasPrivate = hasPrivate || ev.IsPrivate()
				hasSignalScoped = hasSignalScoped || ev.IsSignalScoped()
			default:
				hasPublic = true
			}
		}

		name := "evSubj" + p.TypeName

		signalFields := pageSignalSubjectFields(p, w.eventMap)

		// State-id-scoped events cannot mix with private/signal-scoped
		// (enforced by the parser), so a simple dedicated builder suffices.
		if hasStateIDScoped {
			w.writeEvSubjStateIDFunc(p, name, hasPublic)
			continue
		}

		if hasSignalScoped && !hasPrivate {
			// Signal-scoped events (possibly mixed with public).
			w.writeEvSubjSignalFunc(p, name, signalFields, hasPublic)
			continue
		}

		if hasPrivate && hasSignalScoped {
			// Mixed private + signal-scoped (possibly with public).
			w.writeEvSubjPrivateSignalFunc(p, name, signalFields, hasPublic)
			continue
		}

		if hasPrivate && !hasPublic {
			// All events are per-user, just take userID.
			w.Line(0, "")
			w.Raw("func ")
			w.Raw(name)
			w.Raw("(userID string) []string {\n")
			w.Line(1, "return []string{")
			for _, eh := range p.EventHandlers {
				ev := w.eventMap[eh.EventTypeName]
				if ev == nil {
					continue
				}
				w.Raw("\t\t")
				w.writeEvUserSubExpr(ev)
				w.Raw(",\n")
			}
			w.Line(1, "}")
			w.Line(0, "}")
			continue
		}

		if hasPublic && !hasPrivate {
			// All events are public, the list is the same for every stream.
			w.Line(0, "")
			w.Raw("var ")
			w.Raw(name)
			w.Raw(" = []string{\n")
			for _, eh := range p.EventHandlers {
				ev := w.eventMap[eh.EventTypeName]
				if ev == nil {
					continue
				}
				w.Byte('\t')
				w.Raw(evSubjConst(ev))
				w.Raw(",\n")
			}
			w.Line(0, "}")
			continue
		}

		// Mixed: public + private. Need conditional.
		w.Line(0, "")
		w.Raw("func ")
		w.Raw(name)
		w.Raw("(userID string) []string {\n")
		w.Line(1, "if userID == \"\" {")
		w.Line(2, "return []string{")
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || ev.IsPrivate() {
				continue
			}
			w.Raw("\t\t\t")
			w.Raw(evSubjConst(ev))
			w.Raw(",\n")
		}
		w.Line(2, "}")
		w.Line(1, "}")
		w.Line(1, "return []string{")

		// Public first, then private.
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || ev.IsPrivate() {
				continue
			}
			w.Raw("\t\t")
			w.Raw(evSubjConst(ev))
			w.Raw(",\n")
		}
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || !ev.IsPrivate() {
				continue
			}
			w.Raw("\t\t")
			w.writeEvUserSubExpr(ev)
			w.Raw(",\n")
		}

		w.Line(1, "}")
		w.Line(0, "}")
	}
}

// writeEvUserSubExpr emits a Go expression that builds a per-user
// subscription subject for a private event. Non-User positions
// become "*" wildcards; the User position uses the userID variable.
//
// E.g. for SubjectUser + SubjectChatRoom with subject "chat.sent":
//
//	"chat.sent." + userID + ".*"
func (w *Writer) writeEvUserSubExpr(e *model.Event) {
	var beforeUser strings.Builder
	beforeUser.WriteString(e.Subject)
	var afterUser strings.Builder
	foundUser := false
	for _, sf := range e.SubjectFields {
		if sf.Kind.IsUser() && !foundUser {
			foundUser = true
			continue
		}
		if !foundUser {
			beforeUser.WriteString(".*")
		} else {
			afterUser.WriteString(".*")
		}
	}

	w.writeQuoted(beforeUser.String() + ".")
	w.Raw(" + userID")
	if afterUser.String() != "" {
		w.Raw(" + ")
		w.writeQuoted(afterUser.String())
	}
}

// writeEvSubjSignalFunc emits an evSubjPageXxx function for pages
// whose events are signal-scoped (possibly mixed with plain public events).
// Each unique signal subject field becomes a string parameter.
func (w *Writer) writeEvSubjSignalFunc(
	p *model.Page, name string,
	signalFields []model.SubjectField, hasPublic bool,
) {
	w.Line(0, "")
	w.Raw("func ")
	w.Raw(name)
	w.Raw("(")
	idents := signalIdents(signalFields)
	identBySignal := signalIdentMap(signalFields, idents)
	for i, ident := range idents {
		if i > 0 {
			w.Raw(", ")
		}
		w.Raw("subj")
		w.Raw(ident)
		w.Raw(" string")
	}
	w.Raw(") []string {\n")
	w.Line(1, "return []string{")

	// Public events first.
	if hasPublic {
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || ev.IsPrivate() || ev.IsSignalScoped() {
				continue
			}
			w.Raw("\t\t")
			w.Raw(evSubjConst(ev))
			w.Raw(",\n")
		}
	}

	// Signal-scoped events.
	for _, eh := range p.EventHandlers {
		ev := w.eventMap[eh.EventTypeName]
		if ev == nil || !ev.IsSignalScoped() {
			continue
		}
		w.Raw("\t\t")
		w.writeEvSignalSubExpr(ev, identBySignal)
		w.Raw(",\n")
	}

	w.Line(1, "}")
	w.Line(0, "}")
}

// writeEvSubjStateIDFunc emits the evSubjPageXxx function for a page
// whose events are state-id-scoped (possibly mixed with plain public events).
// Takes the validated Datapages-Instance identifier and builds
// subscription subjects of the form "<base>.<stateID>".
func (w *Writer) writeEvSubjStateIDFunc(p *model.Page, name string, hasPublic bool) {
	w.Line(0, "")
	w.Raw("func ")
	w.Raw(name)
	w.Raw("(stateID string) []string {\n")
	w.Line(1, "return []string{")

	// Public events first.
	if hasPublic {
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || ev.IsStateIDScoped() {
				continue
			}
			w.Raw("\t\t")
			w.Raw(evSubjConst(ev))
			w.Raw(",\n")
		}
	}

	// State-id-scoped events: subject is "<base>.<stateID>", built from the
	// subject prefix constant. It must NOT be built from evSubjConst, which
	// is the wildcard subscription constant ("<base>.*") and would yield a
	// subject no publisher ever writes to.
	for _, eh := range p.EventHandlers {
		ev := w.eventMap[eh.EventTypeName]
		if ev == nil || !ev.IsStateIDScoped() {
			continue
		}
		w.Raw("\t\t")
		w.Raw(evSubjPrefConst(ev))
		w.Raw(" + stateID,\n")
	}

	w.Line(1, "}")
	w.Line(0, "}")
}

// writeEvSubjPrivateSignalFunc emits an evSubjPageXxx function for pages
// whose events mix private (user-addressed) and signal-scoped events,
// possibly with plain public events. Takes userID plus signal parameters.
func (w *Writer) writeEvSubjPrivateSignalFunc(
	p *model.Page, name string,
	signalFields []model.SubjectField, hasPublic bool,
) {
	w.Line(0, "")
	w.Raw("func ")
	w.Raw(name)
	w.Raw("(userID string")
	idents := signalIdents(signalFields)
	identBySignal := signalIdentMap(signalFields, idents)
	for _, ident := range idents {
		w.Raw(", subj")
		w.Raw(ident)
		w.Raw(" string")
	}
	w.Raw(") []string {\n")

	// A stream with no user subscribes by everything that is not addressed to one.
	// A subject built from an empty user ID names nobody: the in-memory
	// broker reads it as a literal that never matches, NATS refuses it and the
	// stream fails to open. Signal-scoped events are public and stay.
	w.Line(1, "if userID == \"\" {")
	w.Line(2, "return []string{")
	for _, eh := range p.EventHandlers {
		ev := w.eventMap[eh.EventTypeName]
		if ev == nil || ev.IsPrivate() {
			continue
		}
		w.Raw("\t\t\t")
		if ev.IsSignalScoped() {
			w.writeEvSignalSubExpr(ev, identBySignal)
		} else {
			w.Raw(evSubjConst(ev))
		}
		w.Raw(",\n")
	}
	w.Line(2, "}")
	w.Line(1, "}")

	w.Line(1, "return []string{")

	// Public events first.
	if hasPublic {
		for _, eh := range p.EventHandlers {
			ev := w.eventMap[eh.EventTypeName]
			if ev == nil || ev.IsPrivate() || ev.IsSignalScoped() {
				continue
			}
			w.Raw("\t\t")
			w.Raw(evSubjConst(ev))
			w.Raw(",\n")
		}
	}

	// Private events.
	for _, eh := range p.EventHandlers {
		ev := w.eventMap[eh.EventTypeName]
		if ev == nil || !ev.IsPrivate() {
			continue
		}
		w.Raw("\t\t")
		w.writeEvUserSubExpr(ev)
		w.Raw(",\n")
	}

	// Signal-scoped events.
	for _, eh := range p.EventHandlers {
		ev := w.eventMap[eh.EventTypeName]
		if ev == nil || !ev.IsSignalScoped() {
			continue
		}
		w.Raw("\t\t")
		w.writeEvSignalSubExpr(ev, identBySignal)
		w.Raw(",\n")
	}

	w.Line(1, "}")
	w.Line(0, "}")
}

// writeEvSignalSubExpr emits a Go expression that builds a signal-scoped
// subscription subject. Each signal-tagged subject field uses the parameter
// its signal is bound to; non-signal positions become "*" wildcards.
//
// E.g. for a field with signal:"instance_id" and subject "calc.updated":
//
//	"calc.updated." + subjInstanceID
func (w *Writer) writeEvSignalSubExpr(
	ev *model.Event, identBySignal map[string]string,
) {
	w.writeQuoted(ev.Subject + ".")
	for i, sf := range ev.SubjectFields {
		if i > 0 {
			w.Raw(` + "." + `)
		} else {
			w.Raw(" + ")
		}
		if sf.SignalName != "" {
			w.Raw("subj")
			w.Raw(identBySignal[sf.SignalName])
		} else {
			w.writeQuoted("*")
		}
	}
}

func (w *Writer) writeBrokerSubjectKind(events []*model.Event) {
	w.Raw(`
// brokerSubjectKind folds subjects that carry a user or a tab back into the event name.
// A metric labelled with the raw subject would carry one value per user or per tab.
func brokerSubjectKind(subject string) string {
	switch {
`)
	for _, e := range events {
		if evUsesPrefixMatch(e) {
			w.Raw("\tcase strings.HasPrefix(subject, ")
			w.Raw(evSubjPrefConst(e))
			w.Raw("):\n")
		} else {
			w.Raw("\tcase subject == ")
			w.Raw(evSubjConst(e))
			w.Raw(":\n")
		}
		w.Raw("\t\treturn ")
		w.writeQuoted(e.Subject)
		w.Byte('\n')
	}
	w.Line(1, "default:")
	w.Line(2, `return "unknown"`)
	w.Line(1, "}")
	w.Line(0, "}")
}

func (w *Writer) writeSetupHandlers(m *model.App) {
	w.Line(0, "")
	w.Line(0, "func setupHandlers(s *Server) {")
	w.Line(1, "// Pages")

	for _, p := range m.Pages {
		if p.GET == nil || p.GET.OutputBody == nil {
			continue
		}

		routeForHandler := routepattern.WithTrailingSlash(p.Route)

		if p.PageSpecialization == model.PageTypeIndex {
			// Index page: GET /
			w.Line(1, "s.Mux().HandleFunc(")
			w.Line(2, "\"GET /\",")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw("GET)\n")
		} else if routepattern.EndsInWildcard(p.Route) {
			// A {name...} wildcard runs to the end of the path already.
			// Marking the end after it puts the wildcard in the middle,
			// which is a pattern net/http will not parse.
			w.Line(1, "s.Mux().HandleFunc(")
			w.Raw("\t\t\"GET ")
			w.Raw(p.Route)
			w.Raw("\",\n")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw("GET)\n")
		} else {
			w.Line(1, "s.Mux().HandleFunc(")
			w.Raw("\t\t\"GET ")
			w.Raw(routeForHandler)
			w.Raw("{$}\",\n")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw("GET)\n")
		}

		// Stream endpoint.
		if pageHasStream(p) {
			streamPath := routeStreamPath(p.Route)

			w.Line(1, "s.Mux().HandleFunc(")
			w.Raw("\t\t\"GET ")
			w.Raw(streamPath)
			w.Raw("{$}\",\n")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw("GETStream)\n")

			if pageHasAnonStream(p, w.eventMap) {
				w.Line(1, "s.Mux().HandleFunc(")
				w.Raw("\t\t\"GET ")
				w.Raw(streamPath)
				w.Raw("anon/{$}\",\n")
				w.Raw("\t\ts.handle")
				w.Raw(p.TypeName)
				w.Raw("GETStreamAnon)\n")
			}
		}
	}

	// App-level actions.
	for _, h := range m.Actions {
		route := routepattern.WithTrailingSlash(h.Route)
		method := strings.ToUpper(h.HTTPMethod)

		w.Line(1, "s.Mux().HandleFunc(")
		w.Raw("\t\t\"")
		w.Raw(method)
		w.Byte(' ')
		w.Raw(route)
		w.Raw("{$}\",\n")
		w.Raw("\t\ts.handle")
		w.Raw(method)
		w.Raw(h.Name)
		w.Raw(")\n")
	}

	// Page actions.
	for _, p := range m.Pages {
		for _, h := range p.Actions {
			route := routepattern.WithTrailingSlash(h.Route)
			method := strings.ToUpper(h.HTTPMethod)

			w.Line(1, "s.Mux().HandleFunc(")
			w.Raw("\t\t\"")
			w.Raw(method)
			w.Byte(' ')
			w.Raw(route)
			w.Raw("{$}\",\n")
			w.Raw("\t\ts.handle")
			w.Raw(p.TypeName)
			w.Raw(method)
			w.Raw(h.Name)
			w.Raw(")\n")
		}
	}

	w.Line(0, "}")
}

func (w *Writer) writeHTTPErrFallback() {
	if !w.usage.errSentinels {
		w.Raw(`	const code = http.StatusInternalServerError
	http.Error(w, http.StatusText(code), code)
`)
		return
	}
	w.Raw(`	switch {
	case errors.Is(err, datapages.ErrBadRequest):
		http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
	case errors.Is(err, datapages.ErrForbidden):
		http.Error(w, http.StatusText(http.StatusForbidden), http.StatusForbidden)
	case errors.Is(err, datapages.ErrNotFound):
		http.Error(w, http.StatusText(http.StatusNotFound), http.StatusNotFound)
	case errors.Is(err, datapages.ErrConflict):
		http.Error(w, http.StatusText(http.StatusConflict), http.StatusConflict)
	default:
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
	}
`)
}

// needsCSRFOnly reports whether a handler has to run the session check for the
// CSRF token alone, because it reads nothing of the session itself.
//
// The check lives inside the session helper. A state-changing action that
// declares neither session nor sessionToken would never call it,
// and a cross-site page can make a browser send exactly that request.
func needsCSRFOnly(h *model.Handler, m *model.App) bool {
	if m.Session == nil {
		return false
	}
	switch strings.ToUpper(h.HTTPMethod) {
	case "GET", "HEAD", "OPTIONS":
		// Nothing to protect: these change nothing.
		return false
	}
	return true
}

// writeCSRFOnlyCheck emits the session lookup a handler runs for its CSRF token.
// The session itself is not passed on; the handler did not ask for it.
func (w *Writer) writeCSRFOnlyCheck() {
	w.Line(1, "// CSRF protection covers every state-changing action, including")
	w.Line(1, "// the ones that read nothing of the session.")
	w.Line(1, "if _, _, ok := s.ReadSession(w, r); !ok {")
	w.Line(2, "return")
	w.Line(1, "}")
}

// writeAppErrHelpers emits httpErrIntern,
// which answers a request whose handler failed.
//
// PageError500 and RecoverError are separate features and each one applies on its own.
// A page load is answered by the 500 page when the app supplies one.
// A Datastar request is answered by RecoverError when the app defines it,
// because that request expects an event stream rather than a document.
// An app that has only one of the two gets it for the requests it covers,
// and the plain HTTP error for the rest.
func (w *Writer) writeAppErrHelpers(m *model.App, appPkg string) {
	hasPage := m.PageError500 != nil
	hasRecover := m.RecoverError != nil

	if !hasPage && !hasRecover {
		w.Raw(`
func (s *Server) httpErrIntern(
	w http.ResponseWriter, _ *http.Request,
	_ *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
`)
		w.writeHTTPErrFallback()
		w.Raw(`}
`)
		return
	}

	if hasPage {
		// httpErrIntern answers a page load by rendering PageError500.
		// The handler of that page therefore can't report through it.
		w.Raw(`
// httpErrFinal writes the error response without rendering PageError500.
// The PageError500 handler uses it so it can't render itself.
func (s *Server) httpErrFinal(w http.ResponseWriter, msg string, err error) {
	s.LogErr(msg, err)
`)
		w.writeHTTPErrFallback()
		w.Raw(`}
`)
	}

	w.Raw(`
func (s *Server) httpErrIntern(
	w http.ResponseWriter, r *http.Request,
	sse *datastar.ServerSentEventGenerator, msg string, err error,
) {
	s.LogErr(msg, err)
`)
	if hasPage {
		w.Raw(`	if !httpserve.IsDatastarRequest(r) {
		// A page load gets the app's own 500 page, with the status that
		// says what happened. The page's own route serves 200;
		// this is the other way in.
		w.WriteHeader(http.StatusInternalServerError)
		s.handlePageError500GET(w, r)
		return
	}
`)
	}
	if hasRecover {
		w.Raw(`	// The response of a Datastar request is an event stream. Once one is
	// open the status line is gone, which is what committed reports.
	committed := sse != nil
	if sse == nil {
		sse = datastar.NewSSE(w, r, datastar.WithCompression())
		committed = true
	}
	errRecover := s.`)
		w.Raw(appPkg)
		w.Raw(`.RecoverError(`)
		for i, kind := range m.RecoverError.OrderedInputs {
			if i > 0 {
				w.Raw(", ")
			}
			if kind == model.InputKindSSE {
				w.Raw("dpsse.New(sse)")
			} else {
				w.Raw("err")
			}
		}
		w.Raw(`)
	if errRecover == nil {
`)
		if w.prometheus {
			w.Raw(`		prom.InternalErrorRecovered()
`)
		}
		w.Raw(`		return // Feedback delivered gracefully.
	}
	// RecoverError failed — fall back to HTTP error response.
`)
		if w.prometheus {
			w.Raw(`	prom.InternalErrorNotRecovered()
`)
		}
		w.Raw(`	s.Logger().Error("recovering error",
		slog.Any("orig.msg", msg),
		slog.Any("orig.err", err),
		slog.Any("err", errRecover))
	if committed {
		// http.Error would write a status the client already received,
		// and append its text to the event stream the client is reading.
		return
	}
`)
	}
	w.writeHTTPErrFallback()
	w.Raw(`}
`)
}

func (w *Writer) writeRender404(m *model.App, appPkg string) {
	p := m.PageError404

	w.Line(0, "")
	w.Line(0, "func (s *Server) render404(w http.ResponseWriter, r *http.Request) {")
	w.Line(1, "// The URL is claimed by no page. Whatever the app renders for it,")
	w.Line(1, "// the response says so: a cache that stores it and a crawler that")
	w.Line(1, "// reads it both go by the status.")
	w.Line(1, "w.WriteHeader(http.StatusNotFound)")

	h404 := p.GET.Handler
	headNeedsSess := m.GlobalHeadGenerator != nil && m.GlobalHeadGenerator.InputSession
	if h404.InputSession != nil || headNeedsSess {
		w.Line(1, "sess, _, ok := s.ReadSession(w, r)")
		w.Line(1, "if !ok {")
		w.Line(2, "return")
		w.Line(1, "}")
		w.Line(0, "")
	}

	w.writePageConstructorStmt("p", p, appPkg)
	w.Line(0, "")

	// Call GET.
	w.writeGETCall(p, m, appPkg, "render404")

	w.Line(0, "}")
}

func (w *Writer) writePageConstructorStmt(varName string, p *model.Page, appPkg string) {
	w.Byte('\t')
	w.Raw(varName)
	w.Raw(" := ")
	w.Raw(appPkg)
	w.Byte('.')
	w.Raw(p.TypeName)
	w.Raw("{\n")
	w.Line(2, "App: s.app,")
	for _, embed := range p.Embeds {
		w.writeEmbedInitStmt(p, embed, appPkg, 2, nil)
	}
	w.Line(1, "}")
}

func (w *Writer) writeEmbedInitStmt(
	p *model.Page, ap *model.AbstractPage, appPkg string, indent int,
	parent types.Type,
) {
	for range indent {
		w.Byte('\t')
	}
	w.Raw(ap.TypeName)
	w.Raw(": ")
	expr, embedded := w.embedLiteralExpr(p, ap, appPkg, parent)
	w.Raw(expr)
	w.Raw("{\n")
	w.Line(indent+1, "App: s.app,")
	for _, sub := range ap.Embeds {
		w.writeEmbedInitStmt(p, sub, appPkg, indent+1, embedded)
	}
	w.Line(indent, "},")
}

// App-level action handler generation kept here; methodized.

func (w *Writer) writeAppActionHandler(h *model.Handler, m *model.App, appPkg string) {
	w.Line(0, "")
	w.Raw("func (s *Server) handle")
	w.Raw(strings.ToUpper(h.HTTPMethod))
	w.Raw(h.Name)
	w.Raw("(w http.ResponseWriter, r *http.Request) {\n")

	if h.InputSSE != nil || h.InputSignals != nil {
		w.Line(1, "if !s.checkIsDSReq(w, r) {")
		w.Line(2, "return")
		w.Line(1, "}")
		w.Line(0, "")
	}

	// Stateful App-level action: verify the Datapages-Instance header and
	// look up the slot in the map for the referenced state type.
	// The action only succeeds when the calling tab is bound to a page that uses
	// the same state type. Its mutex is taken once the request has been read.
	if h.InputState != nil {
		w.writeVerifyInstanceIDHeader()
		w.writeLookupSlotOrReject(stateTypeRef(m, h.InputState.StateTypeName))
		if h.InputStateID != nil {
			w.writeStateRouteKeyVar()
		}
	}

	// Auth.
	needsToken := h.OutputCloseSession != nil
	headNeedsSess := h.OutputBody != nil && m.GlobalHeadGenerator != nil &&
		m.GlobalHeadGenerator.InputSession
	switch {
	case h.InputSession != nil || needsToken || headNeedsSess:
		// A local nobody reads is a package that does not compile.
		sessVar := "_"
		if h.InputSession != nil || headNeedsSess {
			sessVar = "sess"
		}
		if needsToken {
			w.Linef(1, "%s, sessToken, ok := s.ReadSession(w, r)", sessVar)
		} else {
			w.Linef(1, "%s, _, ok := s.ReadSession(w, r)", sessVar)
		}
		w.Line(1, "if !ok {")
		w.Line(2, "return")
		w.Line(1, "}")
	case needsCSRFOnly(h, m):
		w.writeCSRFOnlyCheck()
	}

	// Build the call.
	w.writeHandlerCallAndOutputs(nil, h, m, appPkg, true)

	w.Line(0, "}")
}

func (w *Writer) writeHandlerCallAndOutputs(
	p *model.Page, h *model.Handler, m *model.App, appPkg string, isAppLevel bool,
) {
	// Body size limit for non-GET actions.
	if h.InputSignals != nil && h.InputSSE == nil {
		w.Line(1, "r.Body = http.MaxBytesReader(w, r.Body, DefaultBodySizeLimit)")
	}

	// Read signals.
	if h.InputSignals != nil {
		w.Raw("\tvar signals ")
		w.Raw(renderSignalsType(h.InputSignals, m))
		w.Byte('\n')
		w.Line(1, "if err := datastar.ReadSignals(r, &"+varSignals+"); err != nil {")
		w.Line(2, `s.httpErrBad(w, "reading signals", err)`)
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Read query params.
	if h.InputQuery != nil {
		w.writeReadQuery(h.InputQuery, m)
	}

	// Read path params.
	if h.InputPath != nil {
		w.writeReadPath(h.InputPath, m)
	}

	// The request is read; claim the state for the duration of the handler.
	// Before the SSE generator, which commits the response headers and would
	// leave the rejection below nowhere to go.
	if h.InputState != nil {
		w.writeLockSlotOrReject()
	}

	// Dispatch closures.
	w.writeDispatchers(h, "dispatch", "r.Context()")

	// SSE for actions that take it.
	if h.InputSSE != nil && !isAppLevel {
		w.Line(0, "")
		w.Line(1, "sse := datastar.NewSSE(w, r, datastar.WithCompression())")
	}

	// Page constructor (for page actions).
	if p != nil {
		w.writePageConstructorStmt("p", p, appPkg)
	}

	// Build the actual method call.
	w.writeMethodCall(p, h, m, isAppLevel)
}

func (w *Writer) writeMethodCall(
	p *model.Page, h *model.Handler, m *model.App, isAppLevel bool,
) {
	// Build output variable list in user-defined order.
	outs := handlerOutputVars(h)

	// Build input args in user-defined order.
	args := handlerInputArgs(h, isAppLevel, "dispatch")

	// Build the call expression.
	receiver := "p"
	if isAppLevel {
		receiver = "s.app"
	}
	methodName := h.HTTPMethod + h.Name

	if len(outs) == 0 {
		// Void return or only error.
		if h.OutputErr != nil {
			w.Raw("\tif err := ")
			w.writeCallExpr(receiver, methodName, args)
			w.Raw("; err != nil {\n")
			w.Raw("\t\ts.httpErrIntern(w, r, nil, \"handling action ")
			w.Raw(actionOwnerName(p, isAppLevel))
			w.Byte('.')
			w.Raw(h.Name)
			w.Raw("\", err)\n")
			w.Line(1, "}")
		} else {
			w.Byte('\t')
			w.writeCallExpr(receiver, methodName, args)
			w.Byte('\n')
		}
		return
	}

	w.Byte('\t')
	w.writeCommaSep(outs)
	w.Raw(" := ")
	w.writeCallExpr(receiver, methodName, args)
	w.Byte('\n')

	if h.OutputErr != nil {
		sseRef := "nil"
		if h.InputSSE != nil && !isAppLevel {
			sseRef = "sse"
		}
		w.Line(1, "if err != nil {")
		w.Raw("\t\ts.httpErrIntern(w, r, ")
		w.Raw(sseRef)
		w.Raw(", \"handling ")
		w.Raw(handlerKind(h))
		if handlerKind(h) != "" {
			w.Byte(' ')
		}
		w.Raw(actionOwnerName(p, isAppLevel))
		w.Byte('.')
		w.Raw(h.Name)
		w.Raw("\", err)\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Close session.
	if h.OutputCloseSession != nil {
		w.Raw("\tif ")
		w.Raw(outputVar(h.OutputCloseSession))
		w.Raw(" {\n")
		w.Line(2, "if err := s.CloseSession(w, r, sessToken); err != nil {")
		w.Line(3, `s.httpErrIntern(w, r, nil, "removing session", err)`)
		w.Line(3, "return")
		w.Line(2, "}")
		w.Line(1, "}")
	}

	// New session.
	if h.OutputNewSession != nil {
		w.Raw("\tif j := ")
		w.Raw(outputVar(h.OutputNewSession))
		w.Raw("; j.UserID != \"\" {\n")
		w.Raw("\t\tif err := s.CreateSession(w, r, ")
		w.Raw(outputVar(h.OutputNewSession))
		w.Raw("); err != nil {\n")
		w.Line(3, `s.httpErrIntern(w, r, nil, "creating session", err)`)
		w.Line(2, "}")
		w.Line(1, "}")
	}

	// Redirect.
	if h.OutputRedirect != nil {
		w.Raw("\tif httpserve.Redirect(w, r, ")
		w.Raw(outputVar(h.OutputRedirect))
		w.Raw(") {\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Render body (if action returns templ.Component).
	if h.OutputBody != nil {
		ownerName := actionOwnerName(p, isAppLevel)

		if m.GlobalHeadGenerator != nil {
			w.writeGenericHeadCall(m.GlobalHeadGenerator, hasSessionInput(h))
		}

		w.Line(1, "if err := s.writeHTML(")
		w.Raw("\t\tw, r, ")
		if m.Session != nil {
			sessArg := "sess"
			headNeedsSession := m.GlobalHeadGenerator != nil &&
				m.GlobalHeadGenerator.InputSession
			if !hasSessionInput(h) && !headNeedsSession {
				sessArg = w.sessionType + "{}"
			}
			w.Raw(sessArg)
			w.Raw(", ")
		}
		if m.GlobalHeadGenerator != nil {
			w.Raw("genericHead, nil, ")
		} else {
			w.Raw("nil, ")
		}
		w.Raw(outputVar(h.OutputBody.Output))
		w.Raw(", nil, nil,\n")
		w.Line(1, "); err != nil {")
		w.Raw("\t\ts.LogErr(\"rendering response of ")
		w.Raw(ownerName)
		w.Byte('.')
		w.Raw(h.HTTPMethod)
		w.Raw(h.Name)
		w.Raw("\", err)\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}
}

// writeDispatchers emits one dispatcher value per datapages.Dispatcher parameter
// of the handler. prefix names them apart when a generated function holds the
// dispatchers of more than one handler, as the stream handler does.
// ctxExpr is the context Dispatch publishes with.
func (w *Writer) writeDispatchers(h *model.Handler, prefix, ctxExpr string) {
	for _, d := range h.InputDispatches {
		if !slices.Contains(w.dispatchedEvents, d.EventTypeName) {
			w.dispatchedEvents = append(w.dispatchedEvents, d.EventTypeName)
		}
		w.Line(0, "")
		w.Byte('\t')
		w.Raw(dispatchVarName(prefix, d.EventTypeName))
		w.Raw(" := ")
		w.Raw(dispatcherTypeName(d.EventTypeName))
		w.Raw("{s: s, ctx: ")
		w.Raw(ctxExpr)
		w.Raw("}\n")
	}
}

// writeDispatcherTypes emits the datapages.Dispatcher implementation of every
// event a handler dispatches. It marshals the event and publishes it to every
// subject its subject fields expand into.
func (w *Writer) writeDispatcherTypes(appPkg string) {
	for _, evName := range w.dispatchedEvents {
		w.writeDispatcherType(evName, appPkg)
	}
}

func (w *Writer) writeDispatcherType(evName, appPkg string) {
	ev := w.eventMap[evName]
	typeName := dispatcherTypeName(evName)
	eventType := appPkg + "." + evName

	w.Line(0, "")
	w.Raw("type ")
	w.Raw(typeName)
	w.Raw(" struct {\n")
	w.Line(1, "s   *Server")
	w.Line(1, "ctx context.Context")
	w.Line(0, "}")

	w.Line(0, "")
	w.Raw("func (d ")
	w.Raw(typeName)
	w.Raw(") Dispatch(e ")
	w.Raw(eventType)
	w.Raw(") error {\n")
	w.Line(1, "return d.DispatchCtx(d.ctx, e)")
	w.Line(0, "}")

	w.Line(0, "")
	w.Raw("func (d ")
	w.Raw(typeName)
	w.Raw(") DispatchCtx(\n")
	w.Line(1, "ctx context.Context, e "+eventType+",")
	w.Line(0, ") error {")

	if ev != nil && ev.HasSubjectFields() {
		// Guard before any work: a value carrying a separator or a wildcard
		// makes a subject of a different shape,
		// which every subscription then misses in silence.
		for _, sf := range ev.SubjectFields {
			w.Raw("\tif !subject.IsToken(string(e.")
			w.Raw(sf.FieldName)
			w.Raw(")) {\n")
			w.Line(2, "return fmt.Errorf(")
			w.Raw("\t\t\t\"")
			w.Raw(evName)
			w.Byte('.')
			w.Raw(sf.FieldName)
			w.Raw(" must be a non-empty subject token, received %q\",\n")
			w.Raw("\t\t\te.")
			w.Raw(sf.FieldName)
			w.Raw(")\n")
			w.Line(1, "}")
		}
	}

	w.Line(1, "j, err := json.Marshal(e)")
	w.Line(1, "if err != nil {")
	w.Raw("\t\treturn fmt.Errorf(\"marshaling ")
	w.Raw(evName)
	w.Raw(" JSON: %w\", err)\n")
	w.Line(1, "}")

	if ev != nil && ev.HasSubjectFields() {
		// Every segment carries one value, so the subject is a plain
		// concatenation of the base subject and the fields, in field order.
		w.Raw("\tsubj := ")
		w.writeQuoted(ev.Subject + ".")
		for i, sf := range ev.SubjectFields {
			if i > 0 {
				w.Raw(` + "." + `)
			} else {
				w.Raw(" + ")
			}
			w.Raw("string(e.")
			w.Raw(sf.FieldName)
			w.Byte(')')
		}
		w.Byte('\n')
		w.Raw("\terr = d.s.messageBroker.Publish(")
		w.Raw("ctx, d.s.messageBrokerMetrics, subj, j)\n")
		w.Line(1, "if err != nil {")
		w.Raw("\t\treturn fmt.Errorf(\"publishing subject %q: %w\", subj, err)\n")
		w.Line(1, "}")
	} else if ev != nil {
		w.Raw("\terr = d.s.messageBroker.Publish(ctx, d.s.messageBrokerMetrics, ")
		w.Raw(evSubjConst(ev))
		w.Raw(", j)\n")
		w.Line(1, "if err != nil {")
		w.Raw("\t\treturn fmt.Errorf(\"publishing subject %q: %w\", ")
		w.Raw(evSubjConst(ev))
		w.Raw(", err)\n")
		w.Line(1, "}")
	}

	w.Line(1, "return nil")
	w.Line(0, "}")
}

// Handler inputs are carried by datapages.Path, datapages.Query and
// datapages.Signals, so generated code populates the Values field of each.
const (
	varPath    = "path.Values"
	varQuery   = "query.Values"
	varSignals = "signals.Values"
)

func renderSignalsType(input *model.Input, m *model.App) string {
	return "datapages.Signals[" + renderValuesType(input, m) + "]"
}

func renderQueryType(input *model.Input, m *model.App) string {
	return "datapages.Query[" + renderValuesType(input, m) + "]"
}

func renderPathType(input *model.Input, m *model.App) string {
	return "datapages.Path[" + renderValuesType(input, m) + "]"
}

// renderValuesType renders the Values type argument of a wrapped input.
func renderValuesType(input *model.Input, m *model.App) string {
	if isNamedType(input.Type) {
		return renderType(input.Type)
	}
	return renderAnonStructType(input.Type, m.Fset)
}

func handlerKind(h *model.Handler) string {
	if h.HTTPMethod == "" || h.HTTPMethod == "GET" {
		return ""
	}
	return "action"
}

func actionOwnerName(p *model.Page, isAppLevel bool) string {
	if isAppLevel {
		return "App"
	}
	if p != nil {
		return p.TypeName
	}
	return "App"
}

// writeGETCall generates the GET method call and HTML rendering for a page.
func (w *Writer) writeGETCall(
	p *model.Page, m *model.App, appPkg string, context string,
) {
	if p.GET == nil || p.GET.OutputBody == nil {
		return
	}
	h := p.GET.Handler

	// Build output list.
	var outsBuf [8]string
	outs := outsBuf[:0]
	if p.GET.OutputBody != nil {
		outs = append(outs, outputVar(p.GET.OutputBody.Output))
	}
	if p.GET.OutputHead != nil {
		outs = append(outs, outputVar(p.GET.OutputHead.Output))
	}
	if h.OutputRedirect != nil {
		outs = append(outs, outputVar(h.OutputRedirect))
	}
	if h.OutputDisableRefresh != nil {
		outs = append(outs, outputVar(h.OutputDisableRefresh))
	}
	if h.OutputEnableBgStream != nil {
		outs = append(outs, outputVar(h.OutputEnableBgStream))
	}
	if h.OutputErr != nil {
		outs = append(outs, "err")
	}

	// Build input args in user-defined order.
	args := handlerInputArgs(h, false, "dispatch")

	w.Byte('\t')
	w.writeCommaSep(outs)
	w.Raw(" := ")
	w.writeCallExpr("p", "GET", args)
	w.Byte('\n')

	if h.OutputErr != nil {
		w.Line(1, "if err != nil {")
		w.Raw("\t\ts.httpErrIntern(w, r, nil, \"handling ")
		w.Raw(p.TypeName)
		w.Raw(".GET\", err)\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Redirect.
	if h.OutputRedirect != nil {
		w.Raw("\tif httpserve.Redirect(w, r, ")
		w.Raw(outputVar(h.OutputRedirect))
		w.Raw(") {\n")
		w.Line(2, "return")
		w.Line(1, "}")
	}

	// Generic head.
	if m.GlobalHeadGenerator != nil {
		w.writeGenericHeadCall(m.GlobalHeadGenerator, h.InputSession != nil)
	}

	// Body attrs - simple for render404/error pages.
	w.Line(0, "")
	w.Line(1, "bodyAttrs := func(w http.ResponseWriter) {")
	w.Line(2, "httpserve.WriteReloadOnVisibility(w)")
	w.Line(1, "}")

	headArg := "nil"
	if p.GET.OutputHead != nil {
		headArg = outputVar(p.GET.OutputHead.Output)
	}

	w.Line(1, "if err := s.writeHTML(")
	w.Raw("\t\tw, r, ")
	if m.Session != nil {
		sessArg := "sess"
		headNeedsSession := m.GlobalHeadGenerator != nil &&
			m.GlobalHeadGenerator.InputSession
		if p.PageSpecialization == model.PageTypeError500 ||
			(p.PageSpecialization == model.PageTypeError404 &&
				context == "render404" && !headNeedsSession) {
			sessArg = w.sessionType + "{}"
		}
		w.Raw(sessArg)
		w.Raw(", ")
	}
	if m.GlobalHeadGenerator != nil {
		w.Raw("genericHead, ")
	}
	w.Raw(headArg)
	w.Raw(", body, bodyAttrs, nil,\n")
	w.Line(1, "); err != nil {")
	w.Raw("\t\ts.LogErr(\"rendering ")
	w.Raw(p.TypeName)
	w.Raw("\", err)\n")
	w.Line(2, "return")
	w.Line(1, "}")
}
