package generator

import (
	"slices"
	"strings"

	"github.com/romshark/datapages/internal/parser/model"
	"github.com/romshark/datapages/internal/routepattern"
)

// WritePkgAction generates code for the datapagesgen/action package
// and appends it to buffer.
func (w *Writer) WritePkgAction(m *model.App) {
	// Count total page actions.
	nPageActions := 0
	for _, p := range m.Pages {
		nPageActions += len(p.Actions)
	}

	hasActions := len(m.Actions) > 0 || nPageActions > 0
	w.writeActionHeader(hasActions)

	type actionEntry struct {
		funcName   string
		httpMethod string
		route      string
		pathInput  *model.Input
		queryInput *model.Input
	}

	// Collect and sort app actions.
	appActions := make([]actionEntry, len(m.Actions))
	for i, a := range m.Actions {
		appActions[i] = actionEntry{
			funcName:   strings.ToUpper(a.HTTPMethod) + "App" + a.Name,
			httpMethod: a.HTTPMethod,
			route:      a.Route,
			pathInput:  a.InputPath,
			queryInput: a.InputQuery,
		}
	}
	slices.SortFunc(appActions, func(a, b actionEntry) int {
		return strings.Compare(a.funcName, b.funcName)
	})

	// Collect and sort page actions.
	pageActions := make([]actionEntry, 0, nPageActions)
	for _, p := range m.Pages {
		pageSuffix := stripPagePrefix(p.TypeName)
		for _, a := range p.Actions {
			pageActions = append(pageActions, actionEntry{
				funcName:   strings.ToUpper(a.HTTPMethod) + "Page" + pageSuffix + a.Name,
				httpMethod: a.HTTPMethod,
				route:      a.Route,
				pathInput:  a.InputPath,
				queryInput: a.InputQuery,
			})
		}
	}
	slices.SortFunc(pageActions, func(a, b actionEntry) int {
		return strings.Compare(a.funcName, b.funcName)
	})

	// Emit App actions first, then page actions.
	for _, a := range appActions {
		w.writeActionFunc(a.funcName, a.httpMethod, a.route, a.pathInput, a.queryInput)
	}
	for _, a := range pageActions {
		w.writeActionFunc(a.funcName, a.httpMethod, a.route, a.pathInput, a.queryInput)
	}
}

func (w *Writer) writeActionHeader(hasActions bool) {
	w.Line(0, "// Code generated by github.com/romshark/datapages; DO NOT EDIT.")
	w.Line(0, "")
	w.Line(0, "// Package action provides generators for datastar action attribute expressions.")
	w.Line(0, "// Use these in templates instead of hardcoding action URLs.")
	w.Line(0, "package action")
	if !hasActions {
		w.Line(0, "")
		w.Line(0, "// This package is empty because the application defines no actions.")
		w.Line(0, "// Define action handlers in your app package to generate action helpers.")
		return
	}
	w.Line(0, "")
	w.Line(0, "import (")
	w.Line(1, `"net/url"`)
	w.Line(1, `"strconv"`)
	w.Line(1, `"strings"`)
	w.Line(0, ")")
	w.Line(0, "")
	w.Line(0, "type option struct {")
	w.Line(1, "key   string")
	w.Line(1, "value string")
	w.Line(1, "kind  uint8 // 0=option, 1=before, 2=after")
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithOption creates an action option key-value pair.")
	w.Line(0, "// The key is an option name and the value is a raw JavaScript expression.")
	w.Line(0, "//")
	w.Line(0, "// WARNING: Use WithOption only when no typed helper is available.")
	w.Line(0, "// Typed helpers provide compile-time safety:")
	w.Line(0, "//   - WithContentType")
	w.Line(0, "//   - WithFilterSignals")
	w.Line(0, "//   - WithHeaders")
	w.Line(0, "//   - WithOpenWhenHidden")
	w.Line(0, "//   - WithPayload")
	w.Line(0, "//   - WithSelector")
	w.Line(0, "//   - WithRetry")
	w.Line(0, "//   - WithRetryInterval")
	w.Line(0, "//   - WithRetryScaler")
	w.Line(0, "//   - WithRetryMaxWaitMs")
	w.Line(0, "//   - WithRetryMaxCount")
	w.Line(0, "//   - WithRequestCancellation")
	w.Line(0, "//   - WithRequestCancellationController")
	w.Line(0, "//")
	w.Line(0, "// See https://data-star.dev/reference/actions#options")
	w.Line(0, "func WithOption(key, value string) option {")
	w.Line(1, "return option{key: key, value: value}")
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithBefore prepends a JavaScript expression before the action call.")
	w.Line(0, `// Multiple before expressions are joined with "; " separators.`)
	w.Line(0, "func WithBefore(expr string) option {")
	w.Line(1, "return option{value: expr, kind: 1}")
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithAfter appends a JavaScript expression after the action call.")
	w.Line(0, `// Multiple after expressions are joined with "; " separators.`)
	w.Line(0, "func WithAfter(expr string) option {")
	w.Line(1, "return option{value: expr, kind: 2}")
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// ContentType is the type of content to send with an action request.")
	w.Line(0, "//")
	w.Line(0, "// See https://data-star.dev/reference/actions#options")
	w.Line(0, "type ContentType string")
	w.Line(0, "")
	w.Line(0, "const (")
	w.Line(1, "// ContentTypeJSON sends all signals in a JSON request (default).")
	w.Line(1, `ContentTypeJSON ContentType = "'json'"`)
	w.Line(1, "// ContentTypeForm looks for the closest form to the element,")
	w.Line(1, "// performs validation on form elements, and sends them as a form request.")
	w.Line(1, "// No signals are sent. Use WithSelector to target a specific form.")
	w.Line(1, `ContentTypeForm ContentType = "'form'"`)
	w.Line(0, ")")
	w.Line(0, "")
	w.Line(0, "// WithContentType creates an action option that controls the content type:")
	w.Line(0, "//   - ContentTypeJSON (default)")
	w.Line(0, "//   - ContentTypeForm")
	w.Line(0, "func WithContentType(ct ContentType) option {")
	w.Line(1, `return option{key: "contentType", value: string(ct)}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithFilterSignals creates an action option with a regex pattern to match")
	w.Line(0, "// signal paths to include. If exclude is non-empty, it specifies a regex")
	w.Line(0, `// pattern to exclude. Defaults to include all (/.*/), exclude signals`)
	w.Line(0, `// with a _ prefix (/(^_|\._).*/).`)
	w.Line(0, "//")
	w.Line(0, "// See https://data-star.dev/reference/actions#options")
	w.Line(0, "func WithFilterSignals(include, exclude string) option {")
	w.Line(1, `if include == "" {`)
	w.Line(2, `include = ".*"`)
	w.Line(1, `}`)
	w.Line(1, `n := len("{include: /") + len(include) + len("/}")`)
	w.Line(1, `if exclude != "" {`)
	w.Line(2, `n += len(", exclude: /") + len(exclude) + len("/") // before closing }`)
	w.Line(1, `}`)
	w.Line(1, `var b strings.Builder`)
	w.Line(1, `b.Grow(n)`)
	w.Line(1, `b.WriteString("{include: /")`)
	w.Line(1, `b.WriteString(include)`)
	w.Line(1, `if exclude != "" {`)
	w.Line(2, `b.WriteString("/, exclude: /")`)
	w.Line(2, `b.WriteString(exclude)`)
	w.Line(1, `}`)
	w.Line(1, `b.WriteString("/}")`)
	w.Line(1, `return option{key: "filterSignals", value: b.String()}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithHeaders creates an action option with HTTP headers to send with the request.")
	w.Line(0, "func WithHeaders(headers map[string]string) option {")
	w.Line(1, "if len(headers) == 0 {")
	w.Line(2, "return option{}")
	w.Line(1, "}")
	w.Line(1, "// Pre-calculate size assuming no escaping needed (lower bound).")
	w.Line(1, `n := 2 // {}`)
	w.Line(1, `i := 0`)
	w.Line(1, `for k, v := range headers {`)
	w.Line(2, `if i > 0 {`)
	w.Line(3, `n += 2 // ", "`)
	w.Line(2, `}`)
	w.Line(2, `i++`)
	w.Line(2, "n += len(k) + len(v) + 6 // 'k': 'v'")
	w.Line(1, `}`)
	w.Line(1, `var b strings.Builder`)
	w.Line(1, `b.Grow(n)`)
	w.Line(1, `b.WriteByte('{')`)
	w.Line(1, `first := true`)
	w.Line(1, `for k, v := range headers {`)
	w.Line(2, `if !first {`)
	w.Line(3, `b.WriteString(", ")`)
	w.Line(2, `}`)
	w.Line(2, `first = false`)
	w.Line(2, `b.WriteString("'")`)
	w.Line(2, `b.WriteString(escapeJS(k))`)
	w.Line(2, `b.WriteString("': '")`)
	w.Line(2, `b.WriteString(escapeJS(v))`)
	w.Line(2, `b.WriteString("'")`)
	w.Line(1, `}`)
	w.Line(1, `b.WriteByte('}')`)
	w.Line(1, `return option{key: "headers", value: b.String()}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithOpenWhenHidden creates an action option that controls whether to keep")
	w.Line(0, "// the connection open when the page is hidden. Useful for dashboards but can")
	w.Line(0, "// cause a drain on battery life. Defaults to false for get requests,")
	w.Line(0, "// and true for all other HTTP methods.")
	w.Line(0, "func WithOpenWhenHidden(open bool) option {")
	w.Line(1, `return option{key: "openWhenHidden", value: strconv.FormatBool(open)}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithPayload creates an action option with a JavaScript expression")
	w.Line(0, "// for the request payload.")
	w.Line(0, "func WithPayload(expr string) option {")
	w.Line(1, `return option{key: "payload", value: expr}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithSelector creates an action option that specifies a CSS selector for")
	w.Line(0, "// the form to send when ContentType is ContentTypeForm.")
	w.Line(0, "// If not specified, the closest form to the element is used.")
	w.Line(0, "func WithSelector(selector string) option {")
	w.Line(1, `return option{key: "selector", value: "'" + escapeJS(selector) + "'"}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// Retry determines when to retry requests.")
	w.Line(0, "//")
	w.Line(0, "// See https://data-star.dev/reference/actions#options")
	w.Line(0, "type Retry string")
	w.Line(0, "")
	w.Line(0, "const (")
	w.Line(1, "// RetryAuto retries on network errors only (default).")
	w.Line(1, `RetryAuto Retry = "'auto'"`)
	w.Line(1, "// RetryError retries on 4xx and 5xx responses.")
	w.Line(1, `RetryError Retry = "'error'"`)
	w.Line(1, "// RetryAlways retries on all non-204 responses except redirects.")
	w.Line(1, `RetryAlways Retry = "'always'"`)
	w.Line(1, "// RetryNever disables retries.")
	w.Line(1, `RetryNever Retry = "'never'"`)
	w.Line(0, ")")
	w.Line(0, "")
	w.Line(0, "// WithRetry creates an action option that determines when to retry requests:")
	w.Line(0, "//   - RetryAuto (default)")
	w.Line(0, "//   - RetryError")
	w.Line(0, "//   - RetryAlways")
	w.Line(0, "//   - RetryNever")
	w.Line(0, "func WithRetry(r Retry) option {")
	w.Line(1, `return option{key: "retry", value: string(r)}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithRetryInterval creates an action option for the retry interval in milliseconds.")
	w.Line(0, "// Defaults to 1000 (one second).")
	w.Line(0, "func WithRetryInterval(ms int) option {")
	w.Line(1, `return option{key: "retryInterval", value: strconv.Itoa(ms)}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithRetryScaler creates an action option for the numeric multiplier")
	w.Line(0, "// applied to scale retry wait times. Defaults to 2.")
	w.Line(0, "func WithRetryScaler(multiplier float64) option {")
	w.Line(1, `return option{key: "retryScaler", value: strconv.FormatFloat(multiplier, 'f', -1, 64)}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithRetryMaxWaitMs creates an action option for the maximum allowable wait time")
	w.Line(0, "// in milliseconds between retries. Defaults to 30000 (30 seconds).")
	w.Line(0, "func WithRetryMaxWaitMs(ms int) option {")
	w.Line(1, `return option{key: "retryMaxWaitMs", value: strconv.Itoa(ms)}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithRetryMaxCount creates an action option for the maximum number")
	w.Line(0, "// of retry attempts. Defaults to 10.")
	w.Line(0, "func WithRetryMaxCount(count int) option {")
	w.Line(1, `return option{key: "retryMaxCount", value: strconv.Itoa(count)}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// RequestCancellation controls request cancellation behavior.")
	w.Line(0, "//")
	w.Line(0, "// See https://data-star.dev/reference/actions#request-cancellation")
	w.Line(0, "type RequestCancellation string")
	w.Line(0, "")
	w.Line(0, "const (")
	w.Line(1, "// RequestCancellationAuto cancels existing requests on the same element (default).")
	w.Line(1, `RequestCancellationAuto RequestCancellation = "'auto'"`)
	w.Line(1, "// RequestCancellationCleanup cancels existing requests on the same element")
	w.Line(1, "// and on element or attribute cleanup.")
	w.Line(1, `RequestCancellationCleanup RequestCancellation = "'cleanup'"`)
	w.Line(1, "// RequestCancellationDisabled allows concurrent requests.")
	w.Line(1, `RequestCancellationDisabled RequestCancellation = "'disabled'"`)
	w.Line(0, ")")
	w.Line(0, "")
	w.Line(0, "// WithRequestCancellation creates an action option that controls")
	w.Line(0, "// request cancellation behavior:")
	w.Line(0, "//   - RequestCancellationAuto (default)")
	w.Line(0, "//   - RequestCancellationCleanup")
	w.Line(0, "//   - RequestCancellationDisabled")
	w.Line(0, "func WithRequestCancellation(rc RequestCancellation) option {")
	w.Line(1, `return option{key: "requestCancellation", value: string(rc)}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// WithRequestCancellationController creates an action option that uses")
	w.Line(0, "// a JavaScript AbortController expression for custom request cancellation.")
	w.Line(0, "// The expression should reference a signal holding an AbortController instance,")
	w.Line(0, `// for example "$controller".`)
	w.Line(0, "//")
	w.Line(0, "// See https://data-star.dev/reference/actions#request-cancellation")
	w.Line(0, "func WithRequestCancellationController(expr string) option {")
	w.Line(1, `return option{key: "requestCancellation", value: expr}`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// escapeJS escapes single quotes and backslashes for use in JS single-quoted strings.")
	w.Line(0, "func escapeJS(s string) string {")
	w.Raw("\ts = strings.ReplaceAll(s, \"\\\\\", \"\\\\\\\\\")\n")
	w.Raw("\ts = strings.ReplaceAll(s, \"'\", \"\\\\'\")\n")
	w.Line(1, "return s")
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "// isEntry reports whether an option belongs in the options object.")
	w.Line(0, "//")
	w.Line(0, "// A helper given nothing to say returns the zero option: WithHeaders of")
	w.Line(0, "// an empty map, say, which is what a template computing its headers")
	w.Line(0, "// produces whenever the map comes out empty. Writing it would put")
	w.Line(0, `// "{: }" in the expression, which no browser can parse.`)
	w.Line(0, "func isEntry(o option) bool {")
	w.Line(1, `return o.kind == 0 && o.key != ""`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "func writeOptions(b *strings.Builder, options []option) {")
	w.Line(1, "any := false")
	w.Line(1, "for _, o := range options {")
	w.Line(2, "if isEntry(o) {")
	w.Line(3, "any = true")
	w.Line(3, "break")
	w.Line(2, "}")
	w.Line(1, "}")
	w.Line(1, "if !any {")
	w.Line(2, "return")
	w.Line(1, "}")
	w.Line(1, `b.WriteString(", {")`)
	w.Line(1, "first := true")
	w.Line(1, "for _, o := range options {")
	w.Line(2, "if !isEntry(o) {")
	w.Line(3, "continue")
	w.Line(2, "}")
	w.Line(2, "if !first {")
	w.Line(3, `b.WriteString(", ")`)
	w.Line(2, "}")
	w.Line(2, "first = false")
	w.Line(2, "b.WriteString(o.key)")
	w.Line(2, `b.WriteString(": ")`)
	w.Line(2, "b.WriteString(o.value)")
	w.Line(1, "}")
	w.Line(1, `b.WriteString("}")`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "func optionsLen(options []option) int {")
	w.Line(1, "if len(options) == 0 {")
	w.Line(2, "return 0")
	w.Line(1, "}")
	w.Line(1, "n := 0")
	w.Line(1, "count := 0")
	w.Line(1, "for _, o := range options {")
	w.Line(2, "if !isEntry(o) {")
	w.Line(3, "continue")
	w.Line(2, "}")
	w.Line(2, "if count > 0 {")
	w.Line(3, `n += len(", ")`)
	w.Line(2, "}")
	w.Line(2, "count++")
	w.Line(2, `n += len(o.key) + len(": ") + len(o.value)`)
	w.Line(1, "}")
	w.Line(1, "if count == 0 {")
	w.Line(2, "return 0")
	w.Line(1, "}")
	w.Line(1, `return n + len(", {}")`)
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "func writeBefore(b *strings.Builder, options []option) {")
	w.Line(1, "for _, o := range options {")
	w.Line(2, "if o.kind == 1 {")
	w.Line(3, "b.WriteString(o.value)")
	w.Line(3, `b.WriteString("; ")`)
	w.Line(2, "}")
	w.Line(1, "}")
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "func writeAfter(b *strings.Builder, options []option) {")
	w.Line(1, "for _, o := range options {")
	w.Line(2, "if o.kind == 2 {")
	w.Line(3, `b.WriteString("; ")`)
	w.Line(3, "b.WriteString(o.value)")
	w.Line(2, "}")
	w.Line(1, "}")
	w.Line(0, "}")
	w.Line(0, "")
	w.Line(0, "func beforeAfterLen(options []option) (before, after int) {")
	w.Line(1, "for _, o := range options {")
	w.Line(2, "switch o.kind {")
	w.Line(2, "case 1:")
	w.Line(3, `before += len(o.value) + len("; ")`)
	w.Line(2, "case 2:")
	w.Line(3, `after += len("; ") + len(o.value)`)
	w.Line(2, "}")
	w.Line(1, "}")
	w.Line(1, "return")
	w.Line(0, "}")
}

// writeActionRouteComment writes a doc comment line like
// "// FuncName references /route/\n".
// It strips {$} and ensures a trailing slash.
func (w *Writer) writeActionRouteComment(funcName, route string) {
	w.Raw("// ")
	w.Raw(funcName)
	w.Raw(" references ")
	w.writeRouteURL(route)
	w.Byte('\n')
}

func (w *Writer) writeActionFunc(
	funcName string,
	httpMethod string,
	route string,
	pathInput *model.Input,
	queryInput *model.Input,
) {
	pathVars := slices.Collect(routepattern.Vars(route))
	hasPathVars := len(pathVars) > 0
	params := w.pathParamInfos(pathInput, pathVars)

	var queryFields []structFieldInfo
	if queryInput != nil {
		queryFields = w.structFields(queryInput.Type.Resolved)
	}
	hasQuery := len(queryFields) > 0

	method := strings.ToLower(httpMethod)

	// Doc comment.
	w.Line(0, "")
	w.writeActionRouteComment(funcName, route)

	if !hasPathVars && !hasQuery {
		w.Linef(0, "func %s(options ...option) string {", funcName)
		w.Line(1, "if len(options) == 0 {")
		w.Raw("\t\treturn \"@")
		w.Raw(method)
		w.Raw("('")
		w.writeRouteURL(route)
		w.Raw("')\"\n")
		w.Line(1, "}")
		w.Line(1, "var b strings.Builder")
		w.Line(1, "bl, al := beforeAfterLen(options)")
		w.Raw("\tb.Grow(bl + len(\"@")
		w.Raw(method)
		w.Raw("('")
		w.writeRouteURL(route)
		w.Raw("'\") + optionsLen(options) + len(\")\") + al")
		w.Raw(")\n")
		w.Line(1, "writeBefore(&b, options)")
		w.Raw("\tb.WriteString(\"@")
		w.Raw(method)
		w.Raw("('")
		w.writeRouteURL(route)
		w.Raw("'\")\n")
		w.Line(1, "writeOptions(&b, options)")
		w.Line(1, "b.WriteByte(')')")
		w.Line(1, "writeAfter(&b, options)")
		w.Line(1, "return b.String()")
		w.Line(0, "}")
		return
	}

	if hasPathVars && !hasQuery {
		w.writeActionFuncPathOnly(funcName, method, route, params)
		return
	}

	if !hasPathVars && hasQuery {
		w.writeActionFuncQueryOnly(funcName, method, route, queryFields)
		w.writeActionQueryType(funcName, queryFields)
		return
	}

	// Both path and query.
	w.writeActionFuncPathAndQuery(funcName, method, route, params, queryFields)
	w.writeActionQueryType(funcName, queryFields)
}

func (w *Writer) writeActionFuncPathOnly(
	funcName string,
	method string,
	route string,
	params []pathParamInfo,
) {
	lo := newHrefLocals(params, nil)
	literals, _ := routeSegments(route)

	// func FuncName(params, options ...option) string {
	w.Raw("func ")
	w.Raw(funcName)
	w.Byte('(')
	w.writeTypedParams(params)
	w.Raw(", options ...option) string {\n")

	// Pre-convert non-string params to strings.
	w.writePathPreConvert(params)

	w.Linef(1, "var %s strings.Builder", lo.builder)
	w.Linef(1, "%s, %s := beforeAfterLen(options)", lo.beforeLen, lo.afterLen)

	// b.Grow(bl + len("@method('lit0") +
	//  len(v0) + ... + len("litN'") + optionsLen + len(")") + al)
	w.Rawf("\t%s.Grow(%s + len(\"@", lo.builder, lo.beforeLen)
	w.Raw(method)
	w.Raw("('")
	w.Raw(literals[0])
	w.Raw("\")")
	for i, p := range params {
		w.Raw(" + len(")
		w.Raw(pathVarStrExpr(p))
		w.Raw(") + len(\"")
		w.Raw(literals[i+1])
		if i == len(params)-1 {
			w.Raw("'")
		}
		w.Raw("\")")
	}
	w.Raw(" + optionsLen(options) + len(\")\") + al")
	w.Raw(")\n")

	// writeBefore + b.WriteString("@method('lit0")
	w.Linef(1, "writeBefore(&%s, options)", lo.builder)
	w.Rawf("\t%s.WriteString(\"@", lo.builder)
	w.Raw(method)
	w.Raw("('")
	w.Raw(literals[0])
	w.Raw("\")\n")
	for i, p := range params {
		w.Raw("\tb.WriteString(")
		w.Raw(pathVarStrExpr(p))
		w.Raw(")\n")
		w.Rawf("\t%s.WriteString(\"", lo.builder)
		w.Raw(literals[i+1])
		if i == len(params)-1 {
			w.Raw("'")
		}
		w.Raw("\")\n")
	}

	w.Linef(1, "writeOptions(&%s, options)", lo.builder)
	w.Line(1, "b.WriteByte(')')")
	w.Linef(1, "writeAfter(&%s, options)", lo.builder)
	w.Linef(1, "return %s.String()", lo.builder)
	w.Line(0, "}")
}

func (w *Writer) writeActionFuncQueryOnly(
	funcName string,
	method string,
	route string,
	fields []structFieldInfo,
) {
	lo := newHrefLocals(nil, fields)
	// func FuncName(query QueryFuncName, options ...option) string {
	w.Raw("func ")
	w.Raw(funcName)
	w.Raw("(query Query")
	w.Raw(funcName)
	w.Raw(", options ...option) string {\n")

	// Pre-convert non-string fields to strings.
	w.writeQueryPreConvert(lo, fields)

	// anyQuery check.
	w.writeAnyCheck(lo.anyQuery, fields)
	w.Line(0, "")

	// Builder and length calculation.
	w.Linef(1, "var %s strings.Builder", lo.builder)
	w.Linef(1, "%s, %s := beforeAfterLen(options)", lo.beforeLen, lo.afterLen)
	w.Raw("\tl := bl + len(\"@")
	w.Raw(method)
	w.Raw("('")
	w.writeRouteURL(route)
	w.Raw("'\") + optionsLen(options) + len(\")\") + al\n")
	w.Linef(1, "if %s {", lo.anyQuery)
	w.Linef(2, "%s += len(\"?\")", lo.length)
	w.Line(1, "}")

	// Query param length accumulation.
	w.Linef(1, "%s := 0", lo.count)
	for i, f := range fields {
		tag := queryTagValue(f.Tag)
		w.writeIfZeroCheck(1, "query."+f.Name, f.Type)
		w.Linef(2, "if %s > 0 {", lo.count)
		w.Linef(3, "%s += len(\"&\")", lo.length)
		w.Line(2, "}")
		if i < len(fields)-1 {
			w.Linef(2, "%s++", lo.count)
		}
		w.Linef(2, "%s += len(%q) + len(%s)", lo.length, tag+"=", lo.queryStr[tag])
		w.Line(1, "}")
	}
	w.Line(0, "")

	// Grow and write.
	w.Linef(1, "%s.Grow(%s)", lo.builder, lo.length)
	w.Line(0, "")
	w.Linef(1, "writeBefore(&%s, options)", lo.builder)
	w.Rawf("\t%s.WriteString(\"@", lo.builder)
	w.Raw(method)
	w.Raw("('")
	w.writeRouteURL(route)
	w.Raw("\")\n")
	w.Linef(1, "if %s {", lo.anyQuery)
	w.Linef(2, "%s.WriteString(\"?\")", lo.builder)
	w.Line(1, "}")

	// Write query params.
	w.Linef(1, "%s = 0", lo.count)
	for i, f := range fields {
		tag := queryTagValue(f.Tag)
		w.writeIfZeroCheck(1, "query."+f.Name, f.Type)
		w.Linef(2, "if %s > 0 {", lo.count)
		w.Linef(3, "%s.WriteString(\"&\")", lo.builder)
		w.Line(2, "}")
		if i < len(fields)-1 {
			w.Linef(2, "%s++", lo.count)
		}
		w.Linef(2, "%s.WriteString(%q)", lo.builder, tag+"=")
		w.Linef(2, "%s.WriteString(%s)", lo.builder, lo.queryStr[tag])
		w.Line(1, "}")
	}

	w.Line(1, `b.WriteString("'")`)
	w.Linef(1, "writeOptions(&%s, options)", lo.builder)
	w.Line(1, "b.WriteByte(')')")
	w.Linef(1, "writeAfter(&%s, options)", lo.builder)
	w.Line(0, "")
	w.Linef(1, "return %s.String()", lo.builder)
	w.Line(0, "}")
}

func (w *Writer) writeActionFuncPathAndQuery(
	funcName string,
	method string,
	route string,
	params []pathParamInfo,
	fields []structFieldInfo,
) {
	lo := newHrefLocals(params, fields)
	literals, _ := routeSegments(route)

	// func FuncName(params, query QueryFuncName, options ...option) string {
	w.Raw("func ")
	w.Raw(funcName)
	w.Byte('(')
	w.writeTypedParams(params)
	w.Raw(", query Query")
	w.Raw(funcName)
	w.Raw(", options ...option) string {\n")

	// Pre-convert non-string path params.
	w.writePathPreConvert(params)

	// Pre-convert non-string query fields to strings.
	w.writeQueryPreConvert(lo, fields)

	// anyQuery check.
	w.writeAnyCheck(lo.anyQuery, fields)
	w.Line(0, "")

	// Builder and length calculation.
	w.Linef(1, "var %s strings.Builder", lo.builder)
	w.Linef(1, "%s, %s := beforeAfterLen(options)", lo.beforeLen, lo.afterLen)

	// l := bl + len("@method('lit0") + len(v0) + len("lit1") + ... + len("')")
	w.Raw("\tl := bl + len(\"@")
	w.Raw(method)
	w.Raw("('")
	w.Raw(literals[0])
	w.Raw("\")")
	for i, p := range params {
		w.Raw(" + len(")
		w.Raw(pathVarStrExpr(p))
		w.Raw(") + len(\"")
		w.Raw(literals[i+1])
		w.Raw("\")")
	}
	w.Raw(" + len(\"'\") + optionsLen(options) + len(\")\") + al\n")

	w.Linef(1, "if %s {", lo.anyQuery)
	w.Linef(2, "%s += len(\"?\")", lo.length)
	w.Line(1, "}")

	// Query param length accumulation.
	w.Linef(1, "%s := 0", lo.count)
	for i, f := range fields {
		tag := queryTagValue(f.Tag)
		w.writeIfZeroCheck(1, "query."+f.Name, f.Type)
		w.Linef(2, "if %s > 0 {", lo.count)
		w.Linef(3, "%s += len(\"&\")", lo.length)
		w.Line(2, "}")
		if i < len(fields)-1 {
			w.Linef(2, "%s++", lo.count)
		}
		w.Linef(2, "%s += len(%q) + len(%s)", lo.length, tag+"=", lo.queryStr[tag])
		w.Line(1, "}")
	}
	w.Line(0, "")

	// Grow and write path segments.
	w.Linef(1, "%s.Grow(%s)", lo.builder, lo.length)
	w.Line(0, "")
	w.Linef(1, "writeBefore(&%s, options)", lo.builder)
	w.Rawf("\t%s.WriteString(\"@", lo.builder)
	w.Raw(method)
	w.Raw("('")
	w.Raw(literals[0])
	w.Raw("\")\n")
	for i, p := range params {
		w.Raw("\tb.WriteString(")
		w.Raw(pathVarStrExpr(p))
		w.Raw(")\n")
		w.Rawf("\t%s.WriteString(\"", lo.builder)
		w.Raw(literals[i+1])
		w.Raw("\")\n")
	}

	w.Linef(1, "if %s {", lo.anyQuery)
	w.Linef(2, "%s.WriteString(\"?\")", lo.builder)
	w.Line(1, "}")

	// Write query params.
	w.Linef(1, "%s = 0", lo.count)
	for i, f := range fields {
		tag := queryTagValue(f.Tag)
		w.writeIfZeroCheck(1, "query."+f.Name, f.Type)
		w.Linef(2, "if %s > 0 {", lo.count)
		w.Linef(3, "%s.WriteString(\"&\")", lo.builder)
		w.Line(2, "}")
		if i < len(fields)-1 {
			w.Linef(2, "%s++", lo.count)
		}
		w.Linef(2, "%s.WriteString(%q)", lo.builder, tag+"=")
		w.Linef(2, "%s.WriteString(%s)", lo.builder, lo.queryStr[tag])
		w.Line(1, "}")
	}

	w.Line(1, `b.WriteString("'")`)
	w.Linef(1, "writeOptions(&%s, options)", lo.builder)
	w.Line(1, "b.WriteByte(')')")
	w.Linef(1, "writeAfter(&%s, options)", lo.builder)
	w.Line(0, "")
	w.Linef(1, "return %s.String()", lo.builder)
	w.Line(0, "}")
}

func (w *Writer) writeActionQueryType(funcName string, fields []structFieldInfo) {
	w.Line(0, "")
	w.Raw("type Query")
	w.Raw(funcName)
	w.Raw(" struct {\n")

	// Find longest field name for alignment.
	maxNameLen := 0
	for _, f := range fields {
		if len(f.Name) > maxNameLen {
			maxNameLen = len(f.Name)
		}
	}
	// Find longest type name for alignment.
	maxTypeLen := 0
	for _, f := range fields {
		typeName := fieldTypeName(f.Type)
		if len(typeName) > maxTypeLen {
			maxTypeLen = len(typeName)
		}
	}

	for _, f := range fields {
		tag := queryTagValue(f.Tag)
		typeName := fieldTypeName(f.Type)
		w.Linef(1, "\t%-*s %-*s `query:\"%s\"`",
			maxNameLen, f.Name, maxTypeLen, typeName, tag)
	}

	w.Line(0, "}")
}
