// Code generated by github.com/romshark/datapages; DO NOT EDIT.

// Package href provides generators for datastar anchor hypertext references.
// Use these in templates instead of hardcoding URLs.
package href

import (
	"log/slog"
	"strconv"
	"strings"
	"sync/atomic"

	"github.com/romshark/datapages/runtime/hrefcheck"
)

var logger atomic.Pointer[slog.Logger]

func init() { logger.Store(slog.Default()) }

// SetLogger sets the logger used by External to log invalid URLs.
// Passing nil resets to the default logger. It is safe for concurrent use.
func SetLogger(l *slog.Logger) {
	if l == nil {
		l = slog.Default()
	}
	logger.Store(l)
}

func getLogger() *slog.Logger { return logger.Load() }

// External returns url as-is for use in href attributes.
// It warns about a URL that belongs in a generated builder,
// and about one the templ sanitizer drops.
func External(url string) string {
	switch {
	case !hrefcheck.IsAllowedNonRelativeHref(url):
		getLogger().Warn("href.External called with app-internal URL", "url", url)
	case !hrefcheck.IsRenderedAsWritten(url):
		getLogger().Warn("href.External called with a URL the templ sanitizer drops, "+
			"which renders it as about:invalid", "url", url)
	}
	return url
}

// PageBackground references /background/{$}
func PageBackground() string { return "/background/" }

// PageGone references /gone/{$}
func PageGone() string { return "/gone/" }

// PageIndex references /{$}
func PageIndex() string { return "/" }

// PageMaybe references /maybe/{$}
func PageMaybe(query QueryPageMaybe) string {
	var (
		goStr string
	)

	if query.Go {
		goStr = strconv.FormatBool(query.Go)
	}

	anyQuery := query.Go

	var b strings.Builder
	l := len("/maybe/")
	if anyQuery {
		l += len("?")
	}

	// n = number of query params already accounted for (for '&')
	n := 0

	if query.Go {
		if n > 0 {
			l += len("&")
		}
		n++
		l += len("go=") + len(goStr)
	}
	_ = n

	b.Grow(l)

	b.WriteString("/maybe/")
	if anyQuery {
		b.WriteString("?")
	}

	n = 0

	if query.Go {
		if n > 0 {
			b.WriteString("&")
		}
		b.WriteString("go=")
		b.WriteString(goStr)
	}

	return b.String()
}

// QueryPageMaybe is the query parameters for PageMaybe
type QueryPageMaybe struct {
	Go bool `query:"go"`
}

// PageNoRefresh references /no-refresh/{$}
func PageNoRefresh() string { return "/no-refresh/" }
